## PANDAS ASSIGNMENT

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../Pandas Assignment 1/employees.csv')
df

,employee_id,full_name,department,job_title,hire_date,salary,bonus,years_experience,email,phone,city,state,performance_rating,status,remote_work,manager_name,last_review_date
0,1034,Grace Ferreira,IT,Software Engineer,11/08/2021,87609,NaN,10,grace.ferreira@retailco.com,779 898 3950,Nashville,TN,2.0,Active,No,Sophie Khan,4/15/2023
1,1056,Sonia Chen,Operations,Logistics Coordinator,01/21/2019,58508,NaN,4,sonia.chen@retailco.com,(736) 569-2108,Nashville,TN,5.0,Active,No,Hugo Muller,12/01/2024
2,1156,Wei Khan,Finance,Finance Manager,02/08/2019,64418,NaN,1,wei.khan@retailco.com,NaN,Nashville,TN,2.0,Inactive,No,Noah Kowalski,2/23/2024
3,1081,Noah Brown,Operations,Operations Manager,07/01/2016,58431,1560.0,2,noah.brown@retailco.com,(392) 979-4555,Columbus,OH,5.0,Active,Hybrid,NaN,12/25/2023
4,1072,Wei Wilson,OPERATIONS,Operations Manager,08/06/2018,63197,NaN,6,wei.wilson@retailco.com,747-956-1611,Chicago,IL,1.0,On Leave,Hybrid,Ahmed Wilson,01/01/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,1110,Ravi Lin,HR,Recruiter,02/08/2018,54530,1260.0,7,ravi.lin@retailco.com,(977) 873-7164,Portland,OR,1.0,Active,Hybrid,Jack Bello,01/08/2023
220,1196,Ivy Fischer,CUSTOMER SUPPORT,Customer Success Manager,15/06/2018,65535,7189.0,13,ivy.fischer@retailco.com,292 939 9202,Nashville,TN,4.0,Active,No,Hana Khan,12/07/2025
221,1138,Sophie Brown,HR,HR Business Partner,2/14/2014,50969,NaN,2,sophie.brown@retailco.com,906 689 7909,Chicago,IL,4.0,On Leave,No,Sophie Lee,15/11/2025
222,1036,Mike Popescu,Customer Support,Technical Support Agent,01/19/2019,74124,3700.0,15,mike.popescu@retailco.com,894.973.3240,Dallas,TX,2.0,Active,Yes,Grace Yamamoto,05/11/2023
223,1027,Sarah Wilson,MARKETING,SEO Specialist,03/03/2016,59256,NaN,7,sarah.wilson@retailco.com,840.803.4241,Atlanta,GA,1.0,Active,No,Nora Lee,10/24/2024

**Question1.** 
 - (a) Using .iloc[], select the first 5 rows and only the full_name and department columns.
 - (b) Set employee_id as the index with df.set_index("employee_id"), then use .loc[] to retrieve the row for
employee 1050.

In [5]:
df.iloc[0:5,1:3]

          full_name   department
0    Grace Ferreira           IT
1       Sonia  Chen   Operations
2          Wei Khan      Finance
3        Noah Brown  Operations
4       Wei  Wilson  OPERATIONS

In [7]:
df.set_index("employee_id").loc[1050]

full_name                        Tom Ferreira
department                   Customer Support
job_title              Customer Success Manager
hire_date                            20/09/2020
salary                                    67930
bonus                                    5337.0
years_experience                             15
email                 tom.ferreira@retailco.com
phone                            (716) 861-3827
city                                  San Diego
state                                        CA
performance_rating                          3.0
status                                 Inactive
remote_work                              Hybrid
manager_name                          Tom Smith
last_review_date                     07/14/2024
Name: 1050, dtype: object

**Question2.** 
- (a) Select all employees with a salary greater than $60,000.
- (b) Select all employees with a performance_rating of 5 AND more than 5 years of experience. (Hint:
combine conditions with & and wrap each condition in parentheses.)

In [11]:
df[df['salary'] > 60000]

,employee_id,full_name,department,job_title,hire_date,salary,bonus,years_experience,email,phone,city,state,performance_rating,status,remote_work,manager_name,last_review_date
0,1034,Grace Ferreira,IT,Software Engineer,11/08/2021,87609,NaN,10,grace.ferreira@retailco.com,779 898 3950,Nashville,TN,2.0,Active,No,Sophie Khan,4/15/2023
2,1156,Wei Khan,Finance,Finance Manager,02/08/2019,64418,NaN,1,wei.khan@retailco.com,NaN,Nashville,TN,2.0,Inactive,No,Noah Kowalski,2/23/2024
4,1072,Wei Wilson,OPERATIONS,Operations Manager,08/06/2018,63197,NaN,6,wei.wilson@retailco.com,747-956-1611,Chicago,IL,1.0,On Leave,Hybrid,Ahmed Wilson,01/01/2024
5,1071,Omar Patel,HR,HR Business Partner,02/14/2012,64644,NaN,8,omar.patel@retailco.com,340.311.4920,Portland,OR,3.0,Active,Hybrid,Ravi Kim,25/11/2023
6,1109,Ali Suzuki,HR,Payroll Specialist,15/09/2013,60408,2146.0,10,ali.suzuki@retailco.com,(610) 270-8620,Columbus,OH,1.0,Inactive,Hybrid,Lena Fischer,10/26/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,1125,Diego Ruiz,Finance,Financial Analyst,10/20/2014,67355,9054.0,3,diego.ruiz@retailco.com,785 823 8750,Nashville,TN,3.0,Active,Yes,Laura Khan,07/11/2023
217,1157,Sam Haddad,Finance,Finance Manager,15/03/2020,82702,10636.0,12,sam.haddad@retailco.com,728-615-6781,Austin,TX,4.0,Active,Yes,Amy Nguyen,09/11/2025
218,1055,Rosa Ruiz,IT,Systems Administrator,02/02/2016,80687,8068.0,4,rosa.ruiz@retailco.com,761-944-9647,Portland,OR,1.0,Active,Hybrid,Nora Lee,03/08/2025
220,1196,Ivy Fischer,CUSTOMER SUPPORT,Customer Success Manager,15/06/2018,65535,7189.0,13,ivy.fischer@retailco.com,292 939 9202,Nashville,TN,4.0,Active,No,Hana Khan,12/07/2025
222,1036,Mike Popescu,Customer Support,Technical Support Agent,01/19/2019,74124,3700.0,15,mike.popescu@retailco.com,894.973.3240,Dallas,TX,2.0,Active,Yes,Grace Yamamoto,05/11/2023

In [16]:
df[(df['performance_rating'] == 5) & (df['years_experience'] > 5)]

,employee_id,full_name,department,job_title,hire_date,salary,bonus,years_experience,email,phone,city,state,performance_rating,status,remote_work,manager_name,last_review_date
35,1175,Lena Garcia,Finance,Finance Manager,05/03/2015,73407,7165.0,9,lena.garcia@retailco.com,774 647 7467,Nashville,TN,5.0,Inactive,No,Ravi Davis,10/26/2025
38,1120,Aisha Rossi,marketing,Content Strategist,02/03/2016,77632,5341.0,15,aisha.rossi@retailco.com,366-662-2207,Columbus,OH,5.0,On Leave,Yes,Laura Martin,24/03/2024
40,1070,Alina Silva,HR,HR Business Partner,12/09/2020,63558,NaN,8,alina.silva@retailco.com,989.495.4396,Charlotte,NC,5.0,Active,Yes,Layla Zhang,09/13/2025
44,1096,Emma Ferreira,it,Software Engineer,05/05/2019,80370,3084.0,9,emma.ferreira@retailco.com,633 390 8973,Boston,MA,5.0,Active,No,Sonia Marquez,10/02/2024
48,1040,Oliver Lin,Sales,Sales Associate,26/05/2020,62521,2918.0,10,oliver.lin@retailco.com,438-536-3417,Atlanta,GA,5.0,Active,Hybrid,Sarah Turner,03/01/2023
51,1104,Felix Hassan,marketing,Content Strategist,02/11/2016,58570,NaN,8,felix.hassan@retailco.com,(874) 508-4366,Nashville,TN,5.0,On Leave,Yes,Keiko Costa,4/16/2023
54,1108,Claire Kim,Marketing,SEO Specialist,05/07/2017,59770,6433.0,8,claire.kim@retailco.com,NaN,Raleigh,NC,5.0,Inactive,Hybrid,Mike Smith,9/26/2023
58,1044,Liam Hassan,Customer Support,Customer Success Manager,01/06/2017,57148,7422.0,8,liam.hassan@retailco.com,(823) 873-5381,Dallas,TX,5.0,Active,Hybrid,David Khan,13/11/2025
74,1041,Peter Chen,IT,Software Engineer,08/28/2012,90525,7415.0,13,peter.chen@retailco.com,715 426 1710,Austin,TX,5.0,Active,Yes,Keiko Alvarez,08/23/2023
80,1028,Oliver Lin,OPERATIONS,Operations Manager,09/21/2019,74378,10088.0,15,oliver.lin@retailco.com,(434) 890-1339,Boston,MA,5.0,Active,Yes,Maria Popescu,10/14/2023
83,1063,Diego Alvarez,IT,Systems Administrator,11/20/2014,82128,10674.0,7,diego.alvarez@retailco.com,829.746.2530,Atlanta,GA,5.0,Active,Yes,Paula Singh,02/10/2024
87,1075,Leo Wilson,Operations,Operations Manager,05/09/2021,62907,6131.0,6,leo.wilson@retailco.com,279.777.2838,Phoenix,AZ,5.0,Active,Hybrid,NaN,08/04/2025
97,1162,Claire Novak,hr,Recruiter,09/13/2015,68777,5701.0,15,claire.novak@retailco.com,953 341 2951,Seattle,WA,5.0,Active,Yes,Mei Ferreira,12/22/2025
100,1174,Ruth Ivanova,Operations,Logistics Coordinator,10/03/2016,80052,6128.0,14,ruth.ivanova@retailco.com,693.752.4721,Minneapolis,MN,5.0,Active,No,Ruth Alvarez,NaN
107,1208,David Gomez,Marketing,SEO Specialist,8/13/2020,73323,NaN,14,david.gomez@retailco.com,(615) 931-2752,Dallas,TX,5.0,Active,No,Peter Andersson,18/04/2025
116,1159,Priya Larsson,OPERATIONS,Operations Analyst,19/10/2019,78355,3305.0,14,priya.larsson@retailco.com,838-875-9369,Columbus,OH,5.0,Active,Hybrid,NaN,04/03/2024
140,1006,Ingrid Petrov,hr,HR Business Partner,09/08/2013,65552,NaN,14,ingrid.petrov@retailco.com,207-272-1964,Columbus,OH,5.0,On Leave,Hybrid,Mei Gomez,09/05/2023
163,1093,Liam Johnson,SALES,Account Executive,05/11/2017,61656,7424.0,7,liam.johnson@retailco.com,(694) 307-5840,Atlanta,GA,5.0,Active,No,Ali Walker,08/12/2025
169,1077,Ben Fischer,operations,Warehouse Supervisor,27/04/2023,81352,8847.0,14,ben.fischer@retailco.com,321.382.9802,Atlanta,GA,5.0,On Leave,No,NaN,8/22/2024
174,1031,Omar Muller,OPERATIONS,Operations Manager,05/24/2012,74476,5203.0,15,omar.muller@retailco.com,271-482-7798,Miami,FL,5.0,Active,Hybrid,NaN,16/11/2025
193,1068,Ben Zhang,finance,Accountant,08/09/2021,78018,6730.0,9,ben.zhang@retailco.com,(577) 539-2795,Austin,TX,5.0,Active,Hybrid,Ali Haddad,10/08/2025
195,1170,Dmitri Ivanova,Customer Support,Technical Support Agent,5/16/2015,65026,NaN,10,dmitri.ivanova@retailco.com,NaN,Chicago,IL,5.0,Inactive,No,Grace Marquez,NaN
198,1163,Felix Yamamoto,Sales,Account Executive,11/16/2014,64294,NaN,13,felix.yamamoto@retailco.com,NaN,Chicago,IL,5.0,Inactive,Hybrid,Felix Larsen,NaN
212,1066,Alina Smith,it,Software Engineer,06/25/2023,87248,9166.0,9,alina.smith@retailco.com,NaN,Miami,FL,5.0,Active,No,Liam Ahmed,1/19/2024

**Question3.** 
- Frequency table for department. Note anything strange in the output — why might departments that look
the same get counted separately?

In [20]:
df['department'].value_counts()

department
IT                    15
Operations            10
HR                     8
HR                     8
IT                     8
finance                7
 sales                 7
  Operations           6
  HR                   6
Customer Support       5
Operations             5
  IT                   5
MARKETING              5
CUSTOMER SUPPORT       5
Customer Support       4
FINANCE                4
Marketing              4
  Marketing            4
Finance                4
marketing              4
Sales                  4
 finance               4
  Sales                4
hr                     4
OPERATIONS             4
OPERATIONS             4
 HR                    3
 Operations            3
  Customer Support     3
 hr                    3
CUSTOMER SUPPORT       3
SALES                  3
operations             3
Customer Support       3
IT                     3
it                     3
SALES                  3
Sales                  3
Sales                  3
 operations            3
 Finance               3
 Marketing             3
MARKETING              3
sales                  3
Operations             2
  Finance              2
Finance                2
 it                    2
 customer support      2
 marketing             2
Marketing              2
Finance                2
 IT                    1
FINANCE                1
customer support       1
HR                     1
 Sales                 1
 Customer Support      1
Name: count, dtype: int64

**Question4.** 
- Create a new column department_clean by stripping extra whitespace from department.

In [32]:
df['department_clean'] = df['department'].str.strip(' ')
df

,employee_id,full_name,department,job_title,hire_date,salary,bonus,years_experience,email,phone,city,state,performance_rating,status,remote_work,manager_name,last_review_date,department_clean
0,1034,Grace Ferreira,IT,Software Engineer,11/08/2021,87609,NaN,10,grace.ferreira@retailco.com,779 898 3950,Nashville,TN,2.0,Active,No,Sophie Khan,4/15/2023,IT
1,1056,Sonia Chen,Operations,Logistics Coordinator,01/21/2019,58508,NaN,4,sonia.chen@retailco.com,(736) 569-2108,Nashville,TN,5.0,Active,No,Hugo Muller,12/01/2024,Operations
2,1156,Wei Khan,Finance,Finance Manager,02/08/2019,64418,NaN,1,wei.khan@retailco.com,NaN,Nashville,TN,2.0,Inactive,No,Noah Kowalski,2/23/2024,Finance
3,1081,Noah Brown,Operations,Operations Manager,07/01/2016,58431,1560.0,2,noah.brown@retailco.com,(392) 979-4555,Columbus,OH,5.0,Active,Hybrid,NaN,12/25/2023,Operations
4,1072,Wei Wilson,OPERATIONS,Operations Manager,08/06/2018,63197,NaN,6,wei.wilson@retailco.com,747-956-1611,Chicago,IL,1.0,On Leave,Hybrid,Ahmed Wilson,01/01/2024,OPERATIONS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,1110,Ravi Lin,HR,Recruiter,02/08/2018,54530,1260.0,7,ravi.lin@retailco.com,(977) 873-7164,Portland,OR,1.0,Active,Hybrid,Jack Bello,01/08/2023,HR
220,1196,Ivy Fischer,CUSTOMER SUPPORT,Customer Success Manager,15/06/2018,65535,7189.0,13,ivy.fischer@retailco.com,292 939 9202,Nashville,TN,4.0,Active,No,Hana Khan,12/07/2025,CUSTOMER SUPPORT
221,1138,Sophie Brown,HR,HR Business Partner,2/14/2014,50969,NaN,2,sophie.brown@retailco.com,906 689 7909,Chicago,IL,4.0,On Leave,No,Sophie Lee,15/11/2025,HR
222,1036,Mike Popescu,Customer Support,Technical Support Agent,01/19/2019,74124,3700.0,15,mike.popescu@retailco.com,894.973.3240,Dallas,TX,2.0,Active,Yes,Grace Yamamoto,05/11/2023,Customer Support
223,1027,Sarah Wilson,MARKETING,SEO Specialist,03/03/2016,59256,NaN,7,sarah.wilson@retailco.com,840.803.4241,Atlanta,GA,1.0,Active,No,Nora Lee,10/24/2024,MARKETING

**Question5.** 
- (a) Using full_name column create first_name and last_name columns.
- (b) Use email column to extract just the username (the part before the @ is the username) into a new
column.

In [34]:
name_split = df['full_name'].str.split(n = 1, expand=True)
name_split

          0          1
0     Grace   Ferreira
1     Sonia       Chen
2       Wei       Khan
3      Noah      Brown
4       Wei     Wilson
..      ...        ...
219    Ravi        Lin
220     Ivy  Fischer
221  Sophie      Brown
222    Mike    Popescu
223   Sarah     Wilson

[224 rows x 2 columns]

In [37]:
df['first_name'] = name_split[0]
df

,employee_id,full_name,department,job_title,hire_date,salary,bonus,years_experience,email,phone,city,state,performance_rating,status,remote_work,manager_name,last_review_date,department_clean,first_name
0,1034,Grace Ferreira,IT,Software Engineer,11/08/2021,87609,NaN,10,grace.ferreira@retailco.com,779 898 3950,Nashville,TN,2.0,Active,No,Sophie Khan,4/15/2023,IT,Grace
1,1056,Sonia Chen,Operations,Logistics Coordinator,01/21/2019,58508,NaN,4,sonia.chen@retailco.com,(736) 569-2108,Nashville,TN,5.0,Active,No,Hugo Muller,12/01/2024,Operations,Sonia
2,1156,Wei Khan,Finance,Finance Manager,02/08/2019,64418,NaN,1,wei.khan@retailco.com,NaN,Nashville,TN,2.0,Inactive,No,Noah Kowalski,2/23/2024,Finance,Wei
3,1081,Noah Brown,Operations,Operations Manager,07/01/2016,58431,1560.0,2,noah.brown@retailco.com,(392) 979-4555,Columbus,OH,5.0,Active,Hybrid,NaN,12/25/2023,Operations,Noah
4,1072,Wei Wilson,OPERATIONS,Operations Manager,08/06/2018,63197,NaN,6,wei.wilson@retailco.com,747-956-1611,Chicago,IL,1.0,On Leave,Hybrid,Ahmed Wilson,01/01/2024,OPERATIONS,Wei
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,1110,Ravi Lin,HR,Recruiter,02/08/2018,54530,1260.0,7,ravi.lin@retailco.com,(977) 873-7164,Portland,OR,1.0,Active,Hybrid,Jack Bello,01/08/2023,HR,Ravi
220,1196,Ivy Fischer,CUSTOMER SUPPORT,Customer Success Manager,15/06/2018,65535,7189.0,13,ivy.fischer@retailco.com,292 939 9202,Nashville,TN,4.0,Active,No,Hana Khan,12/07/2025,CUSTOMER SUPPORT,Ivy
221,1138,Sophie Brown,HR,HR Business Partner,2/14/2014,50969,NaN,2,sophie.brown@retailco.com,906 689 7909,Chicago,IL,4.0,On Leave,No,Sophie Lee,15/11/2025,HR,Sophie
222,1036,Mike Popescu,Customer Support,Technical Support Agent,01/19/2019,74124,3700.0,15,mike.popescu@retailco.com,894.973.3240,Dallas,TX,2.0,Active,Yes,Grace Yamamoto,05/11/2023,Customer Support,Mike
223,1027,Sarah Wilson,MARKETING,SEO Specialist,03/03/2016,59256,NaN,7,sarah.wilson@retailco.com,840.803.4241,Atlanta,GA,1.0,Active,No,Nora Lee,10/24/2024,MARKETING,Sarah

In [38]:
df['last_name'] = name_split[1]
df

,employee_id,full_name,department,job_title,hire_date,salary,bonus,years_experience,email,phone,city,state,performance_rating,status,remote_work,manager_name,last_review_date,department_clean,first_name,last_name
0,1034,Grace Ferreira,IT,Software Engineer,11/08/2021,87609,NaN,10,grace.ferreira@retailco.com,779 898 3950,Nashville,TN,2.0,Active,No,Sophie Khan,4/15/2023,IT,Grace,Ferreira
1,1056,Sonia Chen,Operations,Logistics Coordinator,01/21/2019,58508,NaN,4,sonia.chen@retailco.com,(736) 569-2108,Nashville,TN,5.0,Active,No,Hugo Muller,12/01/2024,Operations,Sonia,Chen
2,1156,Wei Khan,Finance,Finance Manager,02/08/2019,64418,NaN,1,wei.khan@retailco.com,NaN,Nashville,TN,2.0,Inactive,No,Noah Kowalski,2/23/2024,Finance,Wei,Khan
3,1081,Noah Brown,Operations,Operations Manager,07/01/2016,58431,1560.0,2,noah.brown@retailco.com,(392) 979-4555,Columbus,OH,5.0,Active,Hybrid,NaN,12/25/2023,Operations,Noah,Brown
4,1072,Wei Wilson,OPERATIONS,Operations Manager,08/06/2018,63197,NaN,6,wei.wilson@retailco.com,747-956-1611,Chicago,IL,1.0,On Leave,Hybrid,Ahmed Wilson,01/01/2024,OPERATIONS,Wei,Wilson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,1110,Ravi Lin,HR,Recruiter,02/08/2018,54530,1260.0,7,ravi.lin@retailco.com,(977) 873-7164,Portland,OR,1.0,Active,Hybrid,Jack Bello,01/08/2023,HR,Ravi,Lin
220,1196,Ivy Fischer,CUSTOMER SUPPORT,Customer Success Manager,15/06/2018,65535,7189.0,13,ivy.fischer@retailco.com,292 939 9202,Nashville,TN,4.0,Active,No,Hana Khan,12/07/2025,CUSTOMER SUPPORT,Ivy,Fischer
221,1138,Sophie Brown,HR,HR Business Partner,2/14/2014,50969,NaN,2,sophie.brown@retailco.com,906 689 7909,Chicago,IL,4.0,On Leave,No,Sophie Lee,15/11/2025,HR,Sophie,Brown
222,1036,Mike Popescu,Customer Support,Technical Support Agent,01/19/2019,74124,3700.0,15,mike.popescu@retailco.com,894.973.3240,Dallas,TX,2.0,Active,Yes,Grace Yamamoto,05/11/2023,Customer Support,Mike,Popescu
223,1027,Sarah Wilson,MARKETING,SEO Specialist,03/03/2016,59256,NaN,7,sarah.wilson@retailco.com,840.803.4241,Atlanta,GA,1.0,Active,No,Nora Lee,10/24/2024,MARKETING,Sarah,Wilson

In [44]:
# Here split divides email into 2 columns. and 'str[0]' picks up first part
df['email'].str.split('@').str[0]

0      grace.ferreira
1          sonia.chen
2            wei.khan
3          noah.brown
4          wei.wilson
            ...
219          ravi.lin
220       ivy.fischer
221      sophie.brown
222      mike.popescu
223      sarah.wilson
Name: email, Length: 224, dtype: object

**Question6.** 
- Using department_clean, group the data and find the average salary and the number of employees in each department. Which department has the highest average salary?

In [60]:
department_summary = df.groupby('department_clean').agg(
    avg_salary = ('salary', 'mean'),
    emp_count = ('salary', 'count')
).round(2)
department_summary

                  avg_salary  emp_count
department_clean
CUSTOMER SUPPORT    53421.62          8
Customer Support    56935.31         16
FINANCE             67748.60          5
Finance             72734.85         13
HR                  61375.38         26
IT                  80812.16         32
MARKETING           60506.88          8
Marketing           57260.00         13
OPERATIONS          67207.25          8
Operations          64727.62         26
SALES               60859.33          6
Sales               60689.27         15
customer support    53504.00          3
finance             77531.27         11
hr                  65633.14          7
it                  83740.40          5
marketing           61273.00          6
operations          66173.33          6
sales               64200.20         10

In [61]:
department_summary['avg_salary'].idxmax()

'it'

- it Department has the highest average salary