In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect("data.db")

In [3]:
q = """SELECT * FROM sqlite_master """

pd.read_sql_query(q, conn)

,type,name,tbl_name,rootpage,sql
0,table,departments,departments,2,"CREATE TABLE ""departments"" (\n""department_id"" ..."
1,table,employees,employees,3,"CREATE TABLE ""employees"" (\n""employee_id"" INTE..."
2,table,customers,customers,6,"CREATE TABLE ""customers"" (\n""customer_id"" INTE..."
3,table,products,products,10,"CREATE TABLE ""products"" (\n""product_id"" INTEGE..."
4,table,orders,orders,11,"CREATE TABLE ""orders"" (\n""order_id"" INTEGER,\n..."
5,table,order_items,order_items,19,"CREATE TABLE ""order_items"" (\n""order_item_id"" ..."
6,table,order_insert_log,order_insert_log,30,CREATE TABLE order_insert_log (\n log_id IN...
7,table,sqlite_sequence,sqlite_sequence,31,"CREATE TABLE sqlite_sequence(name,seq)"
8,trigger,trg_order_insert,orders,0,CREATE TRIGGER trg_order_insert\nAFTER INSERT ...

In [4]:
tables =["departments",
        "employees",
         "customers",
         "products",
        "orders",
        "order_items",
        "order_insert_log",
        "sqlite_sequence",
        "trg_order_insert"
]

for table in tables:
    print(f"\n{table}")

    q = f"PRAGMA table_info({table})"
    display(pd.read_sql_query(q, conn))

departments

   cid             name     type  notnull dflt_value  pk
0    0    department_id  INTEGER        0       None   0
1    1  department_name     TEXT        0       None   0
2    2         location     TEXT        0       None   0

employees

   cid               name       type  notnull dflt_value  pk
0    0        employee_id    INTEGER        0       None   0
1    1          full_name       TEXT        0       None   0
2    2      department_id    INTEGER        0       None   0
3    3          job_title       TEXT        0       None   0
4    4          hire_date  TIMESTAMP        0       None   0
5    5             salary    INTEGER        0       None   0
6    6  performance_score    INTEGER        0       None   0
7    7  employment_status       TEXT        0       None   0

customers

   cid              name       type  notnull dflt_value  pk
0    0       customer_id    INTEGER        0       None   0
1    1     customer_name       TEXT        0       None   0
2    2              city       TEXT        0       None   0
3    3       signup_date  TIMESTAMP        0       None   0
4    4  customer_segment       TEXT        0       None   0

products

   cid          name     type  notnull dflt_value  pk
0    0    product_id  INTEGER        0       None   0
1    1  product_name     TEXT        0       None   0
2    2      category     TEXT        0       None   0
3    3    unit_price  INTEGER        0       None   0

orders

   cid            name       type  notnull dflt_value  pk
0    0        order_id    INTEGER        0       None   0
1    1     customer_id    INTEGER        0       None   0
2    2     employee_id    INTEGER        0       None   0
3    3      order_date  TIMESTAMP        0       None   0
4    4          status       TEXT        0       None   0
5    5  payment_method       TEXT        0       None   0

order_items

   cid           name     type  notnull dflt_value  pk
0    0  order_item_id  INTEGER        0       None   0
1    1       order_id  INTEGER        0       None   0
2    2     product_id  INTEGER        0       None   0
3    3       quantity  INTEGER        0       None   0
4    4     list_price  INTEGER        0       None   0
5    5  discount_rate     REAL        0       None   0
6    6     unit_price  INTEGER        0       None   0

order_insert_log

   cid       name     type  notnull dflt_value  pk
0    0     log_id  INTEGER        0       None   1
1    1   order_id  INTEGER        0       None   0
2    2  logged_at     TEXT        0       None   0

sqlite_sequence

   cid  name type  notnull dflt_value  pk
0    0  name             0       None   0
1    1   seq             0       None   0

trg_order_insert

Empty DataFrame
Columns: [cid, name, type, notnull, dflt_value, pk]
Index: []

In [5]:
q = """
    SELECT DISTINCT payment_method
    FROM orders"""

pd.read_sql_query(q, conn)

  payment_method
0         Cheque
1  Bank Transfer
2    Credit Card
3           Cash
4         Online

In [6]:
q = """
    SELECT customer_id, customer_name, city
    FROM customers
    WHERE city IN ('Karachi','Lahore', 'Islamabad')"""

pd.read_sql_query(q, conn)

    customer_id            customer_name       city
0          2001   Metro Distributors 001     Lahore
1          2003    Metro Enterprises 003  Islamabad
2          2004  United Technologies 004  Islamabad
3          2005           Metro Mart 005     Lahore
4          2006        Beta Services 006     Lahore
..          ...                      ...        ...
94         2146        Beta Services 146     Lahore
95         2147    Global Industries 147    Karachi
96         2148  United Technologies 148    Karachi
97         2149           Elite Mart 149    Karachi
98         2150      Horizon Traders 150    Karachi

[99 rows x 3 columns]

In [7]:
# here we used sub-qeuires instead of join because both tables are not connected and to avoid JOIN

q = """
    SELECT order_id, customer_id, order_date, status
    FROM orders
    WHERE customer_id IN (SELECT customer_id
                            FROM customers
                            WHERE city = "Karachi")"""

pd.read_sql_query(q, conn)

     order_id  customer_id           order_date     status
0        4006         2049  2024-11-12 00:00:00  Completed
1        4007         2134  2026-02-12 00:00:00  Completed
2        4008         2114  2024-09-20 00:00:00  Completed
3        4010         2127  2025-04-03 00:00:00  Completed
4        4011         2134  2024-01-22 00:00:00  Completed
..        ...          ...                  ...        ...
169      4487         2135  2024-03-25 00:00:00    Pending
170      4489         2076  2025-05-25 00:00:00  Completed
171      4490         2141  2026-04-05 00:00:00  Completed
172      4493         2054  2026-08-25 00:00:00  Completed
173      4495         2009  2025-10-12 00:00:00  Completed

[174 rows x 4 columns]

In [8]:
q = """
    SELECT employee_id, full_name, job_title, salary
    FROM employees
    WHERE salary BETWEEN 80000 AND 100000"""

pd.read_sql_query(q, conn)

    employee_id        full_name                     job_title  salary
0          1001        Iqra Butt                 Brand Manager   89000
1          1002    Laiba Hussain                    HR Manager  100000
2          1005      Waqar Javed            Operations Analyst   83000
3          1007        Sara Khan            Operations Analyst   94000
4          1009     Mahnoor Butt            Operations Manager   84000
5          1014        Sana Shah                  HR Executive   96000
6          1016       Usman Noor  Digital Marketing Specialist   86000
7          1020        Iqra Butt             Financial Analyst   88000
8          1021     Danish Ahmed               Finance Manager   93000
9          1025       Fatima Ali                 SQL Developer   81000
10         1031  Danish Siddiqui                 Sales Analyst   95000
11         1036      Hassan Raza        Recruitment Specialist   92000
12         1039     Sara Hussain            Operations Analyst   91000
13         1045          Ali Ali                 Data Engineer   98000
14         1046     Danish Ahmed                  Area Manager   91000
15         1054       Danish Ali             Senior Accountant   84000
16         1056        Iqra Shah              Accounts Officer   87000
17         1058        Sara Khan           Marketing Executive   91000
18         1059        Hina Butt                  Data Analyst   83000
19         1064        Sana Butt            Operations Officer   97000
20         1067       Sara Javed  Digital Marketing Specialist   86000
21         1073       Zain Iqbal             Marketing Manager   84000
22         1077    Mahnoor Javed            Operations Officer   97000
23         1086  Mahnoor Qureshi             Financial Analyst   87000
24         1087        Sara Khan                 Sales Analyst   82000
25         1095       Arham Raza           Procurement Officer   96000
26         1097       Waqar Butt           Marketing Executive   83000
27         1098      Raza Farooq                  Area Manager   81000

In [9]:
# LIKE is similar to REGULAR EXPRESSION
q = """
    SELECT employee_id, full_name, job_title 
    FROM employees
    WHERE full_name LIKE "%A"
    """

pd.read_sql_query(q, conn)

   employee_id     full_name               job_title
0         1026      Ali Raza      Operations Analyst
1         1036   Hassan Raza  Recruitment Specialist
2         1047    Bilal Raza     Marketing Executive
3         1075  Mahnoor Raza           Sales Analyst
4         1095    Arham Raza     Procurement Officer

In [10]:
q = """
    SELECT product_id, product_name, unit_price 
    FROM products
    WHERE product_name LIKE "%Laptop%"
    """

pd.read_sql_query(q, conn)

   product_id         product_name  unit_price
0        3001  Business Laptop Pro      185000
1        3002  Business Laptop Air      145000
2        3003   Workstation Laptop      265000

In [11]:
# UPPER, LOWER, LENGTH
q = """
    SELECT customer_id, customer_name,
    UPPER(customer_name),
    LOWER(customer_name),
    LENGTH(customer_name)
    FROM customers    
    """

pd.read_sql_query(q, conn)

,customer_id,customer_name,UPPER(customer_name),LOWER(customer_name),LENGTH(customer_name)
0,2001,Metro Distributors 001,METRO DISTRIBUTORS 001,metro distributors 001,22
1,2002,Prime Mart 002,PRIME MART 002,prime mart 002,14
2,2003,Metro Enterprises 003,METRO ENTERPRISES 003,metro enterprises 003,21
3,2004,United Technologies 004,UNITED TECHNOLOGIES 004,united technologies 004,23
4,2005,Metro Mart 005,METRO MART 005,metro mart 005,14
...,...,...,...,...,...
145,2146,Beta Services 146,BETA SERVICES 146,beta services 146,17
146,2147,Global Industries 147,GLOBAL INDUSTRIES 147,global industries 147,21
147,2148,United Technologies 148,UNITED TECHNOLOGIES 148,united technologies 148,23
148,2149,Elite Mart 149,ELITE MART 149,elite mart 149,14
149,2150,Horizon Traders 150,HORIZON TRADERS 150,horizon traders 150,19

In [12]:
q = """
    SELECT employee_id, full_name, SUBSTR(full_name, 1, 5) AS first_five_char
    
    FROM employees    
    """

pd.read_sql_query(q, conn)

    employee_id      full_name first_five_char
0          1001      Iqra Butt           Iqra
1          1002  Laiba Hussain           Laiba
2          1003    Sana Farooq           Sana
3          1004  Zain Siddiqui           Zain
4          1005    Waqar Javed           Waqar
..          ...            ...             ...
95         1096    Kashif Noor           Kashi
96         1097     Waqar Butt           Waqar
97         1098    Raza Farooq           Raza
98         1099     Hassan Ali           Hassa
99         1100   Fatima Malik           Fatim

[100 rows x 3 columns]

In [13]:
q = """SELECT employee_id, full_name,
        SUBSTR (
        full_name, INSTR(full_name,' ') + 1 
        )AS sur_name
        FROM employees """

pd.read_sql_query(q,conn)

    employee_id      full_name  sur_name
0          1001      Iqra Butt      Butt
1          1002  Laiba Hussain   Hussain
2          1003    Sana Farooq    Farooq
3          1004  Zain Siddiqui  Siddiqui
4          1005    Waqar Javed     Javed
..          ...            ...       ...
95         1096    Kashif Noor      Noor
96         1097     Waqar Butt      Butt
97         1098    Raza Farooq    Farooq
98         1099     Hassan Ali       Ali
99         1100   Fatima Malik     Malik

[100 rows x 3 columns]

In [14]:
q = """
    SELECT product_name, REPLACE(product_name, "Laptop", "Notebook") as revise_name 
    FROM products
    WHERE product_name LIKE "%Laptop%"
    """

pd.read_sql_query(q, conn)

          product_name            revise_name
0  Business Laptop Pro  Business Notebook Pro
1  Business Laptop Air  Business Notebook Air
2   Workstation Laptop   Workstation Notebook

####  STRFTIME FORMAT

In [15]:
q = """
    SELECT order_id, order_date, 
    STRFTIME ("%Y", order_date) AS order_year,
    STRFTIME ("%m", order_date) AS order_month
    FROM orders
    LIMIT 10
    """

pd.read_sql_query(q, conn)

   order_id           order_date order_year order_month
0      4001  2024-03-26 00:00:00       2024          03
1      4002  2024-08-12 00:00:00       2024          08
2      4003  2026-07-06 00:00:00       2026          07
3      4004  2025-11-16 00:00:00       2025          11
4      4005  2024-04-15 00:00:00       2024          04
5      4006  2024-11-12 00:00:00       2024          11
6      4007  2026-02-12 00:00:00       2026          02
7      4008  2024-09-20 00:00:00       2024          09
8      4009  2024-11-13 00:00:00       2024          11
9      4010  2025-04-03 00:00:00       2025          04

In [16]:
# IF we want to calculate days duration since order
q = """
    SELECT order_id, order_date, 
    CAST(
        JULIANDAY('now') - JULIANDAY(order_date)
    AS INTEGER) AS days_since_order
    FROM orders
    LIMIT 10
    """

pd.read_sql_query(q, conn)

   order_id           order_date  days_since_order
0      4001  2024-03-26 00:00:00               947
1      4002  2024-08-12 00:00:00               808
2      4003  2026-07-06 00:00:00               115
3      4004  2025-11-16 00:00:00               347
4      4005  2024-04-15 00:00:00               927
5      4006  2024-11-12 00:00:00               716
6      4007  2026-02-12 00:00:00               259
7      4008  2024-09-20 00:00:00               769
8      4009  2024-11-13 00:00:00               715
9      4010  2025-04-03 00:00:00               574

In [17]:
# IF we want to calculate days duration since order
q = """
    SELECT STRFTIME("%Y- %m", order_date) AS order_month,
    COUNT(*) AS total_order,
    SUM(
    CASE WHEN status = "Completed" THEN 1 ELSE 0 END) AS completed_orders,
    SUM(
    CASE WHEN status = "Cancelled" THEN 1 ELSE 0 END) AS cancelled_orders
    FROM orders
    GROUP BY STRFTIME("%Y- %m", order_date)
    ORDER BY order_month
    """

pd.read_sql_query(q, conn)

   order_month  total_order  completed_orders  cancelled_orders
0     2024- 01           15                 9                 1
1     2024- 02           10                 6                 2
2     2024- 03           13                10                 0
3     2024- 04           16                 7                 2
4     2024- 05           15                 6                 2
5     2024- 06           12                 8                 1
6     2024- 07           13                 9                 0
7     2024- 08           12                 8                 0
8     2024- 09           13                 7                 3
9     2024- 10           21                13                 1
10    2024- 11           11                 4                 3
11    2024- 12           12                 9                 1
12    2025- 01           17                12                 2
13    2025- 02           19                11                 6
14    2025- 03           15                10                 1
15    2025- 04           13                 7                 4
16    2025- 05           14                 7                 4
17    2025- 06           15                10                 1
18    2025- 07           23                10                 7
19    2025- 08           16                 7                 1
20    2025- 09           19                12                 4
21    2025- 10           12                 9                 0
22    2025- 11           18                12                 1
23    2025- 12           11                 7                 0
24    2026- 01            6                 2                 1
25    2026- 02           18                11                 4
26    2026- 03           16                12                 1
27    2026- 04           22                11                 4
28    2026- 05           12                 5                 4
29    2026- 06           14                10                 3
30    2026- 07           19                10                 3
31    2026- 08           25                10                 4
32    2026- 09           13                 6                 2

#### CT's IN SQL

In [18]:
q = """ 
    SELECT o.order_id, o.customer_id, o.status,
    SUM(oi.quantity * oi.unit_price) AS order_value
    FROM orders o
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY o.order_id, customer_id, status 
    
    """

pd.read_sql_query(q, conn)

     order_id  customer_id     status  order_value
0        4001         2080  Completed       194880
1        4002         2097  Completed       273000
2        4003         2077   Returned       365200
3        4004         2103  Completed        68400
4        4005         2143   Returned       133010
..        ...          ...        ...          ...
495      4496         2017  Completed       265000
496      4497         2123  Cancelled       446500
497      4498         2065  Completed       310000
498      4499         2081   Returned       934200
499      4500         2001   Returned       111200

[500 rows x 4 columns]

In [19]:
q = """
    WITH order_totals AS (
    SELECT o.order_id, o.customer_id, o.status,
    SUM(oi.quantity * oi.unit_price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id, customer_id, status),
    
    customer_spending AS (
    SELECT customer_id, SUM(order_value) AS total_spend 
    FROM order_totals
    WHERE status = "Completed"
    GROUP BY customer_id )

    SELECT c.customer_id, c.customer_name, c.city,
    ROUND(cs.total_spend, 2) AS total_spend
    FROM customer_spending AS cs
    JOIN customers AS c

    ON c.customer_id = cs.customer_id
    WHERE cs.total_spend > 200000
    ORDER BY cs.total_spend DESC
    """

pd.read_sql_query(q, conn)

     customer_id            customer_name        city  total_spend
0           2086      Vertex Services 086  Faisalabad    4497400.0
1           2024  Global Distributors 024  Rawalpindi    2536100.0
2           2017       Royal Services 017  Faisalabad    2406120.0
3           2113       Horizon Stores 113   Islamabad    2361860.0
4           2146        Beta Services 146      Lahore    2326270.0
..           ...                      ...         ...          ...
110         2067   Smart Distributors 067  Faisalabad     236200.0
111         2131       Zeta Solutions 131    Peshawar     234795.0
112         2045  Horizon Enterprises 045      Lahore     234650.0
113         2115     Horizon Services 115    Peshawar     210000.0
114         2020        National Mart 020     Karachi     205200.0

[115 rows x 4 columns]

In [20]:
q = """ SELECT city as location
        FROM customers
        
        UNION
        
        SELECT location
        FROM departments"""

pd.read_sql_query(q, conn)

     location
0  Faisalabad
1   Islamabad
2     Karachi
3      Lahore
4      Multan
5    Peshawar
6  Rawalpindi

In [21]:
q = """ SELECT city as location
        FROM customers
        
        UNION ALL
        
        SELECT location
        FROM departments"""

pd.read_sql_query(q, conn)

       location
0        Lahore
1        Multan
2     Islamabad
3     Islamabad
4        Lahore
..          ...
153   Islamabad
154     Karachi
155      Lahore
156   Islamabad
157  Rawalpindi

[158 rows x 1 columns]