## Grand Test
Task 2
1. Using Pandas. Use data_grand_test.csv
- Display first 5 rows
- Display last 5 rows
- Display data types
- Display total rows & columns
- Display frequency of Departments
- Display frequency of Status

2. Clean the following columns:
- Name:
    - Remove leading/trailing spaces
- City:
    - Remove spaces
    - Convert to Upper Case (Like  KARACHI)
- Status:
    - Using your knowledge of cleaning, clean the Status column. Show each step.
- Skills
The Skills column contains values like
     Python, Excel
     Python ,SQL
     Excel,Power BI
    Tasks:
    - Remove unnecessary spaces using
    - Split the column in Skill1,Skill2,...

Finally print the cleaned dataframe.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../Test Material/data_grand_test.csv")
df

,ID,Name,Department,City,Age,Salary,Phone,Status,Skills,Performance
0,1,Bilal,HR,Islamabad,41,51594,0321-5781453,Active,"Python, Excel",82
1,2,Ali,Finance,Karachi,44,176975,0308-5916045,Active,"Excel,Power BI",91
2,3,Hina,Sales,Peshawar,38,171526,0305-9439388,inactive,"Python ,SQL",55
3,4,Ahmed,Finance,Quetta,38,81409,0329-7879972,Active,"Python, Excel",55
4,5,Hina,IT,Peshawar,37,129637,0317-4639011,inactive,"Python, Excel",91
...,...,...,...,...,...,...,...,...,...,...
995,996,Ali,CS,Peshawar,21,170844,0339-2414665,Inactive,"Java, Python",78
996,997,Ahmed,Finance,Lahore,42,90919,0300-2999562,Active,"SQL,Python",82
997,998,Hina,CS,Karachi,33,153119,0305-6756228,ACTIVE,"Java, Python",91
998,999,Ahmed,HR,Lahore,23,164489,0339-6428600,Active,"Python ,SQL",78
999,1000,Bilal,Finance,Islamabad,39,160165,0303-1245347,Active,"SQL,Python",78

In [4]:
df.head(5)

,ID,Name,Department,City,Age,Salary,Phone,Status,Skills,Performance
0,1,Bilal,HR,Islamabad,41,51594,0321-5781453,Active,"Python, Excel",82
1,2,Ali,Finance,Karachi,44,176975,0308-5916045,Active,"Excel,Power BI",91
2,3,Hina,Sales,Peshawar,38,171526,0305-9439388,inactive,"Python ,SQL",55
3,4,Ahmed,Finance,Quetta,38,81409,0329-7879972,Active,"Python, Excel",55
4,5,Hina,IT,Peshawar,37,129637,0317-4639011,inactive,"Python, Excel",91

In [5]:
df.tail(5)

,ID,Name,Department,City,Age,Salary,Phone,Status,Skills,Performance
995,996,Ali,CS,Peshawar,21,170844,0339-2414665,Inactive,"Java, Python",78
996,997,Ahmed,Finance,Lahore,42,90919,0300-2999562,Active,"SQL,Python",82
997,998,Hina,CS,Karachi,33,153119,0305-6756228,ACTIVE,"Java, Python",91
998,999,Ahmed,HR,Lahore,23,164489,0339-6428600,Active,"Python ,SQL",78
999,1000,Bilal,Finance,Islamabad,39,160165,0303-1245347,Active,"SQL,Python",78

In [6]:
df.dtypes

ID              int64
Name           object
Department     object
City           object
Age             int64
Salary          int64
Phone          object
Status         object
Skills         object
Performance     int64
dtype: object

In [7]:
df.shape

(1000, 10)

In [8]:
df["Department"].value_counts()

Department
Finance    229
HR         215
IT         202
CS         179
Sales      175
Name: count, dtype: int64

In [9]:
df["Status"].value_counts()

Status
 inactive    210
ACTIVE       204
Active       203
Active       195
Inactive     188
Name: count, dtype: int64

In [10]:
df["Name"] = df["Name"].str.strip(' ')
df

,ID,Name,Department,City,Age,Salary,Phone,Status,Skills,Performance
0,1,Bilal,HR,Islamabad,41,51594,0321-5781453,Active,"Python, Excel",82
1,2,Ali,Finance,Karachi,44,176975,0308-5916045,Active,"Excel,Power BI",91
2,3,Hina,Sales,Peshawar,38,171526,0305-9439388,inactive,"Python ,SQL",55
3,4,Ahmed,Finance,Quetta,38,81409,0329-7879972,Active,"Python, Excel",55
4,5,Hina,IT,Peshawar,37,129637,0317-4639011,inactive,"Python, Excel",91
...,...,...,...,...,...,...,...,...,...,...
995,996,Ali,CS,Peshawar,21,170844,0339-2414665,Inactive,"Java, Python",78
996,997,Ahmed,Finance,Lahore,42,90919,0300-2999562,Active,"SQL,Python",82
997,998,Hina,CS,Karachi,33,153119,0305-6756228,ACTIVE,"Java, Python",91
998,999,Ahmed,HR,Lahore,23,164489,0339-6428600,Active,"Python ,SQL",78
999,1000,Bilal,Finance,Islamabad,39,160165,0303-1245347,Active,"SQL,Python",78

In [11]:
df["City"] = df["City"].str.strip(" ")
df

,ID,Name,Department,City,Age,Salary,Phone,Status,Skills,Performance
0,1,Bilal,HR,Islamabad,41,51594,0321-5781453,Active,"Python, Excel",82
1,2,Ali,Finance,Karachi,44,176975,0308-5916045,Active,"Excel,Power BI",91
2,3,Hina,Sales,Peshawar,38,171526,0305-9439388,inactive,"Python ,SQL",55
3,4,Ahmed,Finance,Quetta,38,81409,0329-7879972,Active,"Python, Excel",55
4,5,Hina,IT,Peshawar,37,129637,0317-4639011,inactive,"Python, Excel",91
...,...,...,...,...,...,...,...,...,...,...
995,996,Ali,CS,Peshawar,21,170844,0339-2414665,Inactive,"Java, Python",78
996,997,Ahmed,Finance,Lahore,42,90919,0300-2999562,Active,"SQL,Python",82
997,998,Hina,CS,Karachi,33,153119,0305-6756228,ACTIVE,"Java, Python",91
998,999,Ahmed,HR,Lahore,23,164489,0339-6428600,Active,"Python ,SQL",78
999,1000,Bilal,Finance,Islamabad,39,160165,0303-1245347,Active,"SQL,Python",78

In [12]:
df["City"] = df["City"].str.upper()
df["City"]

0      ISLAMABAD
1        KARACHI
2       PESHAWAR
3         QUETTA
4       PESHAWAR
         ...
995     PESHAWAR
996       LAHORE
997      KARACHI
998       LAHORE
999    ISLAMABAD
Name: City, Length: 1000, dtype: object

In [13]:
df["Status"].value_counts()

Status
 inactive    210
ACTIVE       204
Active       203
Active       195
Inactive     188
Name: count, dtype: int64

In [14]:
df["Status"].isnull().sum()

np.int64(0)

In [15]:
df["Status"].unique()

array(['Active', ' inactive', 'Active ', 'ACTIVE', 'Inactive'],
      dtype=object)

In [16]:
df["Status"] = df["Status"].str.strip()
df["Status"]

0        Active
1        Active
2      inactive
3        Active
4      inactive
         ...
995    Inactive
996      Active
997      ACTIVE
998      Active
999      Active
Name: Status, Length: 1000, dtype: object

In [17]:
df["Status"] = df["Status"].str.lower()
df["Status"].value_counts()

Status
active      602
inactive    398
Name: count, dtype: int64

In [18]:
df["Skills"].value_counts()

Skills
Java, Python        213
 Excel,Power BI     205
Python ,SQL         196
Python, Excel       195
SQL,Python          191
Name: count, dtype: int64

In [19]:
# df["Skills"] = df["Skills"].str.replace(" ", "", regex=False)
# df["Skills"].value_counts()

In [20]:
df["Skills"] = df["Skills"].str.strip()
df["Skills"]

0       Python, Excel
1      Excel,Power BI
2         Python ,SQL
3       Python, Excel
4       Python, Excel
            ...
995      Java, Python
996        SQL,Python
997      Java, Python
998       Python ,SQL
999        SQL,Python
Name: Skills, Length: 1000, dtype: object

In [21]:
df["Skills"] = df["Skills"].str.replace(r'\s*,\s*',',',regex=True)
df["Skills"]

0        Python,Excel
1      Excel,Power BI
2          Python,SQL
3        Python,Excel
4        Python,Excel
            ...
995       Java,Python
996        SQL,Python
997       Java,Python
998        Python,SQL
999        SQL,Python
Name: Skills, Length: 1000, dtype: object

In [22]:
df[['Skills1','Skill2']] = df["Skills"].str.split(',', expand=True)

In [23]:
df

,ID,Name,Department,City,Age,Salary,Phone,Status,Skills,Performance,Skills1,Skill2
0,1,Bilal,HR,ISLAMABAD,41,51594,0321-5781453,active,"Python,Excel",82,Python,Excel
1,2,Ali,Finance,KARACHI,44,176975,0308-5916045,active,"Excel,Power BI",91,Excel,Power BI
2,3,Hina,Sales,PESHAWAR,38,171526,0305-9439388,inactive,"Python,SQL",55,Python,SQL
3,4,Ahmed,Finance,QUETTA,38,81409,0329-7879972,active,"Python,Excel",55,Python,Excel
4,5,Hina,IT,PESHAWAR,37,129637,0317-4639011,inactive,"Python,Excel",91,Python,Excel
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Ali,CS,PESHAWAR,21,170844,0339-2414665,inactive,"Java,Python",78,Java,Python
996,997,Ahmed,Finance,LAHORE,42,90919,0300-2999562,active,"SQL,Python",82,SQL,Python
997,998,Hina,CS,KARACHI,33,153119,0305-6756228,active,"Java,Python",91,Java,Python
998,999,Ahmed,HR,LAHORE,23,164489,0339-6428600,active,"Python,SQL",78,Python,SQL
999,1000,Bilal,Finance,ISLAMABAD,39,160165,0303-1245347,active,"SQL,Python",78,SQL,Python

## Task 3:

Some values in Performance are strings.
- Convert Performance into integer.
- Display employees having Performance greater than 80.
- Display employees from Karachi.
- Display employees from IT department having Performance less than 75.
- Display average salary.

In [122]:
df["Performance"] = df["Performance"].astype('int')
df.sample().dtypes

ID              int64
Name           object
Department     object
City           object
Age             int64
Salary          int64
Phone          object
Status         object
Skills         object
Performance     int64
Skills1        object
Skill2         object
dtype: object

In [125]:
df[df["Performance"] > 80]

,ID,Name,Department,City,Age,Salary,Phone,Status,Skills,Performance,Skills1,Skill2
0,1,Bilal,HR,ISLAMABAD,41,51594,0321-5781453,active,"Python,Excel",82,Python,Excel
1,2,Ali,Finance,KARACHI,44,176975,0308-5916045,active,"Excel,Power BI",91,Excel,Power BI
4,5,Hina,IT,PESHAWAR,37,129637,0317-4639011,inactive,"Python,Excel",91,Python,Excel
14,15,Zain,Sales,PESHAWAR,45,139736,0327-1176720,active,"Excel,Power BI",91,Excel,Power BI
18,19,Bilal,Finance,ISLAMABAD,28,123860,0349-6835853,active,"Excel,Power BI",82,Excel,Power BI
...,...,...,...,...,...,...,...,...,...,...,...,...
990,991,Ali,HR,PESHAWAR,21,70125,0313-6237288,active,"Java,Python",82,Java,Python
991,992,Ayesha,HR,QUETTA,30,114558,0315-4752548,active,"Python,Excel",82,Python,Excel
993,994,Hina,HR,KARACHI,21,128964,0324-6002723,inactive,"SQL,Python",91,SQL,Python
996,997,Ahmed,Finance,LAHORE,42,90919,0300-2999562,active,"SQL,Python",82,SQL,Python
997,998,Hina,CS,KARACHI,33,153119,0305-6756228,active,"Java,Python",91,Java,Python

In [128]:
df[df["City"] == "KARACHI"]

,ID,Name,Department,City,Age,Salary,Phone,Status,Skills,Performance,Skills1,Skill2
1,2,Ali,Finance,KARACHI,44,176975,0308-5916045,active,"Excel,Power BI",91,Excel,Power BI
5,6,Hamza,Sales,KARACHI,36,52773,0305-9962052,active,"SQL,Python",78,SQL,Python
6,7,Bilal,IT,KARACHI,23,63274,0310-8507841,inactive,"Python,SQL",76,Python,SQL
16,17,Bilal,HR,KARACHI,34,54688,0329-3032555,active,"Python,SQL",55,Python,SQL
21,22,Bilal,Sales,KARACHI,37,96408,0308-8964310,active,"Python,SQL",89,Python,SQL
...,...,...,...,...,...,...,...,...,...,...,...,...
980,981,Bilal,HR,KARACHI,28,64229,0318-8122566,active,"SQL,Python",76,SQL,Python
985,986,Fatima,Finance,KARACHI,30,162479,0308-2242663,active,"Java,Python",67,Java,Python
987,988,Zain,HR,KARACHI,43,81111,0348-7464735,inactive,"Java,Python",91,Java,Python
993,994,Hina,HR,KARACHI,21,128964,0324-6002723,inactive,"SQL,Python",91,SQL,Python
997,998,Hina,CS,KARACHI,33,153119,0305-6756228,active,"Java,Python",91,Java,Python

In [133]:
it_performance = df[(df["Department"] == "IT") & (df["Performance"] < 70)]
it_performance

,ID,Name,Department,City,Age,Salary,Phone,Status,Skills,Performance,Skills1,Skill2
55,56,Sara,IT,KARACHI,30,149567,0321-2550032,inactive,"SQL,Python",67,SQL,Python
60,61,Fatima,IT,ISLAMABAD,44,163305,0319-4991143,active,"Excel,Power BI",67,Excel,Power BI
69,70,Zain,IT,QUETTA,44,67021,0300-7115689,active,"Python,SQL",55,Python,SQL
83,84,Zain,IT,LAHORE,27,97236,0302-9563966,active,"Java,Python",55,Java,Python
94,95,Hamza,IT,ISLAMABAD,32,112943,0328-4142107,inactive,"Excel,Power BI",67,Excel,Power BI
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,Ayesha,IT,PESHAWAR,37,57532,0338-4204394,active,"Python,SQL",55,Python,SQL
928,929,Hamza,IT,ISLAMABAD,23,129566,0323-4996098,inactive,"SQL,Python",67,SQL,Python
932,933,Sara,IT,QUETTA,29,133139,0309-5204511,inactive,"Excel,Power BI",67,Excel,Power BI
946,947,Usman,IT,ISLAMABAD,43,122910,0347-7727145,active,"Excel,Power BI",67,Excel,Power BI
975,976,Hina,IT,LAHORE,21,97386,0308-1527122,active,"SQL,Python",55,SQL,Python

In [136]:
avg_salary = df["Salary"].mean()
avg_salary

np.float64(111069.418)