## Task 4:

### Part A – Merge
1. Merge employees.csv and salary.csv using EmployeeID.
2. Merge the resulting dataframe with performance.csv.
3. Display the final dataframe containing:
    - EmployeeID
    - Name
    - Department
    - Salary
    - Rating

In [1]:
import pandas as pd

In [2]:
emp = pd.read_csv("../Test Material/employees.csv")
salary = pd.read_csv("../Test Material/salary.csv")
performance = pd.read_csv("../Test Material/performance.csv")

In [3]:
emp

     EmployeeID          Name Department
0           101  Kashif Ahmed      Sales
1           102     Sara Khan  Marketing
2           103      Zain Ali  Marketing
3           104    Sara Iqbal         HR
4           105     Sara Khan      Sales
..          ...           ...        ...
481         590   Usman Iqbal      Sales
482         596  Kashif Iqbal         HR
483         597    Amna Iqbal      Sales
484         598    Iqra Iqbal         IT
485         600      Umer Ali         HR

[486 rows x 3 columns]

In [4]:
salary

     EmployeeID  Salary
0           101  100000
1           102  129000
2           103  124000
3           104   59000
4           105  122000
..          ...     ...
491         595  139000
492         596  112000
493         597   81000
494         598  113000
495         600  119000

[496 rows x 2 columns]

In [5]:
performance

     EmployeeID Rating
0           103      A
1           104      A
2           105      B
3           106      B
4           107      A
..          ...    ...
493         596      A
494         597      A
495         598      A
496         599      A
497         600      B

[498 rows x 2 columns]

In [6]:
df = pd.merge(emp,salary,on='EmployeeID')
df

     EmployeeID          Name Department  Salary
0           101  Kashif Ahmed      Sales  100000
1           102     Sara Khan  Marketing  129000
2           103      Zain Ali  Marketing  124000
3           104    Sara Iqbal         HR   59000
4           105     Sara Khan      Sales  122000
..          ...           ...        ...     ...
478         590   Usman Iqbal      Sales  121000
479         596  Kashif Iqbal         HR  112000
480         597    Amna Iqbal      Sales   81000
481         598    Iqra Iqbal         IT  113000
482         600      Umer Ali         HR  119000

[483 rows x 4 columns]

In [7]:
final_df = pd.merge(df,performance,on="EmployeeID")
final_df

     EmployeeID          Name Department  Salary Rating
0           103      Zain Ali  Marketing  124000      A
1           104    Sara Iqbal         HR   59000      A
2           105     Sara Khan      Sales  122000      B
3           106    Yasir Khan         HR   71000      B
4           108    Sara Iqbal         IT   54000      B
..          ...           ...        ...     ...    ...
476         590   Usman Iqbal      Sales  121000      A
477         596  Kashif Iqbal         HR  112000      A
478         597    Amna Iqbal      Sales   81000      A
479         598    Iqra Iqbal         IT  113000      A
480         600      Umer Ali         HR  119000      B

[481 rows x 5 columns]

### Part B – Concat
4. Concatenate employees.csv and new_employees.csv to create a single employee
database.
5. Display the total number of employees after concatenation.

In [8]:
new_emp = pd.read_csv("../Test Material/new_employees.csv")
new_emp

     EmployeeID         Name Department
0           601  Bilal Ahmed      Sales
1           602    Amna Raza         IT
2           603    Sara Khan  Marketing
3           604  Usman Iqbal    Finance
4           605   Maham Khan  Marketing
..          ...          ...        ...
145         746  Ahmed Ahmed    Finance
146         747  Ayesha Raza    Finance
147         748    Noor Raza      Sales
148         749   Ayesha Ali         HR
149         750      Ali Ali    Finance

[150 rows x 3 columns]

In [12]:
emp_db = pd.concat([emp,new_emp], ignore_index=True)
emp_db

     EmployeeID          Name Department
0           101  Kashif Ahmed      Sales
1           102     Sara Khan  Marketing
2           103      Zain Ali  Marketing
3           104    Sara Iqbal         HR
4           105     Sara Khan      Sales
..          ...           ...        ...
631         746   Ahmed Ahmed    Finance
632         747   Ayesha Raza    Finance
633         748     Noor Raza      Sales
634         749    Ayesha Ali         HR
635         750       Ali Ali    Finance

[636 rows x 3 columns]

In [11]:
print("Employees in employees.csv file: ", len(emp))
print("Employees in new_employees.csv file: ", len(new_emp))
print("Employees after concat: ", len(emp_db))

Employees in employees.csv file:  486
Employees in new_employees.csv file:  150
Employees after concat:  636

### Part C – Analysis
Using the merged dataframe,
- Display employees whose salary is greater than 80,000.
- Display employees with Rating A.
- Calculate the average salary department-wise.

In [17]:
final_df[final_df["Salary"] > 80000]

     EmployeeID          Name Department  Salary Rating
0           103      Zain Ali  Marketing  124000      A
2           105     Sara Khan      Sales  122000      B
6           112   Maham Ahmed    Finance  129000      A
9           116    Umer Iqbal         HR  139000      A
13          121    Saad Iqbal      Sales  138000      B
..          ...           ...        ...     ...    ...
476         590   Usman Iqbal      Sales  121000      A
477         596  Kashif Iqbal         HR  112000      A
478         597    Amna Iqbal      Sales   81000      A
479         598    Iqra Iqbal         IT  113000      A
480         600      Umer Ali         HR  119000      B

[340 rows x 5 columns]

In [18]:
final_df[final_df["Rating"] == 'A']

     EmployeeID          Name Department  Salary Rating
0           103      Zain Ali  Marketing  124000      A
1           104    Sara Iqbal         HR   59000      A
5           109   Bilal Iqbal         IT   53000      A
6           112   Maham Ahmed    Finance  129000      A
7           113   Yasir Ahmed  Marketing   70000      A
..          ...           ...        ...     ...    ...
475         589    Kashif Ali         IT  113000      A
476         590   Usman Iqbal      Sales  121000      A
477         596  Kashif Iqbal         HR  112000      A
478         597    Amna Iqbal      Sales   81000      A
479         598    Iqra Iqbal         IT  113000      A

[223 rows x 5 columns]

np.float64(101958.41995841995)