## RECOMMENDATION SYSTEM
- Movie Recommender System
- Content based filtering
- - In this file, we worked on data cleaning for recommendations system and tokenization

### TOPICS WE HAVE DISCUSSED (16 august class):
- Filtering = collaborative and content based filtering
- chicken and egg problem in business
- Vectors
- Similarity
- vectorisation
- bag of words
- stemming
- cosine similarity
- list comprehension

In [1]:
import pandas as pd
import json

In [2]:
movies = pd.read_csv('../Datasets/movies.csv')
credits = pd.read_csv('../Datasets/credits.csv')

In [3]:
movies.shape, credits.shape

((4803, 20), (4803, 4))

In [4]:
json.loads(movies["genres"][0])[0]

{'id': 28, 'name': 'Action'}

In [5]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [6]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

- Reason for using JSON:
  - The 'genres' column stores data as a STRING that looks like a list of dictionaries.
  - To actually work with it as a real Python dictionary, we need the JSON library.

In [7]:
# Without JSON: # Returns a plain STRING — we cannot access keys or loop through it

movies["genres"][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [8]:
# With JSON: 
    # json.loads() converts the STRING into a real Python LIST of DICTIONARIES
    # Now we can access keys like ["name"], loop through it, and extract values
json.loads(movies["genres"][0])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [9]:
# We set index to = 0 to get first line
json.loads(movies["genres"][0])[0]

# At index = 0, we write ['name'] to retrieve genre name. 
    #It's like going in without loop
json.loads(movies["genres"][0])[0]['name']

'Action'

In [10]:
## DATA MERGING

movies_credits = pd.merge(movies, credits, left_on="id", right_on="movie_id")

In [11]:
movies_credits.shape

(4803, 24)

In [12]:
movies_credits.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='object')

In [13]:
movies_credits = movies_credits[["movie_id","title_x","overview","genres","keywords",'cast', 'crew']]
movies_credits

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [14]:
movies_credits.dropna(inplace=True)

In [15]:
values = json.loads(movies["genres"][0])
values

# Using List Comprehension in Python
[value["name"] for value in values]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

- To understand above List Comprehension. We actually did for loop to save 'name' of 'genres'
- Following Code is lenghty version of above list comprehension ↓

In [16]:
# list_of_genres_names = []

# for value in values:
#     list_of_genres_names.append(value["name"])

# list_of_genres_names

In [17]:
def extract_values(str_list):
    values = json.loads(str_list)
    return [value["name"] for value in values]

In [18]:
extract_values(movies["genres"][0])

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [19]:
# Applied extract_values Function to dataFrame, now we get list of genres
movies_credits["genres"] = movies_credits["genres"].apply(extract_values)

# Same goes for keywords Column
movies_credits["keywords"] = movies_credits["keywords"].apply(extract_values)

In [20]:
# Now we want to do same for 'cast column' but we only want top 3 cast names not extra
movies_credits["cast"].apply(extract_values) # this will return every name

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4798    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4799    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4800    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4801    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4802    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4800, dtype: object

In [21]:
movies_credits["cast"] = movies_credits["cast"].apply(extract_values).apply(lambda y:y[:3]) # this will return only 3 initial cast name
movies_credits["cast"]

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4798    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4799         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4800           [Eric Mabius, Kristin Booth, Crystal Lowe]
4801            [Daniel Henney, Eliza Coupe, Bill Paxton]
4802    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4800, dtype: object

- Now we are going to fetch director

In [22]:
# Function to fetch Director:
def fetch_director(str_list):
    values = json.loads(str_list)
    return [value["name"] for value in values if value["job"] == "Director"]

In [23]:
fetch_director(movies_credits["crew"][0])

['James Cameron']

In [24]:
# # Convert the 'crew' column string into a real Python list of dictionaries
# values = json.loads(movie_credits["crew"][0])

# # Loop through every crew member in the list
# for value in values:
#     job  = value["job"]   # extract the job title of this crew member
#     name = value["name"]  # extract the name of this crew member

#     # We only want the Director — filter out everyone else
#     if job == "Director":
#         print(name, " : ", job)

In [25]:
movies_credits["crew"] = movies_credits["crew"].apply(fetch_director)
movies_credits

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns]
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [27]:
movies_credits["overview"] = movies_credits["overview"].str.split()

In [28]:
def collapse(lst):
    final_lst = []
    for i in lst:
        final_lst.append(i.replace(" ", ""))
    return final_lst

In [30]:
collapse(["Action","Adventure","Fantasy","Science Fiction"])

['Action', 'Adventure', 'Fantasy', 'ScienceFiction']

In [33]:
movies_credits["cast"] = movies_credits["cast"].apply(collapse)
movies_credits["crew"] = movies_credits["crew"].apply(collapse)
movies_credits["genres"] = movies_credits["genres"].apply(collapse)
movies_credits["keywords"] = movies_credits["keywords"].apply(collapse)

In [36]:
movies_credits["tags"] = movies_credits["overview"] + movies_credits["genres"] + movies_credits["keywords"] + movies_credits["cast"]