## SQLITE CLASS 2: 20th Sept
- SUB QUERIES

In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
db = "jobs.db"
conn = sql.connect(db)

In [3]:
# Master Query
q = "select * from sqlite_master"

pd.read_sql_query(q,conn)

,type,name,tbl_name,rootpage,sql
0,table,recent_grads,recent_grads,2,"CREATE TABLE ""recent_grads"" (\n""index"" INTEGER..."
1,index,ix_recent_grads_index,recent_grads,3,"CREATE INDEX ""ix_recent_grads_index""ON ""recent..."

Syntax: 
- Select:
  - query = `"select [column selection] from [table name] [for rows selection]"`

In [4]:
q = "select * from recent_grads"

pd.read_sql_query(q,conn)

,index,Rank,Major_code,Major,Major_category,Total,Sample_size,Men,Women,ShareWomen,...,Part_time,Full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,College_jobs,Non_college_jobs,Low_wage_jobs
0,0,1,2419,PETROLEUM ENGINEERING,Engineering,2339,36,2057,282,0.120564,...,270,1207,37,0.018381,110000,95000,125000,1534,364,193
1,1,2,2416,MINING AND MINERAL ENGINEERING,Engineering,756,7,679,77,0.101852,...,170,388,85,0.117241,75000,55000,90000,350,257,50
2,2,3,2415,METALLURGICAL ENGINEERING,Engineering,856,3,725,131,0.153037,...,133,340,16,0.024096,73000,50000,105000,456,176,0
3,3,4,2417,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258,16,1123,135,0.107313,...,150,692,40,0.050125,70000,43000,80000,529,102,0
4,4,5,2405,CHEMICAL ENGINEERING,Engineering,32260,289,21239,11021,0.341631,...,5180,16697,1672,0.061098,65000,50000,75000,18314,4440,972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,168,169,3609,ZOOLOGY,Biology & Life Science,8409,47,3050,5359,0.637293,...,2190,3602,304,0.046320,26000,20000,39000,2771,2947,743
169,169,170,5201,EDUCATIONAL PSYCHOLOGY,Psychology & Social Work,2854,7,522,2332,0.817099,...,572,1211,148,0.065112,25000,24000,34000,1488,615,82
170,170,171,5202,CLINICAL PSYCHOLOGY,Psychology & Social Work,2838,13,568,2270,0.799859,...,648,1293,368,0.149048,25000,25000,40000,986,870,622
171,171,172,5203,COUNSELING PSYCHOLOGY,Psychology & Social Work,4626,21,931,3695,0.798746,...,965,2738,214,0.053621,23400,19200,26000,2403,1245,308
172,172,173,3501,LIBRARY SCIENCE,Education,1098,2,134,964,0.877960,...,237,410,87,0.104946,22000,20000,22000,288,338,192

In [5]:
## Limit filter: Will extract only 5
q = "select * from recent_grads limit 5"

pd.read_sql_query(q,conn)

,index,Rank,Major_code,Major,Major_category,Total,Sample_size,Men,Women,ShareWomen,...,Part_time,Full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,College_jobs,Non_college_jobs,Low_wage_jobs
0,0,1,2419,PETROLEUM ENGINEERING,Engineering,2339,36,2057,282,0.120564,...,270,1207,37,0.018381,110000,95000,125000,1534,364,193
1,1,2,2416,MINING AND MINERAL ENGINEERING,Engineering,756,7,679,77,0.101852,...,170,388,85,0.117241,75000,55000,90000,350,257,50
2,2,3,2415,METALLURGICAL ENGINEERING,Engineering,856,3,725,131,0.153037,...,133,340,16,0.024096,73000,50000,105000,456,176,0
3,3,4,2417,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258,16,1123,135,0.107313,...,150,692,40,0.050125,70000,43000,80000,529,102,0
4,4,5,2405,CHEMICAL ENGINEERING,Engineering,32260,289,21239,11021,0.341631,...,5180,16697,1672,0.061098,65000,50000,75000,18314,4440,972

In [6]:
q = "select ShareWomen, Major from recent_grads limit 5"

pd.read_sql_query(q,conn)

   ShareWomen                                      Major
0    0.120564                      PETROLEUM ENGINEERING
1    0.101852             MINING AND MINERAL ENGINEERING
2    0.153037                  METALLURGICAL ENGINEERING
3    0.107313  NAVAL ARCHITECTURE AND MARINE ENGINEERING
4    0.341631                       CHEMICAL ENGINEERING

- You can use `""" string """` or `Triple Coats` for multiple lines of string
- `Filtering Data` using condition: `WHERE CONDITION`

In [7]:
q = """select ShareWomen, Major from recent_grads where ShareWomen > 0.5"""

pd.read_sql_query(q,conn)

    ShareWomen                               Major
0     0.535714                   ACTUARIAL SCIENCE
1     0.578766                    COMPUTER SCIENCE
2     0.558548           ENVIRONMENTAL ENGINEERING
3     0.896019                             NURSING
4     0.750473  INDUSTRIAL PRODUCTION TECHNOLOGIES
..         ...                                 ...
92    0.637293                             ZOOLOGY
93    0.817099              EDUCATIONAL PSYCHOLOGY
94    0.799859                 CLINICAL PSYCHOLOGY
95    0.798746               COUNSELING PSYCHOLOGY
96    0.877960                     LIBRARY SCIENCE

[97 rows x 2 columns]

In [8]:
q = """select ShareWomen, Major from recent_grads 
    where ShareWomen > 0.5 and ShareWomen < 0.8"""

pd.read_sql_query(q,conn)

    ShareWomen                               Major
0     0.535714                   ACTUARIAL SCIENCE
1     0.578766                    COMPUTER SCIENCE
2     0.558548           ENVIRONMENTAL ENGINEERING
3     0.750473  INDUSTRIAL PRODUCTION TECHNOLOGIES
4     0.707719    COMPUTER AND INFORMATION SYSTEMS
..         ...                                 ...
74    0.629505              DRAMA AND THEATER ARTS
75    0.666119            COMPOSITION AND RHETORIC
76    0.637293                             ZOOLOGY
77    0.799859                 CLINICAL PSYCHOLOGY
78    0.798746               COUNSELING PSYCHOLOGY

[79 rows x 2 columns]

- `orderby`

In [9]:
# Filtering: imagine a condition where u need to filter, ShareWomen should be greater than 0.5 or  ShareWomen should be less than or equal to 0.5 and Major == "Engineering"
q = """SELECT ShareWomen, Major_Category ,Major FROM recent_grads 
    WHERE ShareWomen > 0.5 or (ShareWomen <= 0.5 and Major_Category == "Engineering") 
    """

pd.read_sql_query(q,conn)

,ShareWomen,Major_category,Major
0,0.120564,Engineering,PETROLEUM ENGINEERING
1,0.101852,Engineering,MINING AND MINERAL ENGINEERING
2,0.153037,Engineering,METALLURGICAL ENGINEERING
3,0.107313,Engineering,NAVAL ARCHITECTURE AND MARINE ENGINEERING
4,0.341631,Engineering,CHEMICAL ENGINEERING
...,...,...,...
119,0.637293,Biology & Life Science,ZOOLOGY
120,0.817099,Psychology & Social Work,EDUCATIONAL PSYCHOLOGY
121,0.799859,Psychology & Social Work,CLINICAL PSYCHOLOGY
122,0.798746,Psychology & Social Work,COUNSELING PSYCHOLOGY
123,0.877960,Education,LIBRARY SCIENCE

In [10]:
# order by ascending order
q = """SELECT ShareWomen, Major_Category ,Major FROM recent_grads 
    WHERE ShareWomen > 0.5 or (ShareWomen <= 0.5 and Major_Category == "Engineering") 
    ORDER BY ShareWomen ASC
    """

pd.read_sql_query(q,conn)

,ShareWomen,Major_category,Major
0,0.000000,Engineering,MISCELLANEOUS ENGINEERING TECHNOLOGIES
1,0.090713,Engineering,ENGINEERING TECHNOLOGIES
2,0.101852,Engineering,MINING AND MINERAL ENGINEERING
3,0.107313,Engineering,NAVAL ARCHITECTURE AND MARINE ENGINEERING
4,0.119559,Engineering,BIOMEDICAL ENGINEERING
...,...,...,...
119,0.910933,Agriculture & Natural Resources,ANIMAL SCIENCES
120,0.923745,Education,ELEMENTARY EDUCATION
121,0.927807,Computers & Mathematics,MATHEMATICS AND COMPUTER SCIENCE
122,0.967998,Education,EARLY CHILDHOOD EDUCATION
123,0.968954,Humanities & Liberal Arts,ANTHROPOLOGY AND ARCHEOLOGY

In [11]:
# order by descending order
q = """SELECT ShareWomen, Major_Category ,Major FROM recent_grads 
    WHERE ShareWomen > 0.5 or (ShareWomen <= 0.5 and Major_Category == "Engineering") 
    ORDER BY ShareWomen DESC limit 4
    """

pd.read_sql_query(q,conn)

   ShareWomen             Major_category                             Major
0    0.968954  Humanities & Liberal Arts       ANTHROPOLOGY AND ARCHEOLOGY
1    0.967998                  Education         EARLY CHILDHOOD EDUCATION
2    0.927807    Computers & Mathematics  MATHEMATICS AND COMPUTER SCIENCE
3    0.923745                  Education              ELEMENTARY EDUCATION

In [12]:
# avg function
q = """SELECT avg(ShareWomen) FROM recent_grads 
    WHERE ShareWomen > 0.5 or (ShareWomen <= 0.5 and Major_Category == "Engineering") 
    """

pd.read_sql_query(q,conn)

   avg(ShareWomen)
0         0.593841

In [13]:
# Limit: Does not work on data agg function

q = """SELECT avg(ShareWomen) FROM recent_grads 
    WHERE ShareWomen > 0.5 or (ShareWomen <= 0.5 and Major_Category == "Engineering") 
    limit 10
    """

pd.read_sql_query(q,conn)

   avg(ShareWomen)
0         0.593841

In [14]:
# Count function
q = """SELECT avg(ShareWomen), count(Major_Category) FROM recent_grads 
    WHERE ShareWomen > 0.5 or (ShareWomen <= 0.5 and Major_Category == "Engineering") 
    """

pd.read_sql_query(q,conn)

   avg(ShareWomen)  count(Major_Category)
0         0.593841                    124

- We want to identify unique categories from *Major_Category*
  - We Will use `DISTINCT` function

In [15]:
q = """ Select DISTINCT(Major_Category) FROM  recent_grads"""

pd.read_sql_query(q,conn)

                         Major_category
0                           Engineering
1                              Business
2                     Physical Sciences
3                   Law & Public Policy
4               Computers & Mathematics
5       Agriculture & Natural Resources
6   Industrial Arts & Consumer Services
7                                  Arts
8                                Health
9                        Social Science
10               Biology & Life Science
11                            Education
12            Humanities & Liberal Arts
13             Psychology & Social Work
14          Communications & Journalism
15                    Interdisciplinary

- `GROUP BY` function

In [16]:
q = """SELECT Major_Category, avg(ShareWomen) FROM recent_grads GROUP BY  Major_Category"""

pd.read_sql_query(q,conn)

                         Major_category  avg(ShareWomen)
0       Agriculture & Natural Resources         0.617938
1                                  Arts         0.561851
2                Biology & Life Science         0.584518
3                              Business         0.405063
4           Communications & Journalism         0.643835
5               Computers & Mathematics         0.512752
6                             Education         0.674986
7                           Engineering         0.257158
8                                Health         0.616857
9             Humanities & Liberal Arts         0.676193
10  Industrial Arts & Consumer Services         0.449351
11                    Interdisciplinary         0.495397
12                  Law & Public Policy         0.335990
13                    Physical Sciences         0.508749
14             Psychology & Social Work         0.777763
15                       Social Science         0.539067

- `HAVING`: The SQL HAVING clause is used to filter grouped data and aggregate functions after a GROUP BY clause has been applied.

In [17]:
q = """SELECT Major_Category, avg(ShareWomen) FROM recent_grads GROUP BY  Major_Category HAVING avg(ShareWomen) > 0.5"""

pd.read_sql_query(q,conn)

                     Major_category  avg(ShareWomen)
0   Agriculture & Natural Resources         0.617938
1                              Arts         0.561851
2            Biology & Life Science         0.584518
3       Communications & Journalism         0.643835
4           Computers & Mathematics         0.512752
5                         Education         0.674986
6                            Health         0.616857
7         Humanities & Liberal Arts         0.676193
8                 Physical Sciences         0.508749
9          Psychology & Social Work         0.777763
10                   Social Science         0.539067

**SQL alias**
- An SQL alias is a temporary name assigned to a table or column within an SQL query. It is created using the AS keyword and exists only for the duration of that specific query

In [18]:
q = """SELECT Major_Category, avg(ShareWomen) as Average FROM recent_grads GROUP BY  Major_Category HAVING Average > 0.5"""

pd.read_sql_query(q,conn)

                     Major_category   Average
0   Agriculture & Natural Resources  0.617938
1                              Arts  0.561851
2            Biology & Life Science  0.584518
3       Communications & Journalism  0.643835
4           Computers & Mathematics  0.512752
5                         Education  0.674986
6                            Health  0.616857
7         Humanities & Liberal Arts  0.676193
8                 Physical Sciences  0.508749
9          Psychology & Social Work  0.777763
10                   Social Science  0.539067

`cast():` The CAST() function in SQL explicitly converts an expression or column from its current data type into a specified target data type

In [19]:
q = """Select CAST(Women as float) FROM recent_grads"""

pd.read_sql_query(q,conn)

     CAST(Women as float)
0                   282.0
1                    77.0
2                   131.0
3                   135.0
4                 11021.0
..                    ...
168                5359.0
169                2332.0
170                2270.0
171                3695.0
172                 964.0

[173 rows x 1 columns]

In [20]:
q = """SELECT Women, Total FROM recent_grads """

pd.read_sql_query(q,conn)

     Women  Total
0      282   2339
1       77    756
2      131    856
3      135   1258
4    11021  32260
..     ...    ...
168   5359   8409
169   2332   2854
170   2270   2838
171   3695   4626
172    964   1098

[173 rows x 2 columns]

- SQL will always prioritize **FLOAT datatype over INT**

In [21]:
q = """SELECT (Women/Total)*100 FROM recent_grads """

pd.read_sql_query(q,conn)

     (Women/Total)*100
0                    0
1                    0
2                    0
3                    0
4                    0
..                 ...
168                  0
169                  0
170                  0
171                  0
172                  0

[173 rows x 1 columns]

In [22]:
q = """SELECT (Women/cast(Total as float))*100 FROM recent_grads """

pd.read_sql_query(q,conn)

     (Women/cast(Total as float))*100
0                           12.056434
1                           10.185185
2                           15.303738
3                           10.731320
4                           34.163050
..                                ...
168                         63.729338
169                         81.709881
170                         79.985906
171                         79.874622
172                         87.795993

[173 rows x 1 columns]

### SUBQUERY in SQL
**Subquery is a query inside a query**

- Imagine a condition where we need only values greater than average of `'ShareWomen'`

In [25]:
q = """SELECT Major, Major_category, ShareWomen FROM recent_grads """

pd.read_sql_query(q,conn)

,Major,Major_category,ShareWomen
0,PETROLEUM ENGINEERING,Engineering,0.120564
1,MINING AND MINERAL ENGINEERING,Engineering,0.101852
2,METALLURGICAL ENGINEERING,Engineering,0.153037
3,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,0.107313
4,CHEMICAL ENGINEERING,Engineering,0.341631
...,...,...,...
168,ZOOLOGY,Biology & Life Science,0.637293
169,EDUCATIONAL PSYCHOLOGY,Psychology & Social Work,0.817099
170,CLINICAL PSYCHOLOGY,Psychology & Social Work,0.799859
171,COUNSELING PSYCHOLOGY,Psychology & Social Work,0.798746
172,LIBRARY SCIENCE,Education,0.877960

In [26]:
q = """ SELECT avg(ShareWomen) FROM recent_grads"""


pd.read_sql_query(q,conn)

   avg(ShareWomen)
0          0.52255

- using `Subquery` to meet the condition.
  We will put the `above average query` inside the `query of Major,	Major_category,	ShareWomen rows`

In [28]:
q = """SELECT Major, Major_category, ShareWomen FROM recent_grads 
        WHERE ShareWomen > (SELECT avg(ShareWomen) FROM recent_grads)"""

pd.read_sql_query(q,conn)

                                 Major            Major_category  ShareWomen
0                    ACTUARIAL SCIENCE                  Business    0.535714
1                     COMPUTER SCIENCE   Computers & Mathematics    0.578766
2            ENVIRONMENTAL ENGINEERING               Engineering    0.558548
3                              NURSING                    Health    0.896019
4   INDUSTRIAL PRODUCTION TECHNOLOGIES               Engineering    0.750473
..                                 ...                       ...         ...
86                             ZOOLOGY    Biology & Life Science    0.637293
87              EDUCATIONAL PSYCHOLOGY  Psychology & Social Work    0.817099
88                 CLINICAL PSYCHOLOGY  Psychology & Social Work    0.799859
89               COUNSELING PSYCHOLOGY  Psychology & Social Work    0.798746
90                     LIBRARY SCIENCE                 Education    0.877960

[91 rows x 3 columns]

- Using `ORDER BY` for columns-wise selection for applying condition.
    - In simple terms it means `ORDER BY 3` means kay 3rd column(ShareWomen) kay behalf pr DESC kro

In [30]:
q = """SELECT Major, Major_Category, ShareWomen FROM recent_grads 
        WHERE ShareWomen > (SELECT avg(ShareWomen) FROM recent_grads)
        ORDER BY 3 DESC
        LIMIT 5"""

pd.read_sql_query(q,conn)

,Major,Major_category,ShareWomen
0,ANTHROPOLOGY AND ARCHEOLOGY,Humanities & Liberal Arts,0.968954
1,EARLY CHILDHOOD EDUCATION,Education,0.967998
2,MATHEMATICS AND COMPUTER SCIENCE,Computers & Mathematics,0.927807
3,ELEMENTARY EDUCATION,Education,0.923745
4,ANIMAL SCIENCES,Agriculture & Natural Resources,0.910933

In [32]:
q = """SELECT Major, Major_Category, ShareWomen FROM recent_grads 
        WHERE ShareWomen > (SELECT avg(ShareWomen) FROM recent_grads)
        ORDER BY 2 DESC
        LIMIT 5"""

pd.read_sql_query(q,conn)

                               Major  Major_category  ShareWomen
0            INTERNATIONAL RELATIONS  Social Science    0.632987
1      MISCELLANEOUS SOCIAL SCIENCES  Social Science    0.543405
2                        CRIMINOLOGY  Social Science    0.618223
3                          SOCIOLOGY  Social Science    0.532334
4  INTERDISCIPLINARY SOCIAL SCIENCES  Social Science    0.721866