## Song recommendation system

In [1]:
import pandas as pd
import json

In [2]:
songs = pd.read_csv("./songs.csv")

In [3]:
songs

,track_id,title,artist,genre,subgenre,mood,themes,instruments,language,year,era,tempo_bpm,energy,danceability,acousticness,duration_sec
0,1001,Hollow Bones,Ridge Choir,Pop,synthpop,catchy|upbeat,city lights|youth,drum machine|electric guitar|synthesizer,english,1975,1970s,111,0.868,0.842,0.037,126
1,1002,Salt Letters,Lark Trio,Folk,folk revival,wistful|storytelling,the road|family,NaN,english,2009,2000s,97,0.382,0.398,0.672,226
2,1003,Restless Machines,Lumen Petrov,Classical,romantic era,sweeping|solemn,memory|the sea|nature,cello|piano,instrumental,2004,2000s,97,0.187,0.208,0.971,242
3,1004,Salt Window,Quarry Lindqvist,Jazz,jazz fusion,improvised|late night,midnight|the city,brushed drums|saxophone|piano,instrumental,1988,1980s,119,0.398,0.576,0.612,371
4,1005,Winter Highway,Pallas Society,Electronic,ambient techno,hypnotic|euphoric,night drive|neon,sub bass|synthesizer,english,1988,1980s,135,0.803,0.733,0.046,171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,1325,Glass Cathedral,Onyx Okonkwo,Rock,alt rock,restless|raw,the road|small town|rebellion,drum kit|electric guitar,english,2020,2020s,138,0.925,0.406,0.059,324
325,1326,Sleepless Signal,Tarn Trio,Jazz,jazz fusion,smooth|late night,midnight|conversation,brushed drums|piano,english,1994,1990s,137,0.427,0.425,0.700,297
326,1327,Silver Static,Pallas Society,Electronic,ambient techno,hypnotic|euphoric,the club|neon,synthesizer|sub bass,instrumental,1972,1970s,162,0.721,0.881,0.051,318
327,1328,Distant Cathedral,Ember Avenue,Metal,doom metal,aggressive|intense,the abyss|machines|apocalypse,double bass drum|distorted guitar|growled vocals,english,1969,1960s,156,0.977,0.450,0.016,367
328,1329,Copper Ceiling,Kestrel Trio,Electronic,techno,nocturnal|hypnotic,the club|night drive,sampler|drum machine,instrumental,2020,2020s,145,0.821,0.796,0.100,253

In [4]:
songs.columns

Index(['track_id', 'title', 'artist', 'genre', 'subgenre', 'mood', 'themes',
       'instruments', 'language', 'year', 'era', 'tempo_bpm', 'energy',
       'danceability', 'acousticness', 'duration_sec'],
      dtype='object')

#### Following are some most used for song recommendation 
-    [genre + mood + era + energy + tempo_bpm + danceability + acousticness]

In [5]:
songs["genre"]

0             Pop
1            Folk
2       Classical
3            Jazz
4      Electronic
          ...
324          Rock
325          Jazz
326    Electronic
327         Metal
328    Electronic
Name: genre, Length: 329, dtype: object

In [6]:
songs_df = songs[["title","genre","era","mood","energy","tempo_bpm","danceability","acousticness"]]
songs_df

,title,genre,era,mood,energy,tempo_bpm,danceability,acousticness
0,Hollow Bones,Pop,1970s,catchy|upbeat,0.868,111,0.842,0.037
1,Salt Letters,Folk,2000s,wistful|storytelling,0.382,97,0.398,0.672
2,Restless Machines,Classical,2000s,sweeping|solemn,0.187,97,0.208,0.971
3,Salt Window,Jazz,1980s,improvised|late night,0.398,119,0.576,0.612
4,Winter Highway,Electronic,1980s,hypnotic|euphoric,0.803,135,0.733,0.046
...,...,...,...,...,...,...,...,...
324,Glass Cathedral,Rock,2020s,restless|raw,0.925,138,0.406,0.059
325,Sleepless Signal,Jazz,1990s,smooth|late night,0.427,137,0.425,0.700
326,Silver Static,Electronic,1970s,hypnotic|euphoric,0.721,162,0.881,0.051
327,Distant Cathedral,Metal,1960s,aggressive|intense,0.977,156,0.450,0.016
328,Copper Ceiling,Electronic,2020s,nocturnal|hypnotic,0.821,145,0.796,0.100

In [7]:
songs_df.isna().value_counts()

title  genre  era    mood   energy  tempo_bpm  danceability  acousticness
False  False  False  False  False   False      False         False           329
Name: count, dtype: int64

In [8]:
print(type(songs_df["genre"][0]))

<class 'str'>

In [9]:
values = songs_df["genre"]
values

[value for value in values]

['Pop',
 'Folk',
 'Classical',
 'Jazz',
 'Electronic',
 'Country',
 'Reggae',
 'Jazz',
 'Pop',
 'Folk',
 'R&B',
 'Reggae',
 'Lo-fi',
 'Country',
 'Jazz',
 'R&B',
 'Jazz',
 'Pop',
 'Folk',
 'Hip-Hop',
 'Country',
 'Hip-Hop',
 'Classical',
 'Classical',
 'Lo-fi',
 'R&B',
 'Folk',
 'Electronic',
 'Country',
 'Rock',
 'Hip-Hop',
 'Pop',
 'Jazz',
 'Lo-fi',
 'Electronic',
 'Reggae',
 'Pop',
 'Rock',
 'Pop',
 'Country',
 'Pop',
 'Reggae',
 'Lo-fi',
 'Lo-fi',
 'R&B',
 'Hip-Hop',
 'Metal',
 'R&B',
 'Country',
 'Pop',
 'Folk',
 'Electronic',
 'Reggae',
 'R&B',
 'Electronic',
 'Metal',
 'Metal',
 'Reggae',
 'Country',
 'Metal',
 'Classical',
 'Rock',
 'Rock',
 'Folk',
 'Pop',
 'Folk',
 'Country',
 'Lo-fi',
 'Folk',
 'R&B',
 'Classical',
 'Country',
 'Hip-Hop',
 'Metal',
 'Lo-fi',
 'Lo-fi',
 'Metal',
 'Reggae',
 'Jazz',
 'Hip-Hop',
 'Lo-fi',
 'Rock',
 'Folk',
 'R&B',
 'Country',
 'Classical',
 'Folk',
 'Folk',
 'Lo-fi',
 'Jazz',
 'Classical',
 'Rock',
 'Reggae',
 'Country',
 'Classical',
 'Rock',
 'Hip-Hop',
 'Country',
 'R&B',
 'Lo-fi',
 'Rock',
 'Classical',
 'Rock',
 'Metal',
 'Metal',
 'Hip-Hop',
 'Electronic',
 'Classical',
 'Rock',
 'Metal',
 'Classical',
 'Country',
 'Country',
 'Pop',
 'Classical',
 'Reggae',
 'Rock',
 'R&B',
 'Country',
 'R&B',
 'Folk',
 'Lo-fi',
 'Metal',
 'Hip-Hop',
 'Electronic',
 'R&B',
 'Pop',
 'Pop',
 'Electronic',
 'Metal',
 'Reggae',
 'Country',
 'Country',
 'R&B',
 'Pop',
 'Hip-Hop',
 'Pop',
 'Metal',
 'Electronic',
 'Reggae',
 'Rock',
 'Reggae',
 'Metal',
 'R&B',
 'Hip-Hop',
 'Reggae',
 'Metal',
 'Rock',
 'Pop',
 'Hip-Hop',
 'Classical',
 'Folk',
 'Folk',
 'Electronic',
 'Metal',
 'Country',
 'Reggae',
 'Electronic',
 'Rock',
 'Reggae',
 'Lo-fi',
 'Classical',
 'Hip-Hop',
 'Jazz',
 'Folk',
 'Country',
 'Jazz',
 'Country',
 'Folk',
 'Jazz',
 'Reggae',
 'Classical',
 'Classical',
 'Jazz',
 'R&B',
 'Pop',
 'Rock',
 'Classical',
 'Country',
 'Reggae',
 'Pop',
 'Hip-Hop',
 'Electronic',
 'Pop',
 'Electronic',
 'Metal',
 'Pop',
 'Jazz',
 'Classical',
 'Jazz',
 'Hip-Hop',
 'Folk',
 'Hip-Hop',
 'Hip-Hop',
 'Hip-Hop',
 'Classical',
 'Country',
 'Country',
 'Electronic',
 'R&B',
 'Reggae',
 'Pop',
 'Country',
 'Pop',
 'Lo-fi',
 'Rock',
 'Metal',
 'Folk',
 'Rock',
 'Electronic',
 'Rock',
 'Jazz',
 'Metal',
 'Rock',
 'Electronic',
 'Country',
 'R&B',
 'Lo-fi',
 'Classical',
 'Classical',
 'Reggae',
 'Rock',
 'Rock',
 'Folk',
 'R&B',
 'Country',
 'Electronic',
 'Jazz',
 'Jazz',
 'Lo-fi',
 'Reggae',
 'Jazz',
 'Hip-Hop',
 'Rock',
 'Lo-fi',
 'Reggae',
 'Metal',
 'Rock',
 'R&B',
 'Hip-Hop',
 'Electronic',
 'Hip-Hop',
 'Hip-Hop',
 'Metal',
 'Folk',
 'Folk',
 'Classical',
 'Rock',
 'Reggae',
 'Reggae',
 'Rock',
 'Classical',
 'Hip-Hop',
 'Pop',
 'Folk',
 'Hip-Hop',
 'Reggae',
 'Reggae',
 'Folk',
 'Pop',
 'Reggae',
 'Country',
 'Pop',
 'Jazz',
 'Pop',
 'Electronic',
 'Rock',
 'Metal',
 'Reggae',
 'R&B',
 'R&B',
 'Metal',
 'Hip-Hop',
 'Hip-Hop',
 'Electronic',
 'Folk',
 'Jazz',
 'Hip-Hop',
 'Jazz',
 'Country',
 'Jazz',
 'Jazz',
 'Electronic',
 'Reggae',
 'Metal',
 'Lo-fi',
 'R&B',
 'Classical',
 'Metal',
 'Jazz',
 'Jazz',
 'Metal',
 'Rock',
 'Electronic',
 'Lo-fi',
 'R&B',
 'Hip-Hop',
 'Pop',
 'R&B',
 'Folk',
 'Lo-fi',
 'Reggae',
 'Metal',
 'Folk',
 'R&B',
 'R&B',
 'Classical',
 'Pop',
 'R&B',
 'Pop',
 'Rock',
 'Classical',
 'Lo-fi',
 'Reggae',
 'Metal',
 'R&B',
 'Metal',
 'Classical',
 'Electronic',
 'Country',
 'Lo-fi',
 'Jazz',
 'Metal',
 'Classical',
 'Rock',
 'Jazz',
 'Electronic',
 'Metal',
 'Electronic']

In [10]:
songs_df["genre"].apply(lambda x: [x])

0             [Pop]
1            [Folk]
2       [Classical]
3            [Jazz]
4      [Electronic]
           ...
324          [Rock]
325          [Jazz]
326    [Electronic]
327         [Metal]
328    [Electronic]
Name: genre, Length: 329, dtype: object

In [11]:
songs_df

,title,genre,era,mood,energy,tempo_bpm,danceability,acousticness
0,Hollow Bones,Pop,1970s,catchy|upbeat,0.868,111,0.842,0.037
1,Salt Letters,Folk,2000s,wistful|storytelling,0.382,97,0.398,0.672
2,Restless Machines,Classical,2000s,sweeping|solemn,0.187,97,0.208,0.971
3,Salt Window,Jazz,1980s,improvised|late night,0.398,119,0.576,0.612
4,Winter Highway,Electronic,1980s,hypnotic|euphoric,0.803,135,0.733,0.046
...,...,...,...,...,...,...,...,...
324,Glass Cathedral,Rock,2020s,restless|raw,0.925,138,0.406,0.059
325,Sleepless Signal,Jazz,1990s,smooth|late night,0.427,137,0.425,0.700
326,Silver Static,Electronic,1970s,hypnotic|euphoric,0.721,162,0.881,0.051
327,Distant Cathedral,Metal,1960s,aggressive|intense,0.977,156,0.450,0.016
328,Copper Ceiling,Electronic,2020s,nocturnal|hypnotic,0.821,145,0.796,0.100

In [12]:
# Creating a function to remove vertical bar(|) from mood
def remove(value):
    return value.replace("|", "")

In [13]:
songs_df["mood"]= songs_df["mood"].apply(remove)
songs_df

C:\Users\PC\AppData\Local\Temp\ipykernel_19648\1352986791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  songs_df["mood"]= songs_df["mood"].apply(remove)

,title,genre,era,mood,energy,tempo_bpm,danceability,acousticness
0,Hollow Bones,Pop,1970s,catchyupbeat,0.868,111,0.842,0.037
1,Salt Letters,Folk,2000s,wistfulstorytelling,0.382,97,0.398,0.672
2,Restless Machines,Classical,2000s,sweepingsolemn,0.187,97,0.208,0.971
3,Salt Window,Jazz,1980s,improvisedlate night,0.398,119,0.576,0.612
4,Winter Highway,Electronic,1980s,hypnoticeuphoric,0.803,135,0.733,0.046
...,...,...,...,...,...,...,...,...
324,Glass Cathedral,Rock,2020s,restlessraw,0.925,138,0.406,0.059
325,Sleepless Signal,Jazz,1990s,smoothlate night,0.427,137,0.425,0.700
326,Silver Static,Electronic,1970s,hypnoticeuphoric,0.721,162,0.881,0.051
327,Distant Cathedral,Metal,1960s,aggressiveintense,0.977,156,0.450,0.016
328,Copper Ceiling,Electronic,2020s,nocturnalhypnotic,0.821,145,0.796,0.100

In [14]:
# As of Now, We have completed some cleaning of data for cosine similarity and vectorization

In [16]:
songs_df

,title,genre,era,mood,energy,tempo_bpm,danceability,acousticness
0,Hollow Bones,Pop,1970s,catchyupbeat,0.868,111,0.842,0.037
1,Salt Letters,Folk,2000s,wistfulstorytelling,0.382,97,0.398,0.672
2,Restless Machines,Classical,2000s,sweepingsolemn,0.187,97,0.208,0.971
3,Salt Window,Jazz,1980s,improvisedlate night,0.398,119,0.576,0.612
4,Winter Highway,Electronic,1980s,hypnoticeuphoric,0.803,135,0.733,0.046
...,...,...,...,...,...,...,...,...
324,Glass Cathedral,Rock,2020s,restlessraw,0.925,138,0.406,0.059
325,Sleepless Signal,Jazz,1990s,smoothlate night,0.427,137,0.425,0.700
326,Silver Static,Electronic,1970s,hypnoticeuphoric,0.721,162,0.881,0.051
327,Distant Cathedral,Metal,1960s,aggressiveintense,0.977,156,0.450,0.016
328,Copper Ceiling,Electronic,2020s,nocturnalhypnotic,0.821,145,0.796,0.100