## RECOMMENDATION SYSTEM
- Movie Recommender System
- Content based filtering
- - In this file, we worked on data cleaning for recommendations system and tokenization

### TOPICS WE HAVE DISCUSSED (16 august class):
- Filtering = collaborative and content based filtering
- chicken and egg problem in business
- Vectors
- Similarity
- vectorisation
- bag of words
- stemming
- cosine similarity
- list comprehension

In [1]:
import pandas as pd
import json

In [2]:
movies = pd.read_csv('../Datasets/movies.csv')
credits = pd.read_csv('../Datasets/credits.csv')

In [3]:
movies.shape, credits.shape

((4803, 20), (4803, 4))

In [4]:
json.loads(movies["genres"][0])[0]

{'id': 28, 'name': 'Action'}

In [5]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [6]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

- Reason for using JSON:
  - The 'genres' column stores data as a STRING that looks like a list of dictionaries.
  - To actually work with it as a real Python dictionary, we need the JSON library.

In [7]:
# Without JSON: # Returns a plain STRING — we cannot access keys or loop through it

movies["genres"][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [8]:
# With JSON: 
    # json.loads() converts the STRING into a real Python LIST of DICTIONARIES
    # Now we can access keys like ["name"], loop through it, and extract values
json.loads(movies["genres"][0])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [9]:
# We set index to = 0 to get first line
json.loads(movies["genres"][0])[0]

# At index = 0, we write ['name'] to retrieve genre name. 
    #It's like going in without loop
json.loads(movies["genres"][0])[0]['name']

'Action'

In [10]:
## DATA MERGING

movies_credits = pd.merge(movies, credits, left_on="id", right_on="movie_id")

In [11]:
movies_credits.shape

(4803, 24)

In [12]:
movies_credits.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='object')

In [13]:
movies_credits = movies_credits[["movie_id","title_x","overview","genres","keywords",'cast', 'crew']]
movies_credits

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [14]:
movies_credits.dropna(inplace=True)

In [15]:
values = json.loads(movies["genres"][0])
values

# Using List Comprehension in Python
[value["name"] for value in values]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

- To understand above List Comprehension. We actually did for loop to save 'name' of 'genres'
- Following Code is lenghty version of above list comprehension ↓

In [16]:
# list_of_genres_names = []

# for value in values:
#     list_of_genres_names.append(value["name"])

# list_of_genres_names

In [17]:
def extract_values(str_list):
    values = json.loads(str_list)
    return [value["name"] for value in values]

In [18]:
extract_values(movies["genres"][0])

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [19]:
# Applied extract_values Function to dataFrame, now we get list of genres
movies_credits["genres"] = movies_credits["genres"].apply(extract_values)

# Same goes for keywords Column
movies_credits["keywords"] = movies_credits["keywords"].apply(extract_values)

In [20]:
# Now we want to do same for 'cast column' but we only want top 3 cast names not extra
movies_credits["cast"].apply(extract_values) # this will return every name

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4798    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4799    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4800    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4801    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4802    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4800, dtype: object

In [21]:
movies_credits["cast"] = movies_credits["cast"].apply(extract_values).apply(lambda y:y[:3]) # this will return only 3 initial cast name
movies_credits["cast"]

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4798    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4799         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4800           [Eric Mabius, Kristin Booth, Crystal Lowe]
4801            [Daniel Henney, Eliza Coupe, Bill Paxton]
4802    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4800, dtype: object

- Now we are going to fetch director

In [22]:
# Function to fetch Director:
def fetch_director(str_list):
    values = json.loads(str_list)
    return [value["name"] for value in values if value["job"] == "Director"]

In [23]:
fetch_director(movies_credits["crew"][0])

['James Cameron']

In [24]:
# # Convert the 'crew' column string into a real Python list of dictionaries
# values = json.loads(movie_credits["crew"][0])

# # Loop through every crew member in the list
# for value in values:
#     job  = value["job"]   # extract the job title of this crew member
#     name = value["name"]  # extract the name of this crew member

#     # We only want the Director — filter out everyone else
#     if job == "Director":
#         print(name, " : ", job)

In [25]:
movies_credits["crew"] = movies_credits["crew"].apply(fetch_director)
movies_credits

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns]
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [26]:
movies_credits["overview"] = movies_credits["overview"].str.split()

In [27]:
def collapse(lst):
    final_lst = []
    for i in lst:
        final_lst.append(i.replace(" ", ""))
    return final_lst

In [28]:
collapse(["Action","Adventure","Fantasy","Science Fiction"])

['Action', 'Adventure', 'Fantasy', 'ScienceFiction']

In [29]:
movies_credits["cast"] = movies_credits["cast"].apply(collapse)
movies_credits["crew"] = movies_credits["crew"].apply(collapse)
movies_credits["genres"] = movies_credits["genres"].apply(collapse)
movies_credits["keywords"] = movies_credits["keywords"].apply(collapse)

In [30]:
movies_credits["tags"] = movies_credits["overview"] + movies_credits["genres"] + movies_credits["keywords"] + movies_credits["cast"]

In [31]:
final_df = movies_credits[["movie_id", "title_x", "tags"]]

**Class 23/8/26**
- Discussion on Explainatory vs Exploratory Data Analysis
- In Interview, Always answer in a way so no question from question comes
- bag of words, tf idf
- sklearn and CountVectorizer
- stemming
- vectors and its comparison
- cosine similarity

In [32]:
# Following work is required for machine learning model.
# ML model does not need tokens or list, it needs paragraph so we are converting it from list to string of paragraph

# ml model function input requires-> str -> split()

In [33]:
# This is the behind the scene work of below code
" ".join(final_df["tags"][0])

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver'

In [34]:
final_df["tags"] = final_df["tags"].apply(lambda x: " ".join(x)).str.lower()

C:\Users\PC\AppData\Local\Temp\ipykernel_23472\1055519200.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["tags"] = final_df["tags"].apply(lambda x: " ".join(x)).str.lower()

In [35]:
final_df["tags"][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver'

### Now We will do stemming

In [36]:
# NLP helps in machine understanding human language
import nltk

In [37]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [38]:
ps.stem("loved")

'love'

In [39]:
ps.stem("loving")

'love'

In [40]:
ps.stem("dancing")

'danc'

In [41]:
ps.stem("Danced")

'danc'

In [42]:
# Function for stemming using for loops
def stem(txt):
    lst = []

    for i in txt.split():
        lst.append(ps.stem(i))

    return " ".join(lst)

In [43]:
final_df["tags"] = final_df["tags"].apply(stem)

C:\Users\PC\AppData\Local\Temp\ipykernel_23472\1628141165.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["tags"] = final_df["tags"].apply(stem)

In [44]:
final_df.head()

,movie_id,title_x,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [45]:
## sklearn and CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
cv = CountVectorizer(max_features=5000, stop_words="english")

In [47]:
vector = cv.fit_transform(final_df["tags"])

In [48]:
vector = vector.toarray()

In [49]:
# features names
list(cv.get_feature_names_out())

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brian',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasev',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinderella',
 'cindi',
 'cinema',
 'circl',
 'circle',
 'circu',
 'circuit',
 'circumst',
 'circumstances',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilization',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collide',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'comicbook',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compound',
 'compromis',
 'compton',
 'compuls',
 'comput',
 'computer',
 'computerviru',
 'conan',
 'concentrationcamp',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 ...]

In [50]:
final_df.shape

(4800, 3)

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

In [52]:
# Vectors comparison with cosine similarity

similarity = cosine_similarity(vector)
similarity.shape

(4800, 4800)

In [53]:
final_df.reset_index(drop=True, inplace=True)
final_df

,movie_id,title_x,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4795,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4796,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4797,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4798,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4799,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [54]:
## Recommend 
## Recommendation while watching movie


final_df[final_df["title_x"] == "Titanic"]

    movie_id  title_x                                               tags
25       597  Titanic  84 year later, a 101-year-old woman name rose ...

In [55]:
# Now I want vector of 'Titanic' movie
# so we KNOW 'Titanic' movie is at '25' vector so we will simply do following step to get vector of 'titanic' movie

vector[25]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [56]:
# we get index number of titanic movie
final_df[final_df["title_x"] == "The Dark Knight Rises"].index

Index([3], dtype='int64')

In [57]:
# we only wanted titanic movie index number so we provided index[0]
# You can compare with above code output to better understand the idea
movie_index = final_df[final_df["title_x"] == "Avatar"].index[0]
movie_index

np.int64(0)

In [58]:
# we will save similarity of 'titanic' movie in distances. Folling is the similarity score of 'titanic' with other vectors.
distances = similarity[movie_index]
distances

array([1.        , 0.0836242 , 0.0862796 , ..., 0.04441156, 0.        ,
       0.        ], shape=(4800,))

In [59]:
# By applying enumarte function, it assigned each value index number
index_list = list(enumerate(distances))
index_list

[(0, np.float64(1.0000000000000004)),
 (1, np.float64(0.08362420100070908)),
 (2, np.float64(0.08627959628145762)),
 (3, np.float64(0.07299318686018119)),
 (4, np.float64(0.18685673434682065)),
 (5, np.float64(0.10795837927188262)),
 (6, np.float64(0.038277950117547636)),
 (7, np.float64(0.14484136487558028)),
 (8, np.float64(0.05847053462046861)),
 (9, np.float64(0.09656090991705352)),
 (10, np.float64(0.10256410256410257)),
 (11, np.float64(0.09443843292997713)),
 (12, np.float64(0.08920515501750789)),
 (13, np.float64(0.044844852933087494)),
 (14, np.float64(0.12820512820512822)),
 (15, np.float64(0.06201736729460422)),
 (16, np.float64(0.07692307692307693)),
 (17, np.float64(0.13592873654160803)),
 (18, np.float64(0.09435641951204965)),
 (19, np.float64(0.0826898230594723)),
 (20, np.float64(0.057289189923154626)),
 (21, np.float64(0.11149893466761211)),
 (22, np.float64(0.06677805632941779)),
 (23, np.float64(0.08770580193070292)),
 (24, np.float64(0.053376051268362375)),
 (25, np.float64(0.033757978902788886)),
 (26, np.float64(0.15191090506255)),
 (27, np.float64(0.19258222162991087)),
 (28, np.float64(0.11503946170861017)),
 (29, np.float64(0.06419407387663695)),
 (30, np.float64(0.06661733875264912)),
 (31, np.float64(0.15701857325533194)),
 (32, np.float64(0.08483796839677037)),
 (33, np.float64(0.09805806756909202)),
 (34, np.float64(0.0)),
 (35, np.float64(0.10016708449412667)),
 (36, np.float64(0.17093520167692652)),
 (37, np.float64(0.07897471897389846)),
 (38, np.float64(0.08006407690254357)),
 (39, np.float64(0.07692307692307693)),
 (40, np.float64(0.075955452531275)),
 (41, np.float64(0.16526725762745997)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0888231183368655)),
 (44, np.float64(0.03413943709994594)),
 (45, np.float64(0.08134518347820842)),
 (46, np.float64(0.13937366833451514)),
 (47, np.float64(0.19277164398874672)),
 (48, np.float64(0.084103426706236)),
 (49, np.float64(0.05847053462046861)),
 (50, np.float64(0.11322770341445958)),
 (51, np.float64(0.07884165279854434)),
 (52, np.float64(0.14651588715165131)),
 (53, np.float64(0.042796049251091296)),
 (54, np.float64(0.030816677568068284)),
 (55, np.float64(0.0711680683578165)),
 (56, np.float64(0.13655774839978377)),
 (57, np.float64(0.02387049580131443)),
 (58, np.float64(0.06726727939963124)),
 (59, np.float64(0.07161148740394328)),
 (60, np.float64(0.01813094310734737)),
 (61, np.float64(0.22880215766121476)),
 (62, np.float64(0.0826898230594723)),
 (63, np.float64(0.08006407690254357)),
 (64, np.float64(0.02973505167250263)),
 (65, np.float64(0.019277164398874672)),
 (66, np.float64(0.022205779584216375)),
 (67, np.float64(0.15794943794779692)),
 (68, np.float64(0.12104550653376046)),
 (69, np.float64(0.02623641899418197)),
 (70, np.float64(0.075955452531275)),
 (71, np.float64(0.07325794357582566)),
 (72, np.float64(0.13533299049019168)),
 (73, np.float64(0.033389028164708894)),
 (74, np.float64(0.20180183819889372)),
 (75, np.float64(0.10256410256410257)),
 (76, np.float64(0.07082882469748285)),
 (77, np.float64(0.013937366833451514)),
 (78, np.float64(0.05063696835418333)),
 (79, np.float64(0.06201736729460422)),
 (80, np.float64(0.04981354813867179)),
 (81, np.float64(0.10878565864408421)),
 (82, np.float64(0.07502344849205331)),
 (83, np.float64(0.177646236673731)),
 (84, np.float64(0.12201777521731262)),
 (85, np.float64(0.11265439490322912)),
 (86, np.float64(0.06933752452815364)),
 (87, np.float64(0.10826639239215334)),
 (88, np.float64(0.08920515501750789)),
 (89, np.float64(0.05661385170722979)),
 (90, np.float64(0.06163335513613657)),
 (91, np.float64(0.16724840200141816)),
 (92, np.float64(0.06150692760785472)),
 (93, np.float64(0.07007127538005775)),
 (94, np.float64(0.1849000654084097)),
 (95, np.float64(0.1401425507601155)),
 (96, np.float64(0.07692307692307693)),
 (97, np.float64(0.06862635163075162)),
 (98, np.float64(0.07502344849205331)),
 (99, np.float64(0.026688025634181187)),
 (100, np.float64(0.06827887419989188)),
 (101, np.float64(0.075955452531275)),
 (102, np.float64(0.12301385521570944)),
 (103, np.float64(0.07884165279854434)),
 (104, np.float64(0.055749467333806056)),
 (105, np.float64(0.10241831129983782)),
 (106, np.float64(0.06100888760865631)),
 (107, np.float64(0.06100888760865631)),
 (108, np.float64(0.14322297480788657)),
 (109, np.float64(0.06405126152203486)),
 (110, np.float64(0.044844852933087494)),
 (111, np.float64(0.14824986333222023)),
 (112, np.float64(0.07692307692307693)),
 (113, np.float64(0.042796049251091296)),
 (114, np.float64(0.04529108136578383)),
 (115, np.float64(0.04358136336404089)),
 (116, np.float64(0.04721921646498856)),
 (117, np.float64(0.05947010334500526)),
 (118, np.float64(0.03320903209244786)),
 (119, np.float64(0.04318335170875305)),
 (120, np.float64(0.0)),
 (121, np.float64(0.11149893466761211)),
 (122, np.float64(0.11503946170861017)),
 (123, np.float64(0.10997646755364592)),
 (124, np.float64(0.06661733875264912)),
 (125, np.float64(0.07525322988306804)),
 (126, np.float64(0.12503908082008885)),
 (127, np.float64(0.14504754485877894)),
 (128, np.float64(0.0)),
 (129, np.float64(0.08483796839677037)),
 (130, np.float64(0.026688025634181187)),
 (131, np.float64(0.10390486669322622)),
 (132, np.float64(0.04441155916843275)),
 (133, np.float64(0.02830692585361489)),
 (134, np.float64(0.12810252304406972)),
 (135, np.float64(0.0)),
 (136, np.float64(0.023112508176051216)),
 (137, np.float64(0.0296077061122885)),
 (138, np.float64(0.12659242088545833)),
 (139, np.float64(0.1191687183448436)),
 (140, np.float64(0.044844852933087494)),
 (141, np.float64(0.08627959628145762)),
 (142, np.float64(0.08238525545716345)),
 (143, np.float64(0.08559209850218259)),
 (144, np.float64(0.04941662111074008)),
 (145, np.float64(0.019138975058773818)),
 (146, np.float64(0.016093484986175587)),
 (147, np.float64(0.05492350363810897)),
 (148, np.float64(0.09607689228305229)),
 (149, np.float64(0.15421731519099738)),
 (150, np.float64(0.16641005886756868)),
 (151, np.float64(0.20483662259967564)),
 (152, np.float64(0.08238525545716345)),
 (153, np.float64(0.07767356373806174)),
 (154, np.float64(0.06052275326688024)),
 (155, np.float64(0.020174251088960076)),
 (156, np.float64(0.0595843591724218)),
 (157, np.float64(0.10241831129983782)),
 (158, np.float64(0.1319717610643751)),
 (159, np.float64(0.06405126152203486)),
 (160, np.float64(0.11561170597113389)),
 (161, np.float64(0.03140371465106639)),
 (162, np.float64(0.033389028164708894)),
 (163, np.float64(0.050015632328035534)),
 (164, np.float64(0.07897471897389846)),
 (165, np.float64(0.04575090108716775)),
 (166, np.float64(0.1235415527768502)),
 (167, np.float64(0.08920515501750789)),
 (168, np.float64(0.17295817388759027)),
 (169, np.float64(0.08716272672808179)),
 (170, np.float64(0.105129283382795)),
 (171, np.float64(0.022422426466543747)),
 (172, np.float64(0.20483662259967564)),
 (173, np.float64(0.022875450543583874)),
 (174, np.float64(0.10127393670836667)),
 (175, np.float64(0.07082882469748285)),
 (176, np.float64(0.02875986542715254)),
 (177, np.float64(0.0)),
 (178, np.float64(0.024419314525275217)),
 (179, np.float64(0.07161148740394328)),
 (180, np.float64(0.021790681682020446)),
 (181, np.float64(0.04441155916843275)),
 (182, np.float64(0.11556254088025608)),
 (183, np.float64(0.06947334742918748)),
 (184, np.float64(0.17295817388759027)),
 (185, np.float64(0.05063696835418333)),
 (186, np.float64(0.05868830272850543)),
 (187, np.float64(0.1500468969841066)),
 (188, np.float64(0.021995293510729184)),
 (189, np.float64(0.11322770341445959)),
 (190, np.float64(0.084103426706236)),
 (191, np.float64(0.04828045495852676)),
 (192, np.float64(0.04671418358670517)),
 (193, np.float64(0.07813453848974924)),
 (194, np.float64(0.0)),
 (195, np.float64(0.05947010334500526)),
 (196, np.float64(0.05128205128205128)),
 (197, np.float64(0.03673591791853225)),
 (198, np.float64(0.05661385170722978)),
 (199, np.float64(0.08338763984501667)),
 (200, np.float64(0.10741723110591493)),
 (201, np.float64(0.0)),
 (202, np.float64(0.030816677568068284)),
 (203, np.float64(0.08362420100070908)),
 (204, np.float64(0.04883862905055043)),
 (205, np.float64(0.07548513560963972)),
 (206, np.float64(0.10948978029027179)),
 (207, np.float64(0.09883324222148016)),
 (208, np.float64(0.12326671027227314)),
 (209, np.float64(0.06677805632941779)),
 (210, np.float64(0.07502344849205331)),
 (211, np.float64(0.02414022747926338)),
 (212, np.float64(0.06598588053218755)),
 (213, np.float64(0.05868830272850543)),
 (214, np.float64(0.0)),
 (215, np.float64(0.06598588053218755)),
 (216, np.float64(0.06405126152203486)),
 (217, np.float64(0.084103426706236)),
 (218, np.float64(0.03883678186903087)),
 (219, np.float64(0.09078412990032035)),
 (220, np.float64(0.17841031003501578)),
 (221, np.float64(0.04671418358670517)),
 (222, np.float64(0.07884165279854434)),
 (223, np.float64(0.10256410256410257)),
 (224, np.float64(0.06004805767690767)),
 (225, np.float64(0.04622501635210243)),
 (226, np.float64(0.03026137663344012)),
 (227, np.float64(0.081199794294115)),
 (228, np.float64(0.10895340841010223)),
 (229, np.float64(0.10545808983558425)),
 (230, np.float64(0.09065471553673685)),
 (231, np.float64(0.0)),
 (232, np.float64(0.11149893466761211)),
 (233, np.float64(0.10241831129983782)),
 (234, np.float64(0.08483796839677037)),
 (235, np.float64(0.07502344849205331)),
 (236, np.float64(0.11503946170861017)),
 (237, np.float64(0.06405126152203486)),
 (238, np.float64(0.10948978029027179)),
 (239, np.float64(0.0900791242218625)),
 (240, np.float64(0.04671418358670517)),
 (241, np.float64(0.07792865001991967)),
 (242, np.float64(0.08006407690254357)),
 (243, np.float64(0.09245003270420486)),
 (244, np.float64(0.09078412990032035)),
 (245, np.float64(0.08006407690254357)),
 (246, np.float64(0.07548513560963972)),
 (247, np.float64(0.0)),
 (248, np.float64(0.04441155916843275)),
 (249, np.float64(0.13655774839978377)),
 (250, np.float64(0.0)),
 (251, np.float64(0.04134491152973615)),
 (252, np.float64(0.02001601922563589)),
 (253, np.float64(0.06201736729460422)),
 (254, np.float64(0.06793662204867575)),
 (255, np.float64(0.0)),
 (256, np.float64(0.11020775375559674)),
 (257, np.float64(0.053376051268362375)),
 (258, np.float64(0.01736833685729687)),
 (259, np.float64(0.06052275326688024)),
 (260, np.float64(0.2013190579900678)),
 (261, np.float64(0.02360960823249428)),
 (262, np.float64(0.10604746049596296)),
 (263, np.float64(0.09607689228305229)),
 (264, np.float64(0.0)),
 (265, np.float64(0.027066598098038335)),
 (266, np.float64(0.09767725810110088)),
 (267, np.float64(0.06537204504606135)),
 (268, np.float64(0.05195243334661311)),
 (269, np.float64(0.029235267310234306)),
 (270, np.float64(0.08798117404291673)),
 (271, np.float64(0.07082882469748285)),
 (272, np.float64(0.027874733666903028)),
 (273, np.float64(0.020846909961254163)),
 (274, np.float64(0.08833906504195108)),
 (275, np.float64(0.1437993271357627)),
 (276, np.float64(0.06280742930213278)),
 (277, np.float64(0.05272904491779212)),
 (278, np.float64(0.11678545896676293)),
 (279, np.float64(0.06933752452815364)),
 (280, np.float64(0.0)),
 (281, np.float64(0.06477502756312957)),
 (282, np.float64(0.022205779584216375)),
 (283, np.float64(0.027461751819054483)),
 (284, np.float64(0.01813094310734737)),
 (285, np.float64(0.019277164398874672)),
 (286, np.float64(0.07655590023509527)),
 (287, np.float64(0.025976216673306556)),
 (288, np.float64(0.027066598098038335)),
 (289, np.float64(0.04529108136578383)),
 (290, np.float64(0.06280742930213278)),
 (291, np.float64(0.04883862905055043)),
 (292, np.float64(0.08627959628145762)),
 (293, np.float64(0.029235267310234306)),
 (294, np.float64(0.14153462926807445)),
 (295, np.float64(0.10390486669322622)),
 (296, np.float64(0.038277950117547636)),
 (297, np.float64(0.04399058702145837)),
 (298, np.float64(0.0)),
 (299, np.float64(0.05868830272850543)),
 (300, np.float64(0.16898159235484364)),
 (301, np.float64(0.09245003270420485)),
 (302, np.float64(0.06933752452815364)),
 (303, np.float64(0.027461751819054483)),
 (304, np.float64(0.06494054168326639)),
 (305, np.float64(0.1876221896512875)),
 (306, np.float64(0.07897471897389846)),
 (307, np.float64(0.10736246830291345)),
 (308, np.float64(0.06677805632941779)),
 (309, np.float64(0.06163335513613657)),
 (310, np.float64(0.03039738350583688)),
 (311, np.float64(0.14824986333222023)),
 (312, np.float64(0.0954819832052577)),
 (313, np.float64(0.05413319619607667)),
 (314, np.float64(0.0)),
 (315, np.float64(0.08238525545716345)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.10016708449412667)),
 (320, np.float64(0.030816677568068284)),
 (321, np.float64(0.0)),
 (322, np.float64(0.20780973338645242)),
 (323, np.float64(0.029235267310234306)),
 (324, np.float64(0.02387049580131443)),
 (325, np.float64(0.09805806756909202)),
 (326, np.float64(0.055749467333806056)),
 (327, np.float64(0.027066598098038335)),
 (328, np.float64(0.027066598098038335)),
 (329, np.float64(0.07897471897389846)),
 (330, np.float64(0.10003126465607108)),
 (331, np.float64(0.0888231183368655)),
 (332, np.float64(0.10675210253672475)),
 (333, np.float64(0.02414022747926338)),
 (334, np.float64(0.0954819832052577)),
 (335, np.float64(0.04575090108716775)),
 (336, np.float64(0.06827887419989188)),
 (337, np.float64(0.044844852933087494)),
 (338, np.float64(0.0)),
 (339, np.float64(0.04828045495852676)),
 (340, np.float64(0.04941662111074008)),
 (341, np.float64(0.08238525545716345)),
 (342, np.float64(0.1611258466588724)),
 (343, np.float64(0.019003715589632167)),
 (344, np.float64(0.02973505167250263)),
 (345, np.float64(0.022875450543583874)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06052275326688024)),
 (349, np.float64(0.07792865001991967)),
 (350, np.float64(0.04828045495852676)),
 (351, np.float64(0.0)),
 (352, np.float64(0.027066598098038335)),
 (353, np.float64(0.04169381992250833)),
 (354, np.float64(0.021591675854376526)),
 (355, np.float64(0.03626188621469474)),
 (356, np.float64(0.09078412990032035)),
 (357, np.float64(0.0)),
 (358, np.float64(0.05947010334500526)),
 (359, np.float64(0.030816677568068284)),
 (360, np.float64(0.020846909961254163)),
 (361, np.float64(0.07502344849205331)),
 (362, np.float64(0.09607689228305229)),
 (363, np.float64(0.09855206599818042)),
 (364, np.float64(0.023112508176051216)),
 (365, np.float64(0.07502344849205331)),
 (366, np.float64(0.055749467333806056)),
 (367, np.float64(0.0)),
 (368, np.float64(0.12810252304406972)),
 (369, np.float64(0.12503908082008885)),
 (370, np.float64(0.050015632328035534)),
 (371, np.float64(0.0954819832052577)),
 (372, np.float64(0.04721921646498856)),
 (373, np.float64(0.17471413945365305)),
 (374, np.float64(0.037483165639491674)),
 (375, np.float64(0.06100888760865631)),
 (376, np.float64(0.04622501635210243)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.04954787398762881)),
 (380, np.float64(0.05128205128205128)),
 (381, np.float64(0.0826898230594723)),
 (382, np.float64(0.0)),
 (383, np.float64(0.042796049251091296)),
 (384, np.float64(0.02875986542715254)),
 (385, np.float64(0.0)),
 (386, np.float64(0.021790681682020446)),
 (387, np.float64(0.02360960823249428)),
 (388, np.float64(0.0)),
 (389, np.float64(0.08920515501750789)),
 (390, np.float64(0.025976216673306556)),
 (391, np.float64(0.055470019622522904)),
 (392, np.float64(0.02973505167250263)),
 (393, np.float64(0.0)),
 (394, np.float64(0.02470831055537004)),
 (395, np.float64(0.05128205128205128)),
 (396, np.float64(0.04358136336404089)),
 (397, np.float64(0.05128205128205128)),
 (398, np.float64(0.0)),
 (399, np.float64(0.023357091793352585)),
 (400, np.float64(0.08920515501750789)),
 (401, np.float64(0.03202563076101743)),
 (402, np.float64(0.07792865001991967)),
 (403, np.float64(0.08200923681047297)),
 (404, np.float64(0.06052275326688024)),
 (405, np.float64(0.05492350363810897)),
 (406, np.float64(0.02050230920261824)),
 (407, np.float64(0.021025856676559)),
 (408, np.float64(0.03202563076101743)),
 (409, np.float64(0.0)),
 (410, np.float64(0.09656090991705352)),
 (411, np.float64(0.05195243334661311)),
 (412, np.float64(0.09443843292997713)),
 (413, np.float64(0.14153462926807445)),
 (414, np.float64(0.029235267310234306)),
 (415, np.float64(0.05272904491779212)),
 (416, np.float64(0.05063696835418333)),
 (417, np.float64(0.03580574370197164)),
 (418, np.float64(0.03494282789073061)),
 (419, np.float64(0.06862635163075162)),
 (420, np.float64(0.10997646755364592)),
 (421, np.float64(0.023112508176051216)),
 (422, np.float64(0.11503946170861017)),
 (423, np.float64(0.04100461840523648)),
 (424, np.float64(0.037229039552497)),
 (425, np.float64(0.063077570029677)),
 (426, np.float64(0.05304958917673055)),
 (427, np.float64(0.02632490632463282)),
 (428, np.float64(0.055470019622522904)),
 (429, np.float64(0.0)),
 (430, np.float64(0.050015632328035534)),
 (431, np.float64(0.02387049580131443)),
 (432, np.float64(0.11211213233271873)),
 (433, np.float64(0.030816677568068284)),
 (434, np.float64(0.0)),
 (435, np.float64(0.03494282789073061)),
 (436, np.float64(0.0)),
 (437, np.float64(0.02564102564102564)),
 (438, np.float64(0.1207011373963169)),
 (439, np.float64(0.025976216673306556)),
 (440, np.float64(0.024419314525275217)),
 (441, np.float64(0.05661385170722978)),
 (442, np.float64(0.04529108136578383)),
 (443, np.float64(0.06362847629757777)),
 (444, np.float64(0.0)),
 (445, np.float64(0.09883324222148016)),
 (446, np.float64(0.023112508176051216)),
 (447, np.float64(0.06362847629757777)),
 (448, np.float64(0.021025856676559)),
 (449, np.float64(0.10826639239215334)),
 (450, np.float64(0.021025856676559)),
 (451, np.float64(0.02470831055537004)),
 (452, np.float64(0.03026137663344012)),
 (453, np.float64(0.02414022747926338)),
 (454, np.float64(0.11322770341445958)),
 (455, np.float64(0.06052275326688023)),
 (456, np.float64(0.042796049251091296)),
 (457, np.float64(0.08770580193070292)),
 (458, np.float64(0.042796049251091296)),
 (459, np.float64(0.03413943709994594)),
 (460, np.float64(0.02414022747926338)),
 (461, np.float64(0.13937366833451514)),
 (462, np.float64(0.03171009961029961)),
 (463, np.float64(0.03202563076101743)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.14322297480788657)),
 (467, np.float64(0.10423454980627084)),
 (468, np.float64(0.027066598098038335)),
 (469, np.float64(0.05913123959890826)),
 (470, np.float64(0.044844852933087494)),
 (471, np.float64(0.063077570029677)),
 (472, np.float64(0.10675210253672475)),
 (473, np.float64(0.09245003270420486)),
 (474, np.float64(0.0)),
 (475, np.float64(0.06419407387663695)),
 (476, np.float64(0.13355611265883557)),
 (477, np.float64(0.0)),
 (478, np.float64(0.053708615552957466)),
 (479, np.float64(0.08684168428648435)),
 (480, np.float64(0.09656090991705352)),
 (481, np.float64(0.0)),
 (482, np.float64(0.021591675854376526)),
 (483, np.float64(0.12561485860426555)),
 (484, np.float64(0.03026137663344012)),
 (485, np.float64(0.05264981264926564)),
 (486, np.float64(0.07888947910127371)),
 (487, np.float64(0.12561485860426555)),
 (488, np.float64(0.06571520774535256)),
 (489, np.float64(0.0)),
 (490, np.float64(0.13977131156292244)),
 (491, np.float64(0.09930726528736966)),
 (492, np.float64(0.07502344849205331)),
 (493, np.float64(0.03039738350583688)),
 (494, np.float64(0.0)),
 (495, np.float64(0.1884222879063983)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.06677805632941779)),
 (499, np.float64(0.0)),
 (500, np.float64(0.025976216673306556)),
 (501, np.float64(0.0806970043558403)),
 (502, np.float64(0.1319717610643751)),
 (503, np.float64(0.07412493166611012)),
 (504, np.float64(0.0)),
 (505, np.float64(0.13355611265883557)),
 (506, np.float64(0.03413943709994594)),
 (507, np.float64(0.2545139051903111)),
 (508, np.float64(0.10127393670836667)),

- With this, we have synced index number in following variables 'distances, final_df, vector'

In [60]:
# So now we wanted top 10 similar movies
# we will sort, then get 10 similar movies
# Sort function with 'reverse=True' will sort values in descending order on basis of 'index_list'. we use'key= lambda x:x[1]' to achieve this

similar_movie = sorted(index_list, reverse=True, key= lambda x:x[1])
similar_movie

[(0, np.float64(1.0000000000000004)),
 (1213, np.float64(0.283069258536149)),
 (2403, np.float64(0.26554250227189713)),
 (3723, np.float64(0.25715142542972574)),
 (507, np.float64(0.2545139051903111)),
 (539, np.float64(0.2471557663714903)),
 (582, np.float64(0.24194822861802104)),
 (1201, np.float64(0.24140227479263374)),
 (1191, np.float64(0.23372319715296228)),
 (61, np.float64(0.22880215766121476)),
 (778, np.float64(0.22875450543583872)),
 (4041, np.float64(0.22489899383695006)),
 (1914, np.float64(0.22237479499833035)),
 (2780, np.float64(0.21571674297647797)),
 (972, np.float64(0.20814536170751838)),
 (322, np.float64(0.20780973338645242)),
 (151, np.float64(0.20483662259967564)),
 (172, np.float64(0.20483662259967564)),
 (2327, np.float64(0.2038098661460272)),
 (74, np.float64(0.20180183819889372)),
 (3603, np.float64(0.20174251088960077)),
 (260, np.float64(0.2013190579900678)),
 (577, np.float64(0.20131905799006777)),
 (4185, np.float64(0.20033416898825335)),
 (1086, np.float64(0.1981740732880975)),
 (3667, np.float64(0.19535451620220176)),
 (1438, np.float64(0.19418390934515434)),
 (47, np.float64(0.19277164398874672)),
 (27, np.float64(0.19258222162991087)),
 (2966, np.float64(0.19003715589632172)),
 (942, np.float64(0.18887686585995425)),
 (1198, np.float64(0.18842228790639834)),
 (495, np.float64(0.1884222879063983)),
 (305, np.float64(0.1876221896512875)),
 (4, np.float64(0.18685673434682065)),
 (4399, np.float64(0.18490006540840973)),
 (94, np.float64(0.1849000654084097)),
 (2994, np.float64(0.18367958959266126)),
 (3322, np.float64(0.18367958959266126)),
 (1272, np.float64(0.1815682598006407)),
 (1326, np.float64(0.1815682598006407)),
 (1318, np.float64(0.17902871850985821)),
 (220, np.float64(0.17841031003501578)),
 (83, np.float64(0.177646236673731)),
 (1068, np.float64(0.17722938923964168)),
 (3992, np.float64(0.1754116038614058)),
 (2198, np.float64(0.1750547131481244)),
 (4330, np.float64(0.17505471314812437)),
 (373, np.float64(0.17471413945365305)),
 (168, np.float64(0.17295817388759027)),
 (184, np.float64(0.17295817388759027)),
 (838, np.float64(0.17103344030668954)),
 (36, np.float64(0.17093520167692652)),
 (931, np.float64(0.16984155512168933)),
 (300, np.float64(0.16898159235484364)),
 (3157, np.float64(0.16820685341247196)),
 (91, np.float64(0.16724840200141816)),
 (1976, np.float64(0.16724840200141816)),
 (529, np.float64(0.167093470609201)),
 (1825, np.float64(0.167093470609201)),
 (150, np.float64(0.16641005886756868)),
 (661, np.float64(0.1653796461189446)),
 (41, np.float64(0.16526725762745997)),
 (3533, np.float64(0.16526725762745997)),
 (342, np.float64(0.1611258466588724)),
 (595, np.float64(0.1585187847802434)),
 (1531, np.float64(0.1585187847802434)),
 (67, np.float64(0.15794943794779692)),
 (31, np.float64(0.15701857325533194)),
 (2509, np.float64(0.15701857325533194)),
 (1175, np.float64(0.15585730003983933)),
 (4003, np.float64(0.15534712747612348)),
 (149, np.float64(0.15421731519099738)),
 (581, np.float64(0.15408338784034142)),
 (2725, np.float64(0.15408338784034142)),
 (26, np.float64(0.15191090506255)),
 (1377, np.float64(0.15191090506255)),
 (187, np.float64(0.1500468969841066)),
 (111, np.float64(0.14824986333222023)),
 (311, np.float64(0.14824986333222023)),
 (513, np.float64(0.14824986333222023)),
 (1341, np.float64(0.14824986333222023)),
 (52, np.float64(0.14651588715165131)),
 (2069, np.float64(0.14617633655117152)),
 (127, np.float64(0.14504754485877894)),
 (7, np.float64(0.14484136487558028)),
 (2754, np.float64(0.1447071903540765)),
 (275, np.float64(0.1437993271357627)),
 (579, np.float64(0.1437993271357627)),
 (108, np.float64(0.14322297480788657)),
 (466, np.float64(0.14322297480788657)),
 (1294, np.float64(0.14322297480788657)),
 (1352, np.float64(0.14322297480788657)),
 (1473, np.float64(0.14235407108686474)),
 (1932, np.float64(0.1416576493949657)),
 (3349, np.float64(0.14153462926807447)),
 (294, np.float64(0.14153462926807445)),
 (413, np.float64(0.14153462926807445)),
 (568, np.float64(0.14153462926807445)),
 (95, np.float64(0.1401425507601155)),
 (1053, np.float64(0.1401425507601155)),
 (1270, np.float64(0.1401425507601155)),
 (1390, np.float64(0.14011213457945124)),
 (1959, np.float64(0.14011213457945124)),
 (490, np.float64(0.13977131156292244)),
 (1482, np.float64(0.13977131156292244)),
 (46, np.float64(0.13937366833451514)),
 (461, np.float64(0.13937366833451514)),
 (2490, np.float64(0.13937366833451514)),
 (2163, np.float64(0.1373087590952724)),
 (3404, np.float64(0.1373087590952724)),
 (56, np.float64(0.13655774839978377)),
 (249, np.float64(0.13655774839978377)),
 (1324, np.float64(0.13655774839978377)),
 (3774, np.float64(0.13655774839978377)),
 (17, np.float64(0.13592873654160803)),
 (72, np.float64(0.13533299049019168)),
 (859, np.float64(0.13533299049019168)),
 (4072, np.float64(0.13533299049019168)),
 (4532, np.float64(0.1345345587992625)),
 (476, np.float64(0.13355611265883557)),
 (505, np.float64(0.13355611265883557)),
 (935, np.float64(0.13355611265883557)),
 (3975, np.float64(0.13355611265883557)),
 (843, np.float64(0.13344012817090595)),
 (1802, np.float64(0.13344012817090595)),
 (4342, np.float64(0.13323467750529824)),
 (1319, np.float64(0.13302600912742518)),
 (158, np.float64(0.1319717610643751)),
 (502, np.float64(0.1319717610643751)),
 (777, np.float64(0.1319717610643751)),
 (1554, np.float64(0.1316245316231641)),
 (668, np.float64(0.1307440900921227)),
 (1367, np.float64(0.1307440900921227)),
 (2372, np.float64(0.1307440900921227)),
 (2578, np.float64(0.1307440900921227)),
 (1012, np.float64(0.12988108336653278)),
 (2127, np.float64(0.1283881477532739)),
 (14, np.float64(0.12820512820512822)),
 (2175, np.float64(0.12820512820512822)),
 (3617, np.float64(0.12820512820512822)),
 (134, np.float64(0.12810252304406972)),
 (368, np.float64(0.12810252304406972)),
 (1768, np.float64(0.12810252304406972)),
 (2867, np.float64(0.12725695259515554)),
 (138, np.float64(0.12659242088545833)),
 (1083, np.float64(0.12659242088545833)),
 (2680, np.float64(0.12659242088545833)),
 (4223, np.float64(0.12659242088545833)),
 (483, np.float64(0.12561485860426555)),
 (487, np.float64(0.12561485860426555)),
 (773, np.float64(0.12561485860426555)),
 (1155, np.float64(0.12561485860426555)),
 (1735, np.float64(0.125081459767525)),
 (126, np.float64(0.12503908082008885)),
 (369, np.float64(0.12503908082008885)),
 (937, np.float64(0.12503908082008883)),
 (2474, np.float64(0.12403473458920844)),
 (166, np.float64(0.1235415527768502)),
 (754, np.float64(0.1235415527768502)),
 (2444, np.float64(0.1235415527768502)),
 (3623, np.float64(0.1235415527768502)),
 (208, np.float64(0.12326671027227314)),
 (1093, np.float64(0.12326671027227314)),
 (2054, np.float64(0.12326671027227314)),
 (2965, np.float64(0.12326671027227314)),
 (102, np.float64(0.12301385521570944)),
 (84, np.float64(0.12201777521731262)),
 (1872, np.float64(0.12201777521731262)),
 (68, np.float64(0.12104550653376046)),
 (438, np.float64(0.1207011373963169)),
 (2325, np.float64(0.12009611535381534)),
 (2668, np.float64(0.12009611535381534)),
 (2783, np.float64(0.12009611535381534)),
 (3078, np.float64(0.12009611535381534)),
 (549, np.float64(0.11935247900657213)),
 (1296, np.float64(0.11935247900657213)),
 (2278, np.float64(0.11935247900657213)),
 (139, np.float64(0.1191687183448436)),
 (781, np.float64(0.11894020669001053)),
 (1001, np.float64(0.11894020669001053)),
 (1271, np.float64(0.11894020669001053)),
 (1652, np.float64(0.11894020669001053)),
 (2646, np.float64(0.11894020669001053)),
 (3371, np.float64(0.11894020669001053)),
 (3729, np.float64(0.11894020669001053)),
 (4667, np.float64(0.11894020669001053)),
 (999, np.float64(0.1182624791978165)),
 (870, np.float64(0.1180480411624714)),
 (900, np.float64(0.1180480411624714)),
 (1044, np.float64(0.11694106924093722)),
 (1298, np.float64(0.11694106924093722)),
 (1827, np.float64(0.11694106924093722)),
 (2735, np.float64(0.11694106924093722)),
 (278, np.float64(0.11678545896676293)),
 (557, np.float64(0.11678545896676293)),
 (3230, np.float64(0.11678545896676293)),
 (1667, np.float64(0.1165103456070926)),
 (1709, np.float64(0.1165103456070926)),
 (3714, np.float64(0.1165103456070926)),
 (3993, np.float64(0.1165103456070926)),
 (160, np.float64(0.11561170597113389)),
 (182, np.float64(0.11556254088025608)),
 (1611, np.float64(0.11556254088025608)),
 (2541, np.float64(0.11556254088025608)),
 (28, np.float64(0.11503946170861017)),
 (122, np.float64(0.11503946170861017)),
 (236, np.float64(0.11503946170861017)),
 (422, np.float64(0.11503946170861017)),
 (678, np.float64(0.11503946170861017)),
 (589, np.float64(0.11483385035264292)),
 (1491, np.float64(0.114022293537793)),
 (3207, np.float64(0.11357879791107993)),
 (189, np.float64(0.11322770341445959)),
 (1569, np.float64(0.11322770341445959)),
 (50, np.float64(0.11322770341445958)),
 (454, np.float64(0.11322770341445958)),
 (85, np.float64(0.11265439490322912)),
 (432, np.float64(0.11211213233271873)),
 (1217, np.float64(0.11211213233271873)),
 (1412, np.float64(0.11211213233271873)),
 (21, np.float64(0.11149893466761211)),
 (121, np.float64(0.11149893466761211)),
 (232, np.float64(0.11149893466761211)),
 (1610, np.float64(0.11149893466761211)),
 (536, np.float64(0.11102889792108188)),
 (889, np.float64(0.11098534863604863)),
 (256, np.float64(0.11020775375559674)),
 (808, np.float64(0.11020775375559674)),
 (1345, np.float64(0.11020775375559674)),
 (2317, np.float64(0.11020775375559674)),
 (3142, np.float64(0.11020775375559674)),
 (1506, np.float64(0.10997646755364593)),
 (123, np.float64(0.10997646755364592)),
 (420, np.float64(0.10997646755364592)),
 (2366, np.float64(0.10997646755364592)),
 (3003, np.float64(0.10984700727621793)),
 (4462, np.float64(0.10984700727621793)),
 (206, np.float64(0.10948978029027179)),
 (238, np.float64(0.10948978029027179)),
 (228, np.float64(0.10895340841010223)),
 (3304, np.float64(0.10895340841010223)),
 (81, np.float64(0.10878565864408421)),
 (1568, np.float64(0.10878565864408421)),
 (3423, np.float64(0.10826639239215335)),
 (87, np.float64(0.10826639239215334)),
 (449, np.float64(0.10826639239215334)),
 (1028, np.float64(0.10826639239215334)),
 (1939, np.float64(0.10826639239215334)),
 (2066, np.float64(0.10826639239215334)),
 (5, np.float64(0.10795837927188262)),
 (692, np.float64(0.10795837927188262)),
 (740, np.float64(0.1079583792718826)),
 (200, np.float64(0.10741723110591493)),
 (653, np.float64(0.10741723110591493)),
 (1495, np.float64(0.10741723110591493)),
 (1518, np.float64(0.10741723110591493)),
 (307, np.float64(0.10736246830291345)),
 (3088, np.float64(0.10699012312772824)),
 (3625, np.float64(0.10699012312772824)),
 (332, np.float64(0.10675210253672475)),
 (472, np.float64(0.10675210253672475)),
 (786, np.float64(0.10675210253672475)),
 (3493, np.float64(0.10675210253672475)),
 (4771, np.float64(0.10675210253672475)),
 (262, np.float64(0.10604746049596296)),
 (541, np.float64(0.10604746049596296)),
 (572, np.float64(0.10604746049596296)),
 (229, np.float64(0.10545808983558425)),
 (1234, np.float64(0.10529962529853128)),
 (170, np.float64(0.105129283382795)),
 (627, np.float64(0.10482848367219183)),
 (939, np.float64(0.10482848367219183)),
 (1739, np.float64(0.10482848367219183)),
 (2155, np.float64(0.10482848367219183)),
 (2515, np.float64(0.10482848367219183)),
 (2628, np.float64(0.10482848367219183)),
 (4128, np.float64(0.10482848367219183)),
 (467, np.float64(0.10423454980627084)),
 (1490, np.float64(0.10423454980627084)),
 (131, np.float64(0.10390486669322622)),
 (295, np.float64(0.10390486669322622)),
 (687, np.float64(0.10390486669322622)),
 (814, np.float64(0.10390486669322622)),
 (1034, np.float64(0.10390486669322622)),
 (1765, np.float64(0.10390486669322622)),
 (3335, np.float64(0.10390486669322622)),
 (2492, np.float64(0.10336227882434038)),
 (10, np.float64(0.10256410256410257)),
 (75, np.float64(0.10256410256410257)),
 (223, np.float64(0.10256410256410257)),
 (643, np.float64(0.10256410256410257)),
 (1192, np.float64(0.10256410256410257)),
 (2811, np.float64(0.10256410256410257)),
 (3748, np.float64(0.10256410256410257)),
 (654, np.float64(0.1025115460130912)),
 (2100, np.float64(0.1025115460130912)),
 (2433, np.float64(0.1025115460130912)),
 (105, np.float64(0.10241831129983782)),
 (157, np.float64(0.10241831129983782)),
 (233, np.float64(0.10241831129983782)),
 (1163, np.float64(0.10241831129983782)),
 (2450, np.float64(0.10241831129983782)),
 (2756, np.float64(0.10241831129983782)),
 (3050, np.float64(0.10241831129983782)),
 (3616, np.float64(0.10241831129983782)),
 (3832, np.float64(0.10241831129983782)),
 (1449, np.float64(0.10168147934776052)),
 (174, np.float64(0.10127393670836667)),
 (508, np.float64(0.10127393670836667)),
 (1079, np.float64(0.10127393670836667)),
 (2142, np.float64(0.10127393670836667)),
 (3147, np.float64(0.10127393670836667)),
 (3629, np.float64(0.10127393670836667)),
 (3867, np.float64(0.10127393670836667)),
 (4090, np.float64(0.10127393670836667)),
 (35, np.float64(0.10016708449412667)),
 (319, np.float64(0.10016708449412667)),
 (624, np.float64(0.10016708449412667)),
 (1074, np.float64(0.10016708449412667)),
 (2047, np.float64(0.10016708449412667)),
 (3655, np.float64(0.10016708449412667)),
 (3947, np.float64(0.10016708449412667)),
 (3436, np.float64(0.10008009612817945)),
 (330, np.float64(0.10003126465607108)),
 (1291, np.float64(0.10003126465607107)),
 (491, np.float64(0.09930726528736966)),
 (1399, np.float64(0.09930726528736966)),
 (1433, np.float64(0.09930726528736966)),
 (207, np.float64(0.09883324222148016)),
 (445, np.float64(0.09883324222148016)),
 (985, np.float64(0.09883324222148016)),
 (1395, np.float64(0.09883324222148016)),
 (1608, np.float64(0.09883324222148016)),
 (2241, np.float64(0.09883324222148016)),
 (363, np.float64(0.09855206599818042)),
 (2093, np.float64(0.09855206599818042)),
 (33, np.float64(0.09805806756909202)),
 (325, np.float64(0.09805806756909202)),
 (715, np.float64(0.09805806756909202)),
 (878, np.float64(0.09805806756909202)),
 (1277, np.float64(0.09805806756909202)),
 (1878, np.float64(0.09805806756909202)),
 (2781, np.float64(0.09805806756909202)),
 (4011, np.float64(0.09805806756909202)),
 (4191, np.float64(0.09805806756909202)),
 (4325, np.float64(0.09805806756909202)),
 (4484, np.float64(0.09805806756909202)),
 (1769, np.float64(0.09781383788084239)),
 (266, np.float64(0.09767725810110088)),
 (510, np.float64(0.09767725810110088)),
 (3928, np.float64(0.09767725810110088)),
 (3776, np.float64(0.09767725810110087)),
 (9, np.float64(0.09656090991705352)),
 (410, np.float64(0.09656090991705352)),
 (480, np.float64(0.09656090991705352)),
 (535, np.float64(0.09656090991705352)),
 (898, np.float64(0.09656090991705352)),
 (1106, np.float64(0.09656090991705352)),
 (1817, np.float64(0.09656090991705352)),
 (2247, np.float64(0.09656090991705352)),
 (3615, np.float64(0.09656090991705352)),
 (148, np.float64(0.09607689228305229)),
 (263, np.float64(0.09607689228305229)),
 (362, np.float64(0.09607689228305229)),
 (1153, np.float64(0.09607689228305229)),
 (1936, np.float64(0.09607689228305229)),
 (2556, np.float64(0.09607689228305229)),
 (4249, np.float64(0.09607689228305229)),
 (4397, np.float64(0.09607689228305229)),
 (4466, np.float64(0.09607689228305229)),
 (312, np.float64(0.0954819832052577)),
 (334, np.float64(0.0954819832052577)),
 (371, np.float64(0.0954819832052577)),
 (2235, np.float64(0.0954819832052577)),
 (11, np.float64(0.09443843292997713)),
 (412, np.float64(0.09443843292997713)),
 (1990, np.float64(0.09443843292997713)),
 (2550, np.float64(0.09443843292997713)),
 (18, np.float64(0.09435641951204965)),
 (4539, np.float64(0.09435641951204965)),
 (791, np.float64(0.09421114395319916)),
 (1024, np.float64(0.09421114395319916)),
 (1721, np.float64(0.09421114395319916)),
 (4196, np.float64(0.09421114395319916)),
 (243, np.float64(0.09245003270420486)),
 (473, np.float64(0.09245003270420486)),
 (813, np.float64(0.09245003270420486)),
 (1273, np.float64(0.09245003270420486)),
 (1354, np.float64(0.09245003270420486)),
 (1686, np.float64(0.09245003270420486)),
 (2482, np.float64(0.09245003270420486)),
 (2586, np.float64(0.09245003270420486)),
 (2814, np.float64(0.09245003270420486)),
 (3713, np.float64(0.09245003270420486)),
 (4496, np.float64(0.09245003270420486)),
 (301, np.float64(0.09245003270420485)),
 (511, np.float64(0.09245003270420485)),
 (660, np.float64(0.09245003270420485)),
 (920, np.float64(0.09245003270420485)),
 (1567, np.float64(0.09245003270420485)),
 (1680, np.float64(0.09245003270420485)),
 (1715, np.float64(0.09245003270420485)),
 (2390, np.float64(0.09245003270420485)),
 (2639, np.float64(0.09245003270420485)),
 (3532, np.float64(0.09245003270420485)),
 (799, np.float64(0.09183979479633063)),
 (785, np.float64(0.09183979479633061)),
 (596, np.float64(0.0915018021743355)),
 (1440, np.float64(0.0915018021743355)),
 (1695, np.float64(0.0915018021743355)),
 (2644, np.float64(0.0915018021743355)),
 (219, np.float64(0.09078412990032035)),
 (244, np.float64(0.09078412990032035)),
 (356, np.float64(0.09078412990032035)),
 (977, np.float64(0.09078412990032035)),
 (1303, np.float64(0.09078412990032035)),
 (1750, np.float64(0.09078412990032035)),
 (2087, np.float64(0.09078412990032035)),
 (230, np.float64(0.09065471553673685)),
 (3402, np.float64(0.09058216273156766)),
 (239, np.float64(0.0900791242218625)),
 (2564, np.float64(0.0900791242218625)),
 (602, np.float64(0.08968970586617499)),
 (994, np.float64(0.08968970586617499)),
 (1230, np.float64(0.08968970586617499)),
 (1840, np.float64(0.08968970586617499)),
 (3874, np.float64(0.08968970586617499)),
 (12, np.float64(0.08920515501750789)),
 (88, np.float64(0.08920515501750789)),
 (167, np.float64(0.08920515501750789)),
 (389, np.float64(0.08920515501750789)),
 (400, np.float64(0.08920515501750789)),
 (564, np.float64(0.08920515501750789)),
 (1468, np.float64(0.08920515501750789)),
 (1474, np.float64(0.08920515501750789)),
 (2245, np.float64(0.08920515501750789)),
 (2645, np.float64(0.08920515501750789)),
 (2952, np.float64(0.08920515501750789)),
 (43, np.float64(0.0888231183368655)),
 (331, np.float64(0.0888231183368655)),
 (2357, np.float64(0.0888231183368655)),
 (2790, np.float64(0.0888231183368655)),
 (2850, np.float64(0.0888231183368655)),
 (3384, np.float64(0.0888231183368655)),
 (3457, np.float64(0.0888231183368655)),
 (4347, np.float64(0.0888231183368655)),
 (274, np.float64(0.08833906504195108)),
 (270, np.float64(0.08798117404291673)),
 (1900, np.float64(0.08798117404291673)),
 (2109, np.float64(0.08788174152965353)),
 (23, np.float64(0.08770580193070292)),
 (457, np.float64(0.08770580193070292)),
 (1256, np.float64(0.08770580193070292)),
 (1583, np.float64(0.08770580193070292)),
 (2654, np.float64(0.08770580193070292)),
 (2862, np.float64(0.08770580193070292)),
 (3317, np.float64(0.08770580193070292)),
 (169, np.float64(0.08716272672808179)),
 (618, np.float64(0.08716272672808179)),
 (1777, np.float64(0.08716272672808179)),
 (2103, np.float64(0.08716272672808179)),
 (2707, np.float64(0.08716272672808179)),
 (2734, np.float64(0.08716272672808179)),
 (3548, np.float64(0.08716272672808179)),
 (4337, np.float64(0.08716272672808179)),
 (479, np.float64(0.08684168428648435)),
 (752, np.float64(0.08636670341750609)),
 (1826, np.float64(0.08636670341750609)),
 (2442, np.float64(0.08633531446374632)),
 (2, np.float64(0.08627959628145762)),
 (141, np.float64(0.08627959628145762)),
 (292, np.float64(0.08627959628145762)),
 (745, np.float64(0.08627959628145762)),
 (794, np.float64(0.08627959628145762)),
 (1246, np.float64(0.08627959628145762)),
 (3443, np.float64(0.08627959628145762)),
 (3444, np.float64(0.08627959628145762)),
 (143, np.float64(0.08559209850218259)),
 (534, np.float64(0.08559209850218259)),
 (827, np.float64(0.08559209850218259)),
 (1016, np.float64(0.08559209850218259)),
 (1524, np.float64(0.08559209850218259)),
 (2348, np.float64(0.08559209850218259)),

In [61]:
# we get second number of movie using loc function
final_df.loc[1599]

movie_id                                               293863
title_x                                    The Age of Adaline
tags        after 29-year-old adalin recov from a nearli l...
Name: 1599, dtype: object

In [62]:
for i in similar_movie:
    print(i)

(0, np.float64(1.0000000000000004))
(1213, np.float64(0.283069258536149))
(2403, np.float64(0.26554250227189713))
(3723, np.float64(0.25715142542972574))
(507, np.float64(0.2545139051903111))
(539, np.float64(0.2471557663714903))
(582, np.float64(0.24194822861802104))
(1201, np.float64(0.24140227479263374))
(1191, np.float64(0.23372319715296228))
(61, np.float64(0.22880215766121476))
(778, np.float64(0.22875450543583872))
(4041, np.float64(0.22489899383695006))
(1914, np.float64(0.22237479499833035))
(2780, np.float64(0.21571674297647797))
(972, np.float64(0.20814536170751838))
(322, np.float64(0.20780973338645242))
(151, np.float64(0.20483662259967564))
(172, np.float64(0.20483662259967564))
(2327, np.float64(0.2038098661460272))
(74, np.float64(0.20180183819889372))
(3603, np.float64(0.20174251088960077))
(260, np.float64(0.2013190579900678))
(577, np.float64(0.20131905799006777))
(4185, np.float64(0.20033416898825335))
(1086, np.float64(0.1981740732880975))
(3667, np.float64(0.19535451620220176))
(1438, np.float64(0.19418390934515434))
(47, np.float64(0.19277164398874672))
(27, np.float64(0.19258222162991087))
(2966, np.float64(0.19003715589632172))
(942, np.float64(0.18887686585995425))
(1198, np.float64(0.18842228790639834))
(495, np.float64(0.1884222879063983))
(305, np.float64(0.1876221896512875))
(4, np.float64(0.18685673434682065))
(4399, np.float64(0.18490006540840973))
(94, np.float64(0.1849000654084097))
(2994, np.float64(0.18367958959266126))
(3322, np.float64(0.18367958959266126))
(1272, np.float64(0.1815682598006407))
(1326, np.float64(0.1815682598006407))
(1318, np.float64(0.17902871850985821))
(220, np.float64(0.17841031003501578))
(83, np.float64(0.177646236673731))
(1068, np.float64(0.17722938923964168))
(3992, np.float64(0.1754116038614058))
(2198, np.float64(0.1750547131481244))
(4330, np.float64(0.17505471314812437))
(373, np.float64(0.17471413945365305))
(168, np.float64(0.17295817388759027))
(184, np.float64(0.17295817388759027))
(838, np.float64(0.17103344030668954))
(36, np.float64(0.17093520167692652))
(931, np.float64(0.16984155512168933))
(300, np.float64(0.16898159235484364))
(3157, np.float64(0.16820685341247196))
(91, np.float64(0.16724840200141816))
(1976, np.float64(0.16724840200141816))
(529, np.float64(0.167093470609201))
(1825, np.float64(0.167093470609201))
(150, np.float64(0.16641005886756868))
(661, np.float64(0.1653796461189446))
(41, np.float64(0.16526725762745997))
(3533, np.float64(0.16526725762745997))
(342, np.float64(0.1611258466588724))
(595, np.float64(0.1585187847802434))
(1531, np.float64(0.1585187847802434))
(67, np.float64(0.15794943794779692))
(31, np.float64(0.15701857325533194))
(2509, np.float64(0.15701857325533194))
(1175, np.float64(0.15585730003983933))
(4003, np.float64(0.15534712747612348))
(149, np.float64(0.15421731519099738))
(581, np.float64(0.15408338784034142))
(2725, np.float64(0.15408338784034142))
(26, np.float64(0.15191090506255))
(1377, np.float64(0.15191090506255))
(187, np.float64(0.1500468969841066))
(111, np.float64(0.14824986333222023))
(311, np.float64(0.14824986333222023))
(513, np.float64(0.14824986333222023))
(1341, np.float64(0.14824986333222023))
(52, np.float64(0.14651588715165131))
(2069, np.float64(0.14617633655117152))
(127, np.float64(0.14504754485877894))
(7, np.float64(0.14484136487558028))
(2754, np.float64(0.1447071903540765))
(275, np.float64(0.1437993271357627))
(579, np.float64(0.1437993271357627))
(108, np.float64(0.14322297480788657))
(466, np.float64(0.14322297480788657))
(1294, np.float64(0.14322297480788657))
(1352, np.float64(0.14322297480788657))
(1473, np.float64(0.14235407108686474))
(1932, np.float64(0.1416576493949657))
(3349, np.float64(0.14153462926807447))
(294, np.float64(0.14153462926807445))
(413, np.float64(0.14153462926807445))
(568, np.float64(0.14153462926807445))
(95, np.float64(0.1401425507601155))
(1053, np.float64(0.1401425507601155))
(1270, np.float64(0.1401425507601155))
(1390, np.float64(0.14011213457945124))
(1959, np.float64(0.14011213457945124))
(490, np.float64(0.13977131156292244))
(1482, np.float64(0.13977131156292244))
(46, np.float64(0.13937366833451514))
(461, np.float64(0.13937366833451514))
(2490, np.float64(0.13937366833451514))
(2163, np.float64(0.1373087590952724))
(3404, np.float64(0.1373087590952724))
(56, np.float64(0.13655774839978377))
(249, np.float64(0.13655774839978377))
(1324, np.float64(0.13655774839978377))
(3774, np.float64(0.13655774839978377))
(17, np.float64(0.13592873654160803))
(72, np.float64(0.13533299049019168))
(859, np.float64(0.13533299049019168))
(4072, np.float64(0.13533299049019168))
(4532, np.float64(0.1345345587992625))
(476, np.float64(0.13355611265883557))
(505, np.float64(0.13355611265883557))
(935, np.float64(0.13355611265883557))
(3975, np.float64(0.13355611265883557))
(843, np.float64(0.13344012817090595))
(1802, np.float64(0.13344012817090595))
(4342, np.float64(0.13323467750529824))
(1319, np.float64(0.13302600912742518))
(158, np.float64(0.1319717610643751))
(502, np.float64(0.1319717610643751))
(777, np.float64(0.1319717610643751))
(1554, np.float64(0.1316245316231641))
(668, np.float64(0.1307440900921227))
(1367, np.float64(0.1307440900921227))
(2372, np.float64(0.1307440900921227))
(2578, np.float64(0.1307440900921227))
(1012, np.float64(0.12988108336653278))
(2127, np.float64(0.1283881477532739))
(14, np.float64(0.12820512820512822))
(2175, np.float64(0.12820512820512822))
(3617, np.float64(0.12820512820512822))
(134, np.float64(0.12810252304406972))
(368, np.float64(0.12810252304406972))
(1768, np.float64(0.12810252304406972))
(2867, np.float64(0.12725695259515554))
(138, np.float64(0.12659242088545833))
(1083, np.float64(0.12659242088545833))
(2680, np.float64(0.12659242088545833))
(4223, np.float64(0.12659242088545833))
(483, np.float64(0.12561485860426555))
(487, np.float64(0.12561485860426555))
(773, np.float64(0.12561485860426555))
(1155, np.float64(0.12561485860426555))
(1735, np.float64(0.125081459767525))
(126, np.float64(0.12503908082008885))
(369, np.float64(0.12503908082008885))
(937, np.float64(0.12503908082008883))
(2474, np.float64(0.12403473458920844))
(166, np.float64(0.1235415527768502))
(754, np.float64(0.1235415527768502))
(2444, np.float64(0.1235415527768502))
(3623, np.float64(0.1235415527768502))
(208, np.float64(0.12326671027227314))
(1093, np.float64(0.12326671027227314))
(2054, np.float64(0.12326671027227314))
(2965, np.float64(0.12326671027227314))
(102, np.float64(0.12301385521570944))
(84, np.float64(0.12201777521731262))
(1872, np.float64(0.12201777521731262))
(68, np.float64(0.12104550653376046))
(438, np.float64(0.1207011373963169))
(2325, np.float64(0.12009611535381534))
(2668, np.float64(0.12009611535381534))
(2783, np.float64(0.12009611535381534))
(3078, np.float64(0.12009611535381534))
(549, np.float64(0.11935247900657213))
(1296, np.float64(0.11935247900657213))
(2278, np.float64(0.11935247900657213))
(139, np.float64(0.1191687183448436))
(781, np.float64(0.11894020669001053))
(1001, np.float64(0.11894020669001053))
(1271, np.float64(0.11894020669001053))
(1652, np.float64(0.11894020669001053))
(2646, np.float64(0.11894020669001053))
(3371, np.float64(0.11894020669001053))
(3729, np.float64(0.11894020669001053))
(4667, np.float64(0.11894020669001053))
(999, np.float64(0.1182624791978165))
(870, np.float64(0.1180480411624714))
(900, np.float64(0.1180480411624714))
(1044, np.float64(0.11694106924093722))
(1298, np.float64(0.11694106924093722))
(1827, np.float64(0.11694106924093722))
(2735, np.float64(0.11694106924093722))
(278, np.float64(0.11678545896676293))
(557, np.float64(0.11678545896676293))
(3230, np.float64(0.11678545896676293))
(1667, np.float64(0.1165103456070926))
(1709, np.float64(0.1165103456070926))
(3714, np.float64(0.1165103456070926))
(3993, np.float64(0.1165103456070926))
(160, np.float64(0.11561170597113389))
(182, np.float64(0.11556254088025608))
(1611, np.float64(0.11556254088025608))
(2541, np.float64(0.11556254088025608))
(28, np.float64(0.11503946170861017))
(122, np.float64(0.11503946170861017))
(236, np.float64(0.11503946170861017))
(422, np.float64(0.11503946170861017))
(678, np.float64(0.11503946170861017))
(589, np.float64(0.11483385035264292))
(1491, np.float64(0.114022293537793))
(3207, np.float64(0.11357879791107993))
(189, np.float64(0.11322770341445959))
(1569, np.float64(0.11322770341445959))
(50, np.float64(0.11322770341445958))
(454, np.float64(0.11322770341445958))
(85, np.float64(0.11265439490322912))
(432, np.float64(0.11211213233271873))
(1217, np.float64(0.11211213233271873))
(1412, np.float64(0.11211213233271873))
(21, np.float64(0.11149893466761211))
(121, np.float64(0.11149893466761211))
(232, np.float64(0.11149893466761211))
(1610, np.float64(0.11149893466761211))
(536, np.float64(0.11102889792108188))
(889, np.float64(0.11098534863604863))
(256, np.float64(0.11020775375559674))
(808, np.float64(0.11020775375559674))
(1345, np.float64(0.11020775375559674))
(2317, np.float64(0.11020775375559674))
(3142, np.float64(0.11020775375559674))
(1506, np.float64(0.10997646755364593))
(123, np.float64(0.10997646755364592))
(420, np.float64(0.10997646755364592))
(2366, np.float64(0.10997646755364592))
(3003, np.float64(0.10984700727621793))
(4462, np.float64(0.10984700727621793))
(206, np.float64(0.10948978029027179))
(238, np.float64(0.10948978029027179))
(228, np.float64(0.10895340841010223))
(3304, np.float64(0.10895340841010223))
(81, np.float64(0.10878565864408421))
(1568, np.float64(0.10878565864408421))
(3423, np.float64(0.10826639239215335))
(87, np.float64(0.10826639239215334))
(449, np.float64(0.10826639239215334))
(1028, np.float64(0.10826639239215334))
(1939, np.float64(0.10826639239215334))
(2066, np.float64(0.10826639239215334))
(5, np.float64(0.10795837927188262))
(692, np.float64(0.10795837927188262))
(740, np.float64(0.1079583792718826))
(200, np.float64(0.10741723110591493))
(653, np.float64(0.10741723110591493))
(1495, np.float64(0.10741723110591493))
(1518, np.float64(0.10741723110591493))
(307, np.float64(0.10736246830291345))
(3088, np.float64(0.10699012312772824))
(3625, np.float64(0.10699012312772824))
(332, np.float64(0.10675210253672475))
(472, np.float64(0.10675210253672475))
(786, np.float64(0.10675210253672475))
(3493, np.float64(0.10675210253672475))
(4771, np.float64(0.10675210253672475))
(262, np.float64(0.10604746049596296))
(541, np.float64(0.10604746049596296))
(572, np.float64(0.10604746049596296))
(229, np.float64(0.10545808983558425))
(1234, np.float64(0.10529962529853128))
(170, np.float64(0.105129283382795))
(627, np.float64(0.10482848367219183))
(939, np.float64(0.10482848367219183))
(1739, np.float64(0.10482848367219183))
(2155, np.float64(0.10482848367219183))
(2515, np.float64(0.10482848367219183))
(2628, np.float64(0.10482848367219183))
(4128, np.float64(0.10482848367219183))
(467, np.float64(0.10423454980627084))
(1490, np.float64(0.10423454980627084))
(131, np.float64(0.10390486669322622))
(295, np.float64(0.10390486669322622))
(687, np.float64(0.10390486669322622))
(814, np.float64(0.10390486669322622))
(1034, np.float64(0.10390486669322622))
(1765, np.float64(0.10390486669322622))
(3335, np.float64(0.10390486669322622))
(2492, np.float64(0.10336227882434038))
(10, np.float64(0.10256410256410257))
(75, np.float64(0.10256410256410257))
(223, np.float64(0.10256410256410257))
(643, np.float64(0.10256410256410257))
(1192, np.float64(0.10256410256410257))
(2811, np.float64(0.10256410256410257))
(3748, np.float64(0.10256410256410257))
(654, np.float64(0.1025115460130912))
(2100, np.float64(0.1025115460130912))
(2433, np.float64(0.1025115460130912))
(105, np.float64(0.10241831129983782))
(157, np.float64(0.10241831129983782))
(233, np.float64(0.10241831129983782))
(1163, np.float64(0.10241831129983782))
(2450, np.float64(0.10241831129983782))
(2756, np.float64(0.10241831129983782))
(3050, np.float64(0.10241831129983782))
(3616, np.float64(0.10241831129983782))
(3832, np.float64(0.10241831129983782))
(1449, np.float64(0.10168147934776052))
(174, np.float64(0.10127393670836667))
(508, np.float64(0.10127393670836667))
(1079, np.float64(0.10127393670836667))
(2142, np.float64(0.10127393670836667))
(3147, np.float64(0.10127393670836667))
(3629, np.float64(0.10127393670836667))
(3867, np.float64(0.10127393670836667))
(4090, np.float64(0.10127393670836667))
(35, np.float64(0.10016708449412667))
(319, np.float64(0.10016708449412667))
(624, np.float64(0.10016708449412667))
(1074, np.float64(0.10016708449412667))
(2047, np.float64(0.10016708449412667))
(3655, np.float64(0.10016708449412667))
(3947, np.float64(0.10016708449412667))
(3436, np.float64(0.10008009612817945))
(330, np.float64(0.10003126465607108))
(1291, np.float64(0.10003126465607107))
(491, np.float64(0.09930726528736966))
(1399, np.float64(0.09930726528736966))
(1433, np.float64(0.09930726528736966))
(207, np.float64(0.09883324222148016))
(445, np.float64(0.09883324222148016))
(985, np.float64(0.09883324222148016))
(1395, np.float64(0.09883324222148016))
(1608, np.float64(0.09883324222148016))
(2241, np.float64(0.09883324222148016))
(363, np.float64(0.09855206599818042))
(2093, np.float64(0.09855206599818042))
(33, np.float64(0.09805806756909202))
(325, np.float64(0.09805806756909202))
(715, np.float64(0.09805806756909202))
(878, np.float64(0.09805806756909202))
(1277, np.float64(0.09805806756909202))
(1878, np.float64(0.09805806756909202))
(2781, np.float64(0.09805806756909202))
(4011, np.float64(0.09805806756909202))
(4191, np.float64(0.09805806756909202))
(4325, np.float64(0.09805806756909202))
(4484, np.float64(0.09805806756909202))
(1769, np.float64(0.09781383788084239))
(266, np.float64(0.09767725810110088))
(510, np.float64(0.09767725810110088))
(3928, np.float64(0.09767725810110088))
(3776, np.float64(0.09767725810110087))
(9, np.float64(0.09656090991705352))
(410, np.float64(0.09656090991705352))
(480, np.float64(0.09656090991705352))
(535, np.float64(0.09656090991705352))
(898, np.float64(0.09656090991705352))
(1106, np.float64(0.09656090991705352))
(1817, np.float64(0.09656090991705352))
(2247, np.float64(0.09656090991705352))
(3615, np.float64(0.09656090991705352))
(148, np.float64(0.09607689228305229))
(263, np.float64(0.09607689228305229))
(362, np.float64(0.09607689228305229))
(1153, np.float64(0.09607689228305229))
(1936, np.float64(0.09607689228305229))
(2556, np.float64(0.09607689228305229))
(4249, np.float64(0.09607689228305229))
(4397, np.float64(0.09607689228305229))
(4466, np.float64(0.09607689228305229))
(312, np.float64(0.0954819832052577))
(334, np.float64(0.0954819832052577))
(371, np.float64(0.0954819832052577))
(2235, np.float64(0.0954819832052577))
(11, np.float64(0.09443843292997713))
(412, np.float64(0.09443843292997713))
(1990, np.float64(0.09443843292997713))
(2550, np.float64(0.09443843292997713))
(18, np.float64(0.09435641951204965))
(4539, np.float64(0.09435641951204965))
(791, np.float64(0.09421114395319916))
(1024, np.float64(0.09421114395319916))
(1721, np.float64(0.09421114395319916))
(4196, np.float64(0.09421114395319916))
(243, np.float64(0.09245003270420486))
(473, np.float64(0.09245003270420486))
(813, np.float64(0.09245003270420486))
(1273, np.float64(0.09245003270420486))
(1354, np.float64(0.09245003270420486))
(1686, np.float64(0.09245003270420486))
(2482, np.float64(0.09245003270420486))
(2586, np.float64(0.09245003270420486))
(2814, np.float64(0.09245003270420486))
(3713, np.float64(0.09245003270420486))
(4496, np.float64(0.09245003270420486))
(301, np.float64(0.09245003270420485))
(511, np.float64(0.09245003270420485))
(660, np.float64(0.09245003270420485))
(920, np.float64(0.09245003270420485))
(1567, np.float64(0.09245003270420485))
(1680, np.float64(0.09245003270420485))
(1715, np.float64(0.09245003270420485))
(2390, np.float64(0.09245003270420485))
(2639, np.float64(0.09245003270420485))
(3532, np.float64(0.09245003270420485))
(799, np.float64(0.09183979479633063))
(785, np.float64(0.09183979479633061))
(596, np.float64(0.0915018021743355))
(1440, np.float64(0.0915018021743355))
(1695, np.float64(0.0915018021743355))
(2644, np.float64(0.0915018021743355))
(219, np.float64(0.09078412990032035))
(244, np.float64(0.09078412990032035))
(356, np.float64(0.09078412990032035))
(977, np.float64(0.09078412990032035))
(1303, np.float64(0.09078412990032035))
(1750, np.float64(0.09078412990032035))
(2087, np.float64(0.09078412990032035))
(230, np.float64(0.09065471553673685))
(3402, np.float64(0.09058216273156766))
(239, np.float64(0.0900791242218625))
(2564, np.float64(0.0900791242218625))
(602, np.float64(0.08968970586617499))
(994, np.float64(0.08968970586617499))
(1230, np.float64(0.08968970586617499))
(1840, np.float64(0.08968970586617499))
(3874, np.float64(0.08968970586617499))
(12, np.float64(0.08920515501750789))
(88, np.float64(0.08920515501750789))
(167, np.float64(0.08920515501750789))
(389, np.float64(0.08920515501750789))
(400, np.float64(0.08920515501750789))
(564, np.float64(0.08920515501750789))
(1468, np.float64(0.08920515501750789))
(1474, np.float64(0.08920515501750789))
(2245, np.float64(0.08920515501750789))
(2645, np.float64(0.08920515501750789))
(2952, np.float64(0.08920515501750789))
(43, np.float64(0.0888231183368655))
(331, np.float64(0.0888231183368655))
(2357, np.float64(0.0888231183368655))
(2790, np.float64(0.0888231183368655))
(2850, np.float64(0.0888231183368655))
(3384, np.float64(0.0888231183368655))
(3457, np.float64(0.0888231183368655))
(4347, np.float64(0.0888231183368655))
(274, np.float64(0.08833906504195108))
(270, np.float64(0.08798117404291673))
(1900, np.float64(0.08798117404291673))
(2109, np.float64(0.08788174152965353))
(23, np.float64(0.08770580193070292))
(457, np.float64(0.08770580193070292))
(1256, np.float64(0.08770580193070292))
(1583, np.float64(0.08770580193070292))
(2654, np.float64(0.08770580193070292))
(2862, np.float64(0.08770580193070292))
(3317, np.float64(0.08770580193070292))
(169, np.float64(0.08716272672808179))
(618, np.float64(0.08716272672808179))
(1777, np.float64(0.08716272672808179))
(2103, np.float64(0.08716272672808179))
(2707, np.float64(0.08716272672808179))
(2734, np.float64(0.08716272672808179))
(3548, np.float64(0.08716272672808179))
(4337, np.float64(0.08716272672808179))
(479, np.float64(0.08684168428648435))
(752, np.float64(0.08636670341750609))
(1826, np.float64(0.08636670341750609))
(2442, np.float64(0.08633531446374632))
(2, np.float64(0.08627959628145762))
(141, np.float64(0.08627959628145762))
(292, np.float64(0.08627959628145762))
(745, np.float64(0.08627959628145762))
(794, np.float64(0.08627959628145762))
(1246, np.float64(0.08627959628145762))
(3443, np.float64(0.08627959628145762))
(3444, np.float64(0.08627959628145762))
(143, np.float64(0.08559209850218259))
(534, np.float64(0.08559209850218259))
(827, np.float64(0.08559209850218259))
(1016, np.float64(0.08559209850218259))
(1524, np.float64(0.08559209850218259))
(2348, np.float64(0.08559209850218259))
(2874, np.float64(0.08559209850218259))
(3551, np.float64(0.08559209850218259))
(4510, np.float64(0.08559209850218259))
(4581, np.float64(0.08559209850218259))
(775, np.float64(0.08492077756084468))
(960, np.float64(0.08492077756084468))
(1094, np.float64(0.08492077756084468))
(1372, np.float64(0.08492077756084468))
(2577, np.float64(0.08492077756084468))
(3130, np.float64(0.08492077756084468))
(4748, np.float64(0.08492077756084468))
(32, np.float64(0.08483796839677037))
(129, np.float64(0.08483796839677037))
(234, np.float64(0.08483796839677037))
(48, np.float64(0.084103426706236))
(190, np.float64(0.084103426706236))
(217, np.float64(0.084103426706236))
(1302, np.float64(0.084103426706236))
(1, np.float64(0.08362420100070908))
(203, np.float64(0.08362420100070908))
(547, np.float64(0.08362420100070908))
(894, np.float64(0.08362420100070908))
(1139, np.float64(0.08362420100070908))
(2298, np.float64(0.08362420100070908))
(4554, np.float64(0.08362420100070908))

In [63]:
# We wanted top 10 movies to be recommended similar to 'titanic' movie:

for index, similarity_score in similar_movie[1:11]: #[1:11] means top 10 movies
    
    print(final_df.iloc[index, 1])

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.
Battle: Los Angeles
Predators
Small Soldiers
Jupiter Ascending
Meet Dave

In [64]:
# # Now we are saving this whole recommendation system in a single function

def recommend(movie_name):
    movie_index = final_df[final_df["title_x"] == movie_name].index[0]
    distances = similarity[movie_index]
    similar_movie = sorted(list(enumerate(distances)), reverse=True, key= lambda x:x[1])

    for index, similarity_score in similar_movie[1:11]: #[1:11] means top 10 movies
    
        print(final_df.iloc[index, 1])

In [66]:
recommend("")

IndexError: index 0 is out of bounds for axis 0 with size 0