In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect(":memory:")

In [3]:
pd.read_sql_query("SELECT * FROM sqlite_master", conn)

Empty DataFrame
Columns: [type, name, tbl_name, rootpage, sql]
Index: []

### DATA DEFINITION LANGUAGE
- This is table changes

- CREATE TABLE
- ALTER TABLE
- DROP TABLE

In [4]:
# CREATING DATABASE TABLE SCHEME

conn.execute("""CREATE TABLE DATABASE 
            (instructor_id INTEGER PRIMARY KEY,
            full_name VARCHAR(100) NOT NULL,
            dept VARCHAR(50),
            hire_date DATE,
            starting_salary DECIMAL(10,2)
            )""")

In [5]:
pd.read_sql_query("SELECT * FROM sqlite_master", conn)

,type,name,tbl_name,rootpage,sql
0,table,DATABASE,DATABASE,2,CREATE TABLE DATABASE \n (instructo...

In [6]:
conn.execute("""ALTER TABLE DATABASE ADD COLUMN performance_score INTEGER""")

In [7]:
pd.read_sql_query("SELECT * FROM DATABASE", conn)

Empty DataFrame
Columns: [instructor_id, full_name, dept, hire_date, starting_salary, performance_score]
Index: []

In [8]:
conn.execute("""ALTER TABLE DATABASE RENAME COLUMN dept TO department""")

In [9]:
conn.execute("""ALTER TABLE DATABASE RENAME TO instructor_db""")

In [10]:
pd.read_sql_query("SELECT * FROM sqlite_master", conn)

,type,name,tbl_name,rootpage,sql
0,table,instructor_db,instructor_db,2,"CREATE TABLE ""instructor_db"" \n (in..."

In [11]:
conn.execute("""ALTER TABLE instructor_db DROP COLUMN department""")

In [12]:
pd.read_sql_query("SELECT * FROM instructor_db", conn)

Empty DataFrame
Columns: [instructor_id, full_name, hire_date, starting_salary, performance_score]
Index: []

In [13]:
#DROP QUERY
# conn.execute("DROP TABLE performers ",conn)

#### DATA MANIPULATION LANGUAGE DML
This is for Rows

- INSERT INTO
- UPDATE
- DELETE

In [14]:
conn.execute("""
INSERT INTO instructor_db
(instructor_id, full_name, hire_date, performance_score, starting_salary)
VALUES
(101, 'Khan', '2026-08-18', 9, 120000),
(102, 'Abdul', '2026-08-14', 7, 160000),
(103, 'Askim', '2026-05-28', NULL, 76000),
(104, 'Hussain', '2023-02-18', 5, 245000),
(105, 'Khan', NULL, 10, 800000)
""")

In [15]:
pd.read_sql_query("SELECT * FROM instructor_db", conn)

   instructor_id full_name   hire_date  starting_salary  performance_score
0            101      Khan  2026-08-18           120000                9.0
1            102     Abdul  2026-08-14           160000                7.0
2            103     Askim  2026-05-28            76000                NaN
3            104   Hussain  2023-02-18           245000                5.0
4            105      Khan        None           800000               10.0

In [16]:
conn.execute("""UPDATE instructor_db
SET starting_salary = NULL,
    performance_score = 8
WHERE instructor_id = 101""")

In [17]:
pd.read_sql_query("SELECT * FROM instructor_db", conn)

   instructor_id full_name   hire_date  starting_salary  performance_score
0            101      Khan  2026-08-18              NaN                8.0
1            102     Abdul  2026-08-14         160000.0                7.0
2            103     Askim  2026-05-28          76000.0                NaN
3            104   Hussain  2023-02-18         245000.0                5.0
4            105      Khan        None         800000.0               10.0

In [18]:

conn.execute("""DELETE FROM instructor_db
            WHERE instructor_id = 103 """)

In [19]:
pd.read_sql_query("SELECT * FROM instructor_db", conn)

   instructor_id full_name   hire_date  starting_salary  performance_score
0            101      Khan  2026-08-18              NaN                  8
1            102     Abdul  2026-08-14         160000.0                  7
2            104   Hussain  2023-02-18         245000.0                  5
3            105      Khan        None         800000.0                 10

#### DATA QUERY LANGUAGE

- SELECT
- WHERE
- FILTER OPTIONS
- CASE WHEN (IF ELSE CONDITION) for sql
- COALESCE
- IF NULL
- ORDER BY
- LIMIT

In [20]:
pd.read_sql_query("SELECT * FROM instructor_db ORDER BY starting_salary", conn)

   instructor_id full_name   hire_date  starting_salary  performance_score
0            101      Khan  2026-08-18              NaN                  8
1            102     Abdul  2026-08-14         160000.0                  7
2            104   Hussain  2023-02-18         245000.0                  5
3            105      Khan        None         800000.0                 10

In [21]:
pd.read_sql_query("""SELECT * FROM instructor_db 
                    WHERE performance_score > 7 
                    ORDER BY performance_score ASC""", conn)

   instructor_id full_name   hire_date  starting_salary  performance_score
0            101      Khan  2026-08-18              NaN                  8
1            105      Khan        None         800000.0                 10

In [22]:
pd.read_sql_query(""" 
    SELECT 
        *,
    CASE 
        WHEN starting_salary >= 150000 THEN "High-Salary"
        WHEN starting_salary <= 160000 THEN "Avg-Salary"
        ELSE "Low-Salary"
    END AS salary_bracket
    FROM instructor_db
    ORDER BY starting_salary DESC
             
""", conn)

,instructor_id,full_name,hire_date,starting_salary,performance_score,salary_bracket
0,105,Khan,None,800000.0,10,High-Salary
1,104,Hussain,2023-02-18,245000.0,5,High-Salary
2,102,Abdul,2026-08-14,160000.0,7,High-Salary
3,101,Khan,2026-08-18,NaN,8,Low-Salary

In [23]:
pd.read_sql_query("SELECT * FROM instructor_db", conn)

   instructor_id full_name   hire_date  starting_salary  performance_score
0            101      Khan  2026-08-18              NaN                  8
1            102     Abdul  2026-08-14         160000.0                  7
2            104   Hussain  2023-02-18         245000.0                  5
3            105      Khan        None         800000.0                 10

In [24]:
pd.read_sql_query("""SELECT *, COALESCE(starting_salary, 0) AS sal_for_calculation FROM instructor_db """, conn)

,instructor_id,full_name,hire_date,starting_salary,performance_score,sal_for_calculation
0,101,Khan,2026-08-18,NaN,8,0
1,102,Abdul,2026-08-14,160000.0,7,160000
2,104,Hussain,2023-02-18,245000.0,5,245000
3,105,Khan,None,800000.0,10,800000

In [25]:
pd.read_sql_query("""SELECT *, IFNULL(hire_date,"date unavailable") AS date FROM instructor_db """, conn)

,instructor_id,full_name,hire_date,starting_salary,performance_score,date
0,101,Khan,2026-08-18,NaN,8,2026-08-18
1,102,Abdul,2026-08-14,160000.0,7,2026-08-14
2,104,Hussain,2023-02-18,245000.0,5,2023-02-18
3,105,Khan,None,800000.0,10,date unavailable

### VIEWS

In [26]:
pd.read_sql_query("SELECT * FROM sqlite_master", conn)

,type,name,tbl_name,rootpage,sql
0,table,instructor_db,instructor_db,2,"CREATE TABLE ""instructor_db"" \n (in..."

In [27]:
conn.execute("""
CREATE VIEW performers AS
SELECT full_name, hire_date, starting_salary, performance_score
FROM instructor_db
WHERE performance_score >= 8""")

In [28]:
pd.read_sql_query("SELECT * FROM performers", conn)

  full_name   hire_date  starting_salary  performance_score
0      Khan  2026-08-18              NaN                  8
1      Khan        None         800000.0                 10