In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect(":memory:")

In [3]:
pd.read_sql_query("SELECT * FROM sqlite_master", conn)

Empty DataFrame
Columns: [type, name, tbl_name, rootpage, sql]
Index: []

### DATA DEFINITION LANGUAGE
- This is table changes

- CREATE TABLE
- ALTER TABLE
- DROP TABLE

In [4]:
# CREATING DATABASE TABLE SCHEME

conn.execute("""CREATE TABLE DATABASE 
            (instructor_id INTEGER PRIMARY KEY,
            full_name VARCHAR(100) NOT NULL,
            dept VARCHAR(50),
            hire_date DATE,
            starting_salary DECIMAL(10,2)
            )""")

In [5]:
pd.read_sql_query("SELECT * FROM sqlite_master", conn)

,type,name,tbl_name,rootpage,sql
0,table,DATABASE,DATABASE,2,CREATE TABLE DATABASE \n (instructo...

In [6]:
conn.execute("""ALTER TABLE DATABASE ADD COLUMN performance_score INTEGER""")

In [7]:
pd.read_sql_query("SELECT * FROM DATABASE", conn)

Empty DataFrame
Columns: [instructor_id, full_name, dept, hire_date, starting_salary, performance_score]
Index: []

In [8]:
conn.execute("""ALTER TABLE DATABASE RENAME COLUMN dept TO department""")

In [9]:
conn.execute("""ALTER TABLE DATABASE RENAME TO instructor_db""")

In [10]:
pd.read_sql_query("SELECT * FROM sqlite_master", conn)

,type,name,tbl_name,rootpage,sql
0,table,instructor_db,instructor_db,2,"CREATE TABLE ""instructor_db"" \n (in..."

In [11]:
conn.execute("""ALTER TABLE instructor_db DROP COLUMN department""")

In [12]:
pd.read_sql_query("SELECT * FROM instructor_db", conn)

Empty DataFrame
Columns: [instructor_id, full_name, hire_date, starting_salary, performance_score]
Index: []

#### DATA MANIPULATION LANGUAGE DML
- This is for Rows

- INSERT INTO
- UPDATE
- DELETE

In [13]:
conn.execute("""
INSERT INTO instructor_db
(instructor_id, full_name, hire_date, performance_score, starting_salary)
VALUES
(101, 'Khan', '2026-08-18', 9, 120000),
(102, 'Abdul', '2026-08-14', 7, 160000),
(103, 'Askim', '2026-05-28', NULL, 76000),
(104, 'Hussain', '2023-02-18', 5, 245000),
(105, 'Khan', NULL, 10, 800000)
""")

In [14]:
pd.read_sql_query("SELECT * FROM instructor_db", conn)

   instructor_id full_name   hire_date  starting_salary  performance_score
0            101      Khan  2026-08-18           120000                9.0
1            102     Abdul  2026-08-14           160000                7.0
2            103     Askim  2026-05-28            76000                NaN
3            104   Hussain  2023-02-18           245000                5.0
4            105      Khan        None           800000               10.0

In [15]:
conn.execute("""UPDATE instructor_db
SET performance_score = 8
WHERE instructor_id = 101""")

In [16]:
# DELETE QUERY

#### DATA QUERY LANGUAGE

- SELECT
- WHERE
- FILTER OPTIONS
- ORDER BY
-LIMIT

In [17]:
pd.read_sql_query("SELECT * FROM instructor_db", conn)

   instructor_id full_name   hire_date  starting_salary  performance_score
0            101      Khan  2026-08-18           120000                8.0
1            102     Abdul  2026-08-14           160000                7.0
2            103     Askim  2026-05-28            76000                NaN
3            104   Hussain  2023-02-18           245000                5.0
4            105      Khan        None           800000               10.0