- In this File, we worked on
-  `factbook database`,
- `PANDAS features in SQL,`
- `SQL JOINS.`

In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
db = "factbook.db"
conn = sql.connect(db)

<img src= 'factbook.jpg' width='60%'/>

In [3]:
query = "SELECT * FROM sqlite_master"

pd.read_sql_query(query,conn)

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,facts,facts,47,"CREATE TABLE ""facts"" (""id"" INTEGER PRIMARY KEY..."
2,table,cities,cities,2,CREATE TABLE cities (\n id integer prim...

In [4]:
query = "SELECT * FROM facts LIMIT 10"
pd.read_sql_query(query, conn)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230,652230,0,32564342,2.32,38.57,13.89,1.51
1,2,al,Albania,28748,27398,1350,3029278,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741,2381741,0,39542166,1.84,23.67,4.31,0.92
3,4,an,Andorra,468,468,0,85580,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700,1246700,0,19625353,2.78,38.78,11.49,0.46
5,6,ac,Antigua and Barbuda,442,442,0,92436,1.24,15.85,5.69,2.21
6,7,ar,Argentina,2780400,2736690,43710,43431886,0.93,16.64,7.33,0.00
7,8,am,Armenia,29743,28203,1540,3056382,0.15,13.61,9.34,5.80
8,9,as,Australia,7741220,7682300,58920,22751014,1.07,12.15,7.14,5.65
9,10,au,Austria,83871,82445,1426,8665550,0.55,9.41,9.42,5.56

In [5]:
query = "SELECT * FROM cities LIMIT 10"

pd.read_sql_query(query, conn)

   id          name  population  capital facts_id
0   1    Oranjestad       37000        1      216
1   2  Saint John'S       27000        1        6
2   3     Abu Dhabi      942000        1      184
3   4         Dubai     1978000        0      184
4   5       Sharjah      983000        0      184
5   6         Kabul     3097000        1        1
6   7       Algiers     2916000        1        3
7   8          Oran      783000        0        3
8   9          Baku     2123000        1       11
9  10        Tirana      419000        1        2

In [6]:
# Using `id` fetching specific country 

query = """SELECT * FROM facts
        WHERE id = 11 
        LIMIT 10"""

pd.read_sql_query(query, conn)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,11,aj,Azerbaijan,86600,82629,3971,9780780,0.96,16.64,7.07,0.0

#### You can also use `Pandas` and its functionalities to work with `SQLite`. This process is very similar to working inside `Databricks notebooks`.

#### It's like Mix of SQL and Pandas syntax. But use it when required.

In [7]:
query = "SELECT * FROM cities LIMIT 10"

#saving into df, similar to Pandas
df = pd.read_sql_query(query, conn)
df

   id          name  population  capital facts_id
0   1    Oranjestad       37000        1      216
1   2  Saint John'S       27000        1        6
2   3     Abu Dhabi      942000        1      184
3   4         Dubai     1978000        0      184
4   5       Sharjah      983000        0      184
5   6         Kabul     3097000        1        1
6   7       Algiers     2916000        1        3
7   8          Oran      783000        0        3
8   9          Baku     2123000        1       11
9  10        Tirana      419000        1        2

In [8]:
# An example of pandas syntax for sqlite3

df[df["facts_id"] == "184"]

   id       name  population  capital facts_id
2   3  Abu Dhabi      942000        1      184
3   4      Dubai     1978000        0      184
4   5    Sharjah      983000        0      184

In [9]:
# Here we have used `INNER JOIN` to join two different tables of 'facts and Cities'
# `INNER JOIN`: Returns only rows that have matching values in both tables

query = """SELECT c.*, f.* FROM facts f
        INNER JOIN cities c 
        ON f.id = c.facts_id"""

pd.read_sql_query(query, conn)

,id,name,population,capital,facts_id,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,Oranjestad,37000,1,216,216,aa,Aruba,180.0,180.0,0.0,112162,1.33,12.56,8.18,8.92
1,2,Saint John'S,27000,1,6,6,ac,Antigua and Barbuda,442.0,442.0,0.0,92436,1.24,15.85,5.69,2.21
2,3,Abu Dhabi,942000,1,184,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36
3,4,Dubai,1978000,0,184,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36
4,5,Sharjah,983000,0,184,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,393,Mbabane,66000,1,167,167,wz,Swaziland,17364.0,17204.0,160.0,1435613,1.11,24.67,13.56,0.00
393,394,Sanaa,2419000,1,193,193,ym,Yemen,527968.0,527968.0,0.0,26737317,2.47,29.98,6.28,1.00
394,395,Aden,784000,0,193,193,ym,Yemen,527968.0,527968.0,0.0,26737317,2.47,29.98,6.28,1.00
395,396,Lusaka,1802000,1,194,194,za,Zambia,752618.0,743398.0,9220.0,15066266,2.88,42.13,12.67,0.68
396,397,Harare,1542000,1,195,195,zi,Zimbabwe,390757.0,386847.0,3910.0,14229541,2.21,32.26,10.13,0.00

In [10]:
# Here we renamed columns from two different tables
query = """SELECT c.facts_id, f.id,
        f.name Countries, c.name Cities, c.capital Capital, f.population country_pop, c.population cities_pop 
        FROM facts f
        INNER JOIN cities c 
        ON f.id = c.facts_id"""

pd.read_sql_query(query, conn)

,facts_id,id,Countries,Cities,Capital,country_pop,cities_pop
0,216,216,Aruba,Oranjestad,1,112162,37000
1,6,6,Antigua and Barbuda,Saint John'S,1,92436,27000
2,184,184,United Arab Emirates,Abu Dhabi,1,5779760,942000
3,184,184,United Arab Emirates,Dubai,0,5779760,1978000
4,184,184,United Arab Emirates,Sharjah,0,5779760,983000
...,...,...,...,...,...,...,...
392,167,167,Swaziland,Mbabane,1,1435613,66000
393,193,193,Yemen,Sanaa,1,26737317,2419000
394,193,193,Yemen,Aden,0,26737317,784000
395,194,194,Zambia,Lusaka,1,15066266,1802000
396,195,195,Zimbabwe,Harare,1,14229541,1542000

In [11]:
# LEFT JOIN: Returns all rows from the left table, and only the matched rows from the right table

query = """SELECT
        f.name Countries, c.name Cities
        FROM facts f
        LEFT JOIN cities c 
        ON f.id = c.facts_id"""

pd.read_sql_query(query, conn)

          Countries            Cities
0       Afghanistan             Kabul
1           Albania            Tirana
2           Algeria           Algiers
3           Algeria              Oran
4           Andorra  Andorra La Vella
..              ...               ...
443  Atlantic Ocean              None
444    Indian Ocean              None
445   Pacific Ocean              None
446  Southern Ocean              None
447           World              None

[448 rows x 2 columns]

In [12]:
query = """SELECT count(*)
        FROM facts f"""
pd.read_sql_query(query, conn)

   count(*)
0       261

In [14]:
# Using `WHERE` clause and `IS NULL`  with `LEFT JOIN`:

query = """SELECT
        f.name Countries, c.name Cities
        FROM facts f
        LEFT JOIN cities c 
        ON f.id = c.facts_id
        WHERE Cities IS NULL"""

pd.read_sql_query(query, conn)

                Countries        Cities
0                   Aruba    Oranjestad
1     Antigua and Barbuda  Saint John'S
2    United Arab Emirates     Abu Dhabi
3    United Arab Emirates         Dubai
4    United Arab Emirates       Sharjah
..                    ...           ...
392             Swaziland       Mbabane
393                 Yemen         Sanaa
394                 Yemen          Aden
395                Zambia        Lusaka
396              Zimbabwe        Harare

[397 rows x 2 columns]

In [15]:
# Using `WHERE` clause and `IS NOT NULL`  with `LEFT JOIN`:

query = """SELECT
        f.name Countries, c.name Cities
        FROM facts f
        LEFT JOIN cities c 
        ON f.id = c.facts_id
        WHERE Cities IS NOT NULL"""

pd.read_sql_query(query, conn)

                Countries        Cities
0                   Aruba    Oranjestad
1     Antigua and Barbuda  Saint John'S
2    United Arab Emirates     Abu Dhabi
3    United Arab Emirates         Dubai
4    United Arab Emirates       Sharjah
..                    ...           ...
392             Swaziland       Mbabane
393                 Yemen         Sanaa
394                 Yemen          Aden
395                Zambia        Lusaka
396              Zimbabwe        Harare

[397 rows x 2 columns]

In [16]:
# RIGHT JOIN: Returns all rows from the right table, and only the matched rows from the left table

query = """SELECT
        f.name Countries, c.name Cities
        FROM facts f
        RIGHT JOIN cities c 
        ON f.id = c.facts_id"""

pd.read_sql_query(query, conn)

                    Countries            Cities
0                 Afghanistan             Kabul
1                     Albania            Tirana
2                     Algeria           Algiers
3                     Algeria              Oran
4                     Andorra  Andorra La Vella
..                        ...               ...
392                      Guam           Hagatna
393  Northern Mariana Islands            Saipan
394               Puerto Rico          San Juan
395            Virgin Islands  Charlotte Amalie
396            Western Sahara          Laayoune

[397 rows x 2 columns]

In [17]:
# FULL JOIN: Returns all rows when there is a match in either the left or right table


query = """SELECT
        f.name Countries, c.name Cities
        FROM facts f
        FULL JOIN cities c 
        ON f.id = c.facts_id"""

pd.read_sql_query(query, conn)

          Countries            Cities
0       Afghanistan             Kabul
1           Albania            Tirana
2           Algeria           Algiers
3           Algeria              Oran
4           Andorra  Andorra La Vella
..              ...               ...
443  Atlantic Ocean              None
444    Indian Ocean              None
445   Pacific Ocean              None
446  Southern Ocean              None
447           World              None

[448 rows x 2 columns]

##### Find `country, tot_pop, urban_pop, urban_pop_pct`

In [52]:
query = """SELECT f.name Country, f.population Total_Population, SUM(c.population) Urban_population,

        (CAST(SUM(c.population) AS FLOAT) / f.population) * 100 Urban_Population_pct
        
        FROM facts f
        INNER JOIN cities c ON f.id = c.facts_id
        GROUP BY f.id, f.name, f.population"""

pd.read_sql_query(query, conn)

,Country,Total_Population,Urban_population,Urban_Population_pct
0,Afghanistan,32564342,3097000,9.510403
1,Albania,3029278,419000,13.831679
2,Algeria,39542166,3699000,9.354571
3,Andorra,85580,23000,26.875438
4,Angola,19625353,6166000,31.418543
...,...,...,...,...
205,Guam,161785,169000,104.459622
206,Northern Mariana Islands,52344,56000,106.984564
207,Puerto Rico,3598357,2475000,68.781391
208,Virgin Islands,103574,60000,57.929596
209,Western Sahara,570866,237000,41.515872