In [2]:
import pandas as pd
import sqlite3 as sql

In [3]:
db = "factbook.db"
conn = sql.connect(db)

<img src= 'factbook.jpg' width='60%'/>

In [9]:
query = "SELECT * FROM sqlite_master"

pd.read_sql_query(query,conn)

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,facts,facts,47,"CREATE TABLE ""facts"" (""id"" INTEGER PRIMARY KEY..."
2,table,cities,cities,2,CREATE TABLE cities (\n id integer prim...

In [12]:
query = "SELECT * FROM facts LIMIT 10"
pd.read_sql_query(query, conn)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230,652230,0,32564342,2.32,38.57,13.89,1.51
1,2,al,Albania,28748,27398,1350,3029278,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741,2381741,0,39542166,1.84,23.67,4.31,0.92
3,4,an,Andorra,468,468,0,85580,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700,1246700,0,19625353,2.78,38.78,11.49,0.46
5,6,ac,Antigua and Barbuda,442,442,0,92436,1.24,15.85,5.69,2.21
6,7,ar,Argentina,2780400,2736690,43710,43431886,0.93,16.64,7.33,0.00
7,8,am,Armenia,29743,28203,1540,3056382,0.15,13.61,9.34,5.80
8,9,as,Australia,7741220,7682300,58920,22751014,1.07,12.15,7.14,5.65
9,10,au,Austria,83871,82445,1426,8665550,0.55,9.41,9.42,5.56

In [13]:
query = "SELECT * FROM cities LIMIT 10"

pd.read_sql_query(query, conn)

   id          name  population  capital facts_id
0   1    Oranjestad       37000        1      216
1   2  Saint John'S       27000        1        6
2   3     Abu Dhabi      942000        1      184
3   4         Dubai     1978000        0      184
4   5       Sharjah      983000        0      184
5   6         Kabul     3097000        1        1
6   7       Algiers     2916000        1        3
7   8          Oran      783000        0        3
8   9          Baku     2123000        1       11
9  10        Tirana      419000        1        2

In [15]:
# Using `id` fetching specific country 

query = """SELECT * FROM facts
        WHERE id = 11 
        LIMIT 10"""

pd.read_sql_query(query, conn)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,11,aj,Azerbaijan,86600,82629,3971,9780780,0.96,16.64,7.07,0.0

#### You can also use `Pandas` and its functionalities to work with `SQLite`. This process is very similar to working inside `Databricks notebooks`.

#### It's like Mix of SQL and Pandas syntax. But use it when required.

In [18]:
query = "SELECT * FROM cities LIMIT 10"

#saving into df, similar to Pandas
df = pd.read_sql_query(query, conn)
df

   id          name  population  capital facts_id
0   1    Oranjestad       37000        1      216
1   2  Saint John'S       27000        1        6
2   3     Abu Dhabi      942000        1      184
3   4         Dubai     1978000        0      184
4   5       Sharjah      983000        0      184
5   6         Kabul     3097000        1        1
6   7       Algiers     2916000        1        3
7   8          Oran      783000        0        3
8   9          Baku     2123000        1       11
9  10        Tirana      419000        1        2

In [22]:
# An example of pandas syntax for sqlite3

df[df["facts_id"] == "184"]

   id       name  population  capital facts_id
2   3  Abu Dhabi      942000        1      184
3   4      Dubai     1978000        0      184
4   5    Sharjah      983000        0      184