In [1]:
import pandas as pd

In [2]:
df_2015 = pd.read_csv('../Dataset/World_Happiness_2015.csv')
df_2016 = pd.read_csv('../Dataset/World_Happiness_2016.csv')
df_2017 = pd.read_csv('../Dataset/World_Happiness_2017.csv')

In [3]:
df_2015.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [4]:
df_2016.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [5]:
df_2017.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')

In [6]:
df_2015["Year"] = 2015
df_2016["Year"] = 2016
df_2017["Year"] = 2017

In [21]:
three_2015 = df_2015[['Country','Happiness Score', 'Year']].head(3)
three_2016 = df_2016[['Country','Happiness Score', 'Year']].head(3)
# three_2016 = df_2016[['Country','Happiness Score', 'Year']].iloc[1:4]

In [8]:
three_2015

       Country  Happiness Score  Year
0  Switzerland            7.587  2015
1      Iceland            7.561  2015
2      Denmark            7.527  2015

In [9]:
three_2016

       Country  Happiness Score  Year
1  Switzerland            7.509  2016
2      Iceland            7.501  2016
3       Norway            7.498  2016

In [10]:
sample = pd.concat([three_2015,three_2016], axis=0)
sample

       Country  Happiness Score  Year
0  Switzerland            7.587  2015
1      Iceland            7.561  2015
2      Denmark            7.527  2015
1  Switzerland            7.509  2016
2      Iceland            7.501  2016
3       Norway            7.498  2016

In [11]:
sample.loc[0]

Country            Switzerland
Happiness Score          7.587
Year                      2015
Name: 0, dtype: object

In [12]:
sample.iloc[0]

Country            Switzerland
Happiness Score          7.587
Year                      2015
Name: 0, dtype: object

In [ ]:
three_2016 = df_2016[['Country','Happiness Score', 'Year']].iloc[1:4]

In [13]:
concatenation = pd.concat([three_2015,three_2016], axis=0)
concatenation

       Country  Happiness Score  Year
0  Switzerland            7.587  2015
1      Iceland            7.561  2015
2      Denmark            7.527  2015
1  Switzerland            7.509  2016
2      Iceland            7.501  2016
3       Norway            7.498  2016

In [14]:
concatenation.reset_index(drop=True)

       Country  Happiness Score  Year
0  Switzerland            7.587  2015
1      Iceland            7.561  2015
2      Denmark            7.527  2015
3  Switzerland            7.509  2016
4      Iceland            7.501  2016
5       Norway            7.498  2016

In [15]:
concatenation = pd.concat([three_2015,three_2016], axis=1)
concatenation

       Country  Happiness Score    Year      Country  Happiness Score    Year
0  Switzerland            7.587  2015.0          NaN              NaN     NaN
1      Iceland            7.561  2015.0  Switzerland            7.509  2016.0
2      Denmark            7.527  2015.0      Iceland            7.501  2016.0
3          NaN              NaN     NaN       Norway            7.498  2016.0

In [16]:
three_2015.rename({"Country":"cty"}, axis=1, inplace=True)

In [17]:
pd.merge(three_2015, three_2016, left_on='cty', right_on='Country', how='outer' )

,cty,Happiness Score_x,Year_x,Country,Happiness Score_y,Year_y
0,Denmark,7.527,2015.0,NaN,NaN,NaN
1,Iceland,7.561,2015.0,Iceland,7.501,2016.0
2,NaN,NaN,NaN,Norway,7.498,2016.0
3,Switzerland,7.587,2015.0,Switzerland,7.509,2016.0

In [18]:
df_2017[df_2017["Country"] == "Pakistan"]

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual,Year
79,Pakistan,80,5.269,5.359984,5.178016,0.726884,0.672691,0.402048,0.235215,0.315446,0.124348,2.792489,2017

In [19]:
df_2016[df_2016["Country"] == "Pakistan"]

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
91,Pakistan,Southern Asia,92,5.132,5.038,5.226,0.68816,0.26135,0.40306,0.14622,0.1388,0.31185,3.18286,2016

In [20]:
# df_2015[df_2015["cty"] == "Pakistan"]