In [1]:
import pandas as pd
import re

In [2]:
hn = pd.read_csv("../Pandas/hacker_news.csv")
hn.head(5)

,id,title,url,num_points,num_comments,author,created_at
0,12579008,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,altstar,9/26/2016 3:26
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,blacksqr,9/26/2016 3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,pavel_lishin,9/26/2016 3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,poindontcare,9/26/2016 3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,markgainor1,9/26/2016 3:14

In [3]:
# We are searching for and in given text
re.search("and", "I have two hands")

In [4]:
# span=(12,15): This is index number where and was found
"I have two hands"[12:15]

'and'

In [5]:
title = hn["title"]

In [6]:
"mend","send","bend"
re.search("[msb]end", "My name is ssend")

In [7]:
pattern = "[Pp]ython"

title[title.str.contains(pattern)]

109           Solve a wooden puzzle with Python and Jupyter
257       A fast PostgreSQL client library for Python: 3...
284                                     Asynchronous Python
444       Python 4 Kids: Python for Kids: Python 3  Proj...
478       Cubr  A Rubiks Cube Solver Written in Python a...
                                ...
292474    OAuth 2.0 for Google (Analytics) API with Pyth...
292506      Mac OS X Keychain Forensic Tool (Python, GPLv2)
292735    Show HN: Combo, the Simple Python Package Manager
292821             Try to not use the Python C API directly
293085      Hackerone disclosed report aggregator in python
Name: title, Length: 2572, dtype: object

In [8]:
pattern = "[Rr]uby"

title[title.str.contains(pattern)]

1291                        Wrote a simple ps clone in ruby
1497       Ruby Poltergeist gem the best way to scrape data
1624      A proposal of new concurrency model for Ruby 3...
1734      Ruby gem to fetch gocd information as rich mod...
1981                    Ruby vs. Python, the Definitive FAQ
                                ...
291994    Statically typed Ruby  method signatures somet...
292008                       Pros and Cons of Ruby on Rails
292456                       PostgreSQL for Ruby Developers
292501            Ruby Robotic Vacuum Programming Challenge
292779          Collection of expectation matchers for Ruby
Name: title, Length: 920, dtype: object

In [9]:
# 1000-2999

pattern = "[12][0123456789][0123456789][0123456789]"
#2090

title[title.str.contains(pattern)]

20              OMeta#: Who? What? When? Where? Why? (2008)
24                  Segas Plans for World Domination (1993)
48        My CppCon 2016 trip report (thoughts on my fav...
59                       Mistakenly Seeking Solitude (2014)
66        Anti-Spoofing, BCP 38, and the Tragedy of the ...
                                ...
293076    The Effects of Computer Programming on the Bra...
293086    GM crops created superweed, say scientists (2005)
293104    Google's new logo was created by Russian desig...
293115    Attention and awareness in stage magic: turnin...
293116                    Dying vets fuck you letter (2013)
Name: title, Length: 15487, dtype: object

In [10]:
# 1000-2999

pattern = "[1-2][0-9][0-9][0-9]"
#2090

title[title.str.contains(pattern)]

20              OMeta#: Who? What? When? Where? Why? (2008)
24                  Segas Plans for World Domination (1993)
48        My CppCon 2016 trip report (thoughts on my fav...
59                       Mistakenly Seeking Solitude (2014)
66        Anti-Spoofing, BCP 38, and the Tragedy of the ...
                                ...
293076    The Effects of Computer Programming on the Bra...
293086    GM crops created superweed, say scientists (2005)
293104    Google's new logo was created by Russian desig...
293115    Attention and awareness in stage magic: turnin...
293116                    Dying vets fuck you letter (2013)
Name: title, Length: 15487, dtype: object

## Numeric Quantifier
    * a{3} -> the character `a` three times
    * a{3,5} -> the character `a` three, four or five times
    * a{,3} -> the character `a` zero, one, two or three times
    * a{8,} -> the character `a` eight or more times

In [11]:
"mend", "send", "bend"

# sd,sad,saad,saaad
re.search("sa{,3}d", "My name is saad")

## Single Character Quantifier

    * a* -> equivalent to a{0,} zero or more
    * a+ -> equivalent to a{1,} one or more
    * a? -> equivalent to a{0,1} zero or one

In [12]:
# 1000-2999
# here [0-9]{3} means that bracket multiply by 3

pattern = "[12][0-9]{3}"

title[title.str.contains(pattern)]

20              OMeta#: Who? What? When? Where? Why? (2008)
24                  Segas Plans for World Domination (1993)
48        My CppCon 2016 trip report (thoughts on my fav...
59                       Mistakenly Seeking Solitude (2014)
66        Anti-Spoofing, BCP 38, and the Tragedy of the ...
                                ...
293076    The Effects of Computer Programming on the Bra...
293086    GM crops created superweed, say scientists (2005)
293104    Google's new logo was created by Russian desig...
293115    Attention and awareness in stage magic: turnin...
293116                    Dying vets fuck you letter (2013)
Name: title, Length: 15487, dtype: object

In [13]:
# 1000-2999
# \d = [0-9]

pattern = "[12]\d{3}"

title[title.str.contains(pattern)]

20              OMeta#: Who? What? When? Where? Why? (2008)
24                  Segas Plans for World Domination (1993)
48        My CppCon 2016 trip report (thoughts on my fav...
59                       Mistakenly Seeking Solitude (2014)
66        Anti-Spoofing, BCP 38, and the Tragedy of the ...
                                ...
293076    The Effects of Computer Programming on the Bra...
293086    GM crops created superweed, say scientists (2005)
293104    Google's new logo was created by Russian desig...
293115    Attention and awareness in stage magic: turnin...
293116                    Dying vets fuck you letter (2013)
Name: title, Length: 15487, dtype: object

In [14]:
# email, e-mail

pattern = "e-{0,1}mail"

title[title.str.contains(pattern)]

90        This is what happens when you reply to spam email
173                  Correct way to validate email adresses
1010      Obama used a pseudonym in emails with Clinton,...
1012      The most broken part of your user experience i...
1029                 Visualization of Clinton email scandal
                                ...
291942    U.S., tech industry fight over email privacy h...
292071    U.S., tech industry fight over email privacy h...
292094    Why you shouldn't use disposable email address...
292341    Ex-Tesla engineer could face prison for email ...
292778    Show HN: LeadStage emaildomaindb  Flag email a...
Name: title, Length: 873, dtype: object

In [15]:
# email, e-mail

pattern = "(e-?mail)" #() is capture group, in extract, capture group is necessary

title.str.extract(pattern).value_counts(dropna= False)

0
NaN       292246
email        821
e-mail        52
Name: count, dtype: int64

In [16]:
# [pdf], [video], [..]
# \w = [A-Za-z0-9_]

pattern = "\[\w+\]"
title[title.str.contains(pattern)]

36        Cuba's DIY Inventions from 30 Years of Isolati...
114       A Possible Future of Software Development by  ...
153                                  FreeBSD Issue #1 [pdf]
154          Proprietary versus open instruction sets [pdf]
217                         Forever Alone Programming [FAP]
                                ...
292904                      How to Write About Africa [pdf]
292944    Interactively Develop a Reactjs Application [v...
293044    The Synthesis of Reliable Organisms from Unrel...
293075    Saul Bass Pitch Video for Bell System Logo Red...
293115    Attention and awareness in stage magic: turnin...
Name: title, Length: 5871, dtype: object

In [17]:
# [pdf], [video], [..]
# . = any character or special character except newline

pattern = "(\[.+\])"
title.str.extract(pattern).value_counts()

0
[pdf]                           3520
[video]                         1521
[audio]                           65
[2015]                            21
[Infographic]                     17
                                ...
[List]                             1
[Little Free Libraries]            1
[Live Demo and Ready Sample]       1
[Live Demo and Sample]             1
[yourtube]                         1
Name: count, Length: 994, dtype: int64

In [18]:
# [pdf], [video], [..]
# \w = [A-Za-z0-9_]

pattern = "(\[\w+\])"
title.str.extract(pattern).value_counts()

0
[pdf]            3531
[video]          1524
[audio]            65
[2015]             23
[Infographic]      18
                 ...
[NYTimes]           1
[NLG]               1
[NIST]              1
[NEW]               1
[yourtube]          1
Name: count, Length: 445, dtype: int64

## Negative Clas
    * `Negative Set` -> [^fud] == any character except f, u and d
    * `Negative Digit` -> [^0-9] == \D(any negative digit)
    * `Negative Word` -> \W
    * `Negative Whitespace` -> \S any character except space character

In [21]:
a = "I am learning javascript"
b = "I am learning javapython"
c = "Java is my favorite"
d = "I am learning Java"

pattern = "[Jj]ava[^Ss]"

print(re.search(pattern, b))

<re.Match object; span=(14, 19), match='javap'>

In [24]:
print("\bhello\b")

hell

In [31]:
a = "I am learning javascript"
b = "I am learning javapython"
c = "Java is my favorite"
d = "I am learning Java$"

pattern = "\\b[Jj]ava\\b"

print(re.search(pattern, d))

<re.Match object; span=(14, 18), match='Java'>

- `^` -> It will check pattern at the start
- `$` -> It will check pattern at the end

In [32]:
# [pdf], [video], [..]
# \w = [A-Za-z0-9_]

pattern = "^\[\w+\]"
title[title.str.contains(pattern)]

2396      [video] Introducing Bitcoin Flexible Transactions
3460      [T]he greatest programming tips and tricks you...
5917      [video] React Router v4 with Michael Jackson a...
6221      [video]Government Hacking and Human Rights: Th...
6438      [LIVE] NASA: Earth from Space  Video from the ...
                                ...
287517                    [Elixir] from Function  Processes
289811             [video] the science behind reading speed
290375    [Android]RecyclerItemDecoration-ItemDecoration...
292247    [screencast] Functional Programming in Python ...
292523    [Podcast] How to build a content marketing mac...
Name: title, Length: 304, dtype: object

In [33]:
# [pdf], [video], [..]
# \w = [A-Za-z0-9_]

pattern = "\[\w+\]$"
title[title.str.contains(pattern)]

36        Cuba's DIY Inventions from 30 Years of Isolati...
153                                  FreeBSD Issue #1 [pdf]
154          Proprietary versus open instruction sets [pdf]
217                         Forever Alone Programming [FAP]
249       How the Chinese Government Fabricates Social M...
                                ...
292904                      How to Write About Africa [pdf]
292944    Interactively Develop a Reactjs Application [v...
293044    The Synthesis of Reliable Organisms from Unrel...
293075    Saul Bass Pitch Video for Bell System Logo Red...
293115    Attention and awareness in stage magic: turnin...
Name: title, Length: 5384, dtype: object

In [34]:
# [pdf], [video], [..]
# \w = [A-Za-z0-9_]

pattern = "^\[\w+\]$"
title[title.str.contains(pattern)]

Series([], Name: title, dtype: object)

In [36]:
# [pdf], [video], [..]
# \w = [A-Za-z0-9_]

pattern = r"\bemail\b"
title[title.str.contains(pattern, flags=re.I)]

90        This is what happens when you reply to spam email
173                  Correct way to validate email adresses
816       WHATSAPP MAY INCORPORATE PASSCODE AND RECOVERY...
1012      The most broken part of your user experience i...
1029                 Visualization of Clinton email scandal
                                ...
292341    Ex-Tesla engineer could face prison for email ...
292373    Why Security Experts Are Using an Ancient Emai...
292451    Does Blackmailing Pay? Ashley Madison Extortio...
292778    Show HN: LeadStage emaildomaindb  Flag email a...
292886    Encrypted Email Service Tutanota Celebrates On...
Name: title, Length: 1214, dtype: object

In [37]:
# mysql, postgresql, cloudSQL, .....SQL

pattern = r"\w+sql"
title[title.str.contains(pattern, flags= re.I)]

43        PostgreSQL RDS pg-stat-ramdisk-size new featur...
240       Bidirectional Replication is coming to Postgre...
257       A fast PostgreSQL client library for Python: 3...
452            4 N00b MySQL Mistakes Every Programmer Makes
569           Postgresql 9.6.0 release schedule (9-29-2016)
                                ...
292272                                     PostgreSQL Magic
292456                       PostgreSQL for Ruby Developers
292567    Kingshard--A High-Performance Proxy for MySQL ...
292664    tiDB  Scalable RDBMS Inspired by Google F1 wit...
292857      Finally an easy to use report builder for MySQL
Name: title, Length: 775, dtype: object

In [38]:
pattern = r"\b[Cc]\b"
title[title.str.contains(pattern)]

87          Smart pointers and move semantics in modern C++
98                      A Simple Commodore 64 Game in C++17
252       Show HN: openemacs  a tiny emacs clone, ? 1024...
332       Jason Turner: A Simple Commodore 64 Game in C+...
457              Talking to C Programmers about C++ [video]
                                ...
292667           Swift VS Objective-C. iOS Developers Clash
292800    Mike Acton  Data-Oriented Design and C++  CppC...
292821             Try to not use the Python C API directly
292981                     New C++ Features  Move Semantics
293063    C++ encapsulation for Data-Oriented Design: pe...
Name: title, Length: 2381, dtype: object

## Lookarounds
- *positive lookahead -> zzz(?=abc) match zzz only when it is followed by abc
- *negative lookahead -> zzz(?!=abc) match zzz only when it is not followed by abc
- *positive lookbehind -> zzz(?<=abc) match zzz only when it is preceded by abc
- *negative lookbehind -> zzz(?<!=abc) match zzz only when it is not preceded by abc

In [40]:
d = "The New C, Standards worth it"

pattern = r"\b[Cc]\b(?!.)"

print(re.search(pattern, d))

None

In [41]:
# bye bye
# tata tata

pattern = r"\b(\w+)\s\1\b"
title[title.str.contains(pattern)]

C:\Users\moeed\AppData\Local\Temp\ipykernel_21168\3920447769.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  title[title.str.contains(pattern)]

2597      The Log Log Prior for the Frequency of Extrate...
2804          AI Is the New New Thing (And Its Taking Over)
9592      A very very very good vacation responder. The ...
10487     The Last Last Summer:  Donald Trump and the Fa...
10722     Grunt 1.0.1 1+ What is the difference and what...
                                ...
283224                        Flexbox Cheatsheet Cheatsheet
290301      Bye Bye MySQL and MongoDB. Guten Tag PostgreSQL
290390    How can I run commands based on the the proxim...
291630       QuoteMaker  A Markov Chain Generator Generator
292360          In PHP '00-00-00 00:00:00' means 1999-11-30
Name: title, Length: 180, dtype: object

In [42]:
# bye bye
# tata tata

pattern = r"\b(\w+)\s\1\s\1\b"
title[title.str.contains(pattern)]

C:\Users\moeed\AppData\Local\Temp\ipykernel_21168\2089061775.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  title[title.str.contains(pattern)]

9592      A very very very good vacation responder. The ...
41519     Mcdonalds copying cyriak  cows cows cows in th...
65901     340 billion billion billion billion: possible ...
75624        Developers Developers Developers Are Expensive
86064                  It's a small small small small world
100624                                    Bison Bison Bison
105208    Buffalo buffalo Buffalo buffalo buffalo buffal...
125147     Data Data Data  7,087 books dataset in one place
171163    Buffalo buffalo Buffalo buffalo buffalo buffal...
171322                                       Bork Bork Bork
173442          Byte Me, JavaScript Fatigue Fatigue Fatigue
175674     Always Always Always Use the Double Opt-In Intro
189871                               Dot Dot Dot HTML5 Game
229507                                          Now Now Now
236050    General-purpose tool-building factory factory ...
248287    From Side Project to Profitable Start Up  Part...
273073    Seeding /dev/random with with with a $10 SDR r...
Name: title, dtype: object

In [46]:
# Problem OK OK Problem

pattern = r"\b(\w+)\s(\w+)\s\2\s\1\b"

title[title.str.contains(pattern)]

C:\Users\moeed\AppData\Local\Temp\ipykernel_21168\3226136428.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  title[title.str.contains(pattern)]

65901     340 billion billion billion billion: possible ...
86064                  It's a small small small small world
248287    From Side Project to Profitable Start Up  Part...
Name: title, dtype: object

In [48]:
# e mail, e-mail, email

pattern = r"(e[\s-]?mail)"

title.str.extract(pattern, flags=re.I).value_counts()

0
email     803
Email     776
e-mail     52
e mail     28
e Mail     25
E-mail     20
E-Mail     16
E mail      3
EMAIL       3
eMail       3
EMail       2
Name: count, dtype: int64

In [49]:
pattern = r"(e[\s-]?mail)"

title = title.str.replace(pattern, "email", flags=re.I, regex=True)

In [50]:
pattern = r"(e[\s-]?mail)"

title.str.extract(pattern, flags=re.I).value_counts()

0
email    1731
Name: count, dtype: int64

In [51]:
url = hn.url
url

0         http://www.regulations.gov/document?D=FDA-2015...
1          https://www.sqlite.org/sqlar/doc/trunk/README.md
2         https://medium.com/vanmoof/our-secrets-out-f21...
3         http://cacm.acm.org/magazines/2011/7/109891-al...
4         https://www.talend.com/blog/2016/05/12/talend-...
                                ...
293114                                                  NaN
293115    http://people.cs.uchicago.edu/~luitien/nrn2473...
293116    http://dangerousminds.net/comments/dying_vets_...
293117              https://www.zend.com/en/resources/php-7
293118      http://newsroom.toyota.co.jp/en/detail/9233109/
Name: url, Length: 293119, dtype: object

In [55]:
pattern = r"https?://(?P<Domain>[\w.]+)/?[\w.]*"
url.str.extract(pattern)

                        Domain
0          www.regulations.gov
1               www.sqlite.org
2                   medium.com
3                 cacm.acm.org
4               www.talend.com
...                        ...
293114                     NaN
293115  people.cs.uchicago.edu
293116      dangerousminds.net
293117            www.zend.com
293118   newsroom.toyota.co.jp

[293119 rows x 1 columns]

# Find Protocol, Domain, and Path

In [58]:
pattern = r"(?P<Protocol>https?)://(?P<Domain>[\w.]+)/(?P<Path>[\w./]*)"

url.str.extract(pattern)

,Protocol,Domain,Path
0,http,www.regulations.gov,document
1,https,www.sqlite.org,sqlar/doc/trunk/README.md
2,https,medium.com,vanmoof/our
3,http,cacm.acm.org,magazines/2011/7/109891
4,https,www.talend.com,blog/2016/05/12/talend
...,...,...,...
293114,NaN,NaN,NaN
293115,http,people.cs.uchicago.edu,
293116,http,dangerousminds.net,comments/dying_vets_fuck_you_letter_to_george_...
293117,https,www.zend.com,en/resources/php
293118,http,newsroom.toyota.co.jp,en/detail/9233109/